import "server-only";

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { BRAND } from "@/lib/brand";

export interface PassportPdfInput {
  studentName: string;
  rows: Array<{
    name: string;
    description?: string;
    hours: number;
    evidenced: boolean;
  }>;
  issuedAt: string;
}

/**
 * Generate a Skills Passport PDF — a one-page evidence appendix for the
 * certificate: each competency, whether it has evidence, and logged hours.
 * Signed competencies are marked. Uses pdf-lib (already a dependency).
 */
export async function generatePassportPdf(data: PassportPdfInput): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]); // A4 portrait
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const ink = rgb(0.1, 0.1, 0.1);
  const muted = rgb(0.4, 0.4, 0.4);
  const green = rgb(0.1, 0.5, 0.2);
  let y = 760;

  // Header
  page.drawRectangle({ x: 40, y: 60, width: 515, height: 722, borderColor: ink, borderWidth: 2 });
  page.drawText("Skills Passport", { x: 60, y, size: 26, font: bold, color: ink });
  y -= 24;
  page.drawText(data.studentName, { x: 60, y, size: 16, font, color: ink });
  y -= 18;
  page.drawText(`Issued ${data.issuedAt}`, { x: 60, y, size: 11, font, color: muted });
  y -= 30;
  page.drawLine({ start: { x: 60, y }, end: { x: 535, y }, thickness: 1, color: muted });
  y -= 22;

  // Competency table
  const totalHours = data.rows.reduce((a, r) => a + r.hours, 0);
  const evidenced = data.rows.filter((r) => r.evidenced).length;
  page.drawText(`Competencies: ${evidenced}/${data.rows.length} evidenced · ${totalHours.toFixed(1)}h logged`, {
    x: 60, y, size: 12, font: bold, color: ink,
  });
  y -= 22;

  for (const r of data.rows) {
    if (y < 90) break; // one page; truncate rather than overflow
    page.drawText(`•  ${r.name}`, { x: 60, y, size: 12, font: bold, color: ink });
    if (r.description) {
      page.drawText(r.description, { x: 74, y: y - 14, size: 9, font, color: muted });
    }
    const status = r.evidenced ? `evidenced · ${r.hours.toFixed(1)}h` : "not yet evidenced";
    page.drawText(status, { x: 420, y, size: 10, font, color: r.evidenced ? green : muted });
    y -= r.description ? 32 : 20;
  }

  // Footer
  y = 82;
  page.drawText(`Generated by ${BRAND.name} — evidence-based competency record.`, { x: 60, y, size: 9, font, color: muted });

  const bytes = await doc.save();
  return Buffer.from(bytes);
}
