-- =============================================================================
-- Psychopharm: assign consistent pharmacological classes to all medications
-- (2026-08-14). 122/151 rows had drug_class = NULL; the remainder used a mix of
-- mechanism- and indication-based labels. This assigns a clinically meaningful,
-- consistent class to every drug, then standardises the pre-existing labels.
-- Additive + reversible (set drug_class back to NULL to revert).
-- =============================================================================

-- 1) Assign classes to the 122 uncategorised drugs.
update public.psych_drugs d
set drug_class = v.drug_class
from (values
  ('Acamprosate', 'Alcohol-aversion / relapse-prevention agent'),
  ('Agomelatine', 'Melatonergic antidepressant'),
  ('Amitriptyline', 'Tricyclic antidepressant (TCA)'),
  ('Amoxapine', 'Tricyclic antidepressant (TCA)'),
  ('Amphetamine (D,L)', 'Stimulant'),
  ('Amphetamine (D)', 'Stimulant'),
  ('Armodafinil', 'Wakefulness-promoting agent'),
  ('Asenapine', 'Atypical antipsychotic'),
  ('Atomoxetine', 'Non-stimulant ADHD agent'),
  ('Blonanserin', 'Atypical antipsychotic'),
  ('Bremelanotide', 'Melanocortin agonist'),
  ('Brexanolone', 'Neuroactive steroid'),
  ('Buprenorphine', 'Opioid partial agonist'),
  ('Bupropion', 'NDRI antidepressant'),
  ('Buspirone', 'Azapirone anxiolytic'),
  ('Caprylidene', 'Medical food (metabolic)'),
  ('Carbamazepine', 'Anticonvulsant / mood stabilizer'),
  ('Chlorpromazine', 'Typical antipsychotic'),
  ('Clomipramine', 'Tricyclic antidepressant (TCA)'),
  ('Clonidine', 'Alpha-2 agonist'),
  ('Clozapine', 'Atypical antipsychotic'),
  ('Cyamemazine', 'Typical antipsychotic'),
  ('Desipramine', 'Tricyclic antidepressant (TCA)'),
  ('Desvenlafaxine', 'SNRI'),
  ('Deutetrabenazine', 'VMAT2 inhibitor'),
  ('Dextromethorphan', 'NMDA receptor antagonist (antitussive)'),
  ('Diazepam', 'Benzodiazepine'),
  ('Diphenhydramine', 'Sedative antihistamine'),
  ('Disulfiram', 'Alcohol-aversion agent'),
  ('Donepezil', 'Cholinesterase inhibitor'),
  ('Dothiepin', 'Tricyclic antidepressant (TCA)'),
  ('Doxepin', 'Tricyclic antidepressant (TCA)'),
  ('Esketamine', 'Rapid-acting antidepressant (NMDA antagonist)'),
  ('Estazolam', 'Benzodiazepine'),
  ('Eszopiclone', 'Sedative-hypnotic (Z-drug)'),
  ('Flibanserin', 'Serotonin 5-HT1A/2A modulator'),
  ('Flumazenil', 'Benzodiazepine receptor antagonist'),
  ('Flunitrazepam', 'Benzodiazepine'),
  ('Flupenthixol', 'Typical antipsychotic'),
  ('Fluphenazine', 'Typical antipsychotic'),
  ('Flurazepam', 'Benzodiazepine'),
  ('Fluvoxamine', 'SSRI'),
  ('Gabapentin', 'Gabapentinoid'),
  ('Galantamine', 'Cholinesterase inhibitor'),
  ('Guanfacine', 'Alpha-2 agonist'),
  ('Haloperidol', 'Typical antipsychotic'),
  ('Iloperidone', 'Atypical antipsychotic'),
  ('Imipramine', 'Tricyclic antidepressant (TCA)'),
  ('Isocarboxazid', 'MAOI antidepressant'),
  ('Ketamine', 'Rapid-acting antidepressant (NMDA antagonist)'),
  ('Lemborexant', 'Orexin receptor antagonist'),
  ('Levetiracetam', 'Anticonvulsant'),
  ('Levomilnacipran', 'SNRI'),
  ('Lofepramine', 'Tricyclic antidepressant (TCA)'),
  ('Lofexidine', 'Alpha-2 agonist'),
  ('Loflazepate', 'Benzodiazepine'),
  ('Loxapine', 'Typical antipsychotic'),
  ('Lumateperone', 'Atypical antipsychotic'),
  ('Lurasidone', 'Atypical antipsychotic'),
  ('Maprotiline', 'Tetracyclic antidepressant'),
  ('Memantine', 'NMDA receptor antagonist'),
  ('Methylfolate (L)', 'Medical food (adjunctive antidepressant)'),
  ('Methylphenidate (D,L)', 'Stimulant'),
  ('Methylphenidate (D)', 'Stimulant'),
  ('Mianserin', 'Tetracyclic antidepressant'),
  ('Midazolam', 'Benzodiazepine'),
  ('Milnacipran', 'SNRI'),
  ('Moclobemide', 'MAOI antidepressant (reversible)'),
  ('Modafinil', 'Wakefulness-promoting agent'),
  ('Molindone', 'Typical antipsychotic'),
  ('Nalmefene', 'Opioid antagonist'),
  ('Naltrexone', 'Opioid antagonist'),
  ('Naltrexone/Bupropion', 'Combination (opioid antagonist + NDRI)'),
  ('Nefazodone', 'SARI antidepressant'),
  ('Nortriptyline', 'Tricyclic antidepressant (TCA)'),
  ('Olanzapine', 'Atypical antipsychotic'),
  ('Oxcarbazepine', 'Anticonvulsant / mood stabilizer'),
  ('Paliperidone', 'Atypical antipsychotic'),
  ('Perospirone', 'Atypical antipsychotic'),
  ('Phenelzine', 'MAOI antidepressant'),
  ('Phentermine/topiramate', 'Combination (weight management)'),
  ('Pimavanserin', '5-HT2A inverse agonist (antipsychotic)'),
  ('Pimozide', 'Typical antipsychotic'),
  ('Pipothiazine', 'Typical antipsychotic'),
  ('Pitolisant', 'Histamine H3 receptor antagonist'),
  ('Prazosin', 'Alpha-1 blocker'),
  ('Pregabalin', 'Gabapentinoid'),
  ('Propranolol', 'Beta-blocker'),
  ('Protriptyline', 'Tricyclic antidepressant (TCA)'),
  ('Quazepam', 'Benzodiazepine'),
  ('Ramelteon', 'Melatonin receptor agonist'),
  ('Reboxetine', 'NRI antidepressant'),
  ('Rivastigmine', 'Cholinesterase inhibitor'),
  ('Selegiline', 'MAOI antidepressant'),
  ('Sertindole', 'Atypical antipsychotic'),
  ('Sildenafil', 'PDE5 inhibitor'),
  ('Sodium oxybate', 'CNS depressant (narcolepsy)'),
  ('solriamfetol', 'Wakefulness-promoting agent'),
  ('Suvorexant', 'Orexin receptor antagonist'),
  ('Tasimelteon', 'Melatonin receptor agonist'),
  ('Temazepam', 'Benzodiazepine'),
  ('Thioridazine', 'Typical antipsychotic'),
  ('Thiothixene', 'Typical antipsychotic'),
  ('Tiagabine', 'Anticonvulsant'),
  ('Tianeptine', 'Atypical antidepressant'),
  ('Tranylcypromine', 'MAOI antidepressant'),
  ('Trazodone', 'SARI antidepressant'),
  ('Triazolam', 'Benzodiazepine'),
  ('Trifluoperazine', 'Typical antipsychotic'),
  ('Trihexyphenidyl', 'Anticholinergic'),
  ('Triiodothyronine', 'Thyroid hormone'),
  ('Trimipramine', 'Tricyclic antidepressant (TCA)'),
  ('Valbenazine', 'VMAT2 inhibitor'),
  ('Varenicline', 'Nicotinic partial agonist'),
  ('Vilazodone', 'Serotonin modulator antidepressant'),
  ('Vortioxetine', 'Serotonin modulator antidepressant'),
  ('Zaleplon', 'Sedative-hypnotic (Z-drug)'),
  ('Zolpidem', 'Sedative-hypnotic (Z-drug)'),
  ('Zonisamide', 'Anticonvulsant'),
  ('Zopiclone', 'Sedative-hypnotic (Z-drug)'),
  ('Zotepine', 'Atypical antipsychotic'),
  ('Zuclopenthixol', 'Typical antipsychotic')
) as v(generic_name, drug_class)
where d.generic_name = v.generic_name and d.drug_class is null;

-- 2) Standardise the pre-existing inconsistent labels.
update public.psych_drugs set drug_class = 'Typical antipsychotic'
  where drug_class = 'Dopamine antagonist (antipsychotic)';
update public.psych_drugs set drug_class = 'Sedative antihistamine'
  where drug_class = 'Sedative antihistamine (anxiolytic)';
update public.psych_drugs set drug_class = 'Anticonvulsant'
  where drug_class in ('Anticonvulsant (adjunctive)', 'Anticonvulsant / mood stabilizer');
