/**
 * Quiz bank (v5 §4.1 / brief §11.3 content volume) — 20 sourced items,
 * order-the-steps + would-you-report focus, wired into MSE and OSCE
 * completion. Every item carries a one-line rationale citing its source.
 * No item ships without one.
 */

import type { QuizItem } from "./quiz";

export const QUIZ_BANK: QuizItem[] = [
  // ---- Order-the-steps: risk assessment / intake sequence ----
  {
    id: "q-order-risk-1",
    type: "order_steps",
    prompt: "Order the risk-assessment sequence in a first session where a patient mentions hopelessness.",
    options: [
      "Screen in clear language → explore plan/means/intent → check protective factors → make a safety plan",
      "Explore the mood first → end the session → note risk 'for next time'",
      "Ask the family → then the patient → then decide",
      "Reassure early → move to another topic → document 'no risk'",
    ],
    correct: 0,
    rationale: "Risk asked directly, then plan/means/intent, then protective factors, then a concrete safety plan — in that order.",
    source: "WHO mhGAP-IG 2.0 (2016), assessment & management of self-harm/suicide",
  },
  {
    id: "q-order-risk-2",
    type: "order_steps",
    prompt: "A patient says 'sometimes I think it would be easier to not be here.' Order the correct next steps.",
    options: [
      "Ask about plan and means → assess intent → involve support if imminent → document",
      "Tell them 'everyone feels that way' → change topic",
      "End the session early to avoid escalation",
      "Call the family before asking anything more",
    ],
    correct: 0,
    rationale: "Passive ideation still demands the plan/means/intent probe; support and documentation follow.",
    source: "WHO mhGAP-IG 2.0 (2016)",
  },
  {
    id: "q-order-intake-1",
    type: "order_steps",
    prompt: "Order the first-session intake sequence.",
    options: [
      "Presenting complaint in own words → history (sleep/appetite/function) → risk screen → expectations & consent",
      "Diagnosis first → then questions",
      "Family's account only → then the patient",
      "Forms first → then talk",
    ],
    correct: 0,
    rationale: "The complaint in the patient's own words opens; the physical/function triad and risk follow before any framing.",
    source: "DSM-5 Cultural Formulation Interview (2013) + mhGAP",
  },
  {
    id: "q-order-crisis-1",
    type: "order_steps",
    prompt: "A client has a specific plan and the means available tonight. Order your actions.",
    options: [
      "Stay with them → activate support/referral → involve emergency services if needed → document",
      "End the session → call tomorrow",
      "Give a leaflet → schedule next week",
      "Promise confidentiality → let them leave alone",
    ],
    correct: 0,
    rationale: "Imminent risk: you do not leave them alone; support and emergency involvement happen before documentation.",
    source: "WHO mhGAP-IG 2.0 (2016) — imminent self-harm",
  },
  {
    id: "q-order-mse-1",
    type: "order_steps",
    prompt: "Order the MSE write-up domains in the standard sequence.",
    options: [
      "Appearance → behaviour → speech → mood → affect → thought form/content → perception → cognition → insight → judgment",
      "Mood first, appearance last",
      "Perception before speech",
      "Insight before mood",
    ],
    correct: 0,
    rationale: "The standard MSE order moves from the observable surface inward to thought, perception and judgment.",
    source: "Standard MSE structure (British Psychological Society guidance)",
  },
  // ---- Would-you-report: MHA 2017 / POCSO applied ----
  {
    id: "q-report-pocso-1",
    type: "would_you_report",
    prompt: "A 13-year-old tells you a tutor has been touching her. She begs you not to tell. Would you report?",
    options: [
      "Yes — POCSO mandates reporting to police/Childline, no discretion",
      "Only with parental consent",
      "Only if she repeats it next session",
      "No — confidentiality protects the disclosure",
    ],
    correct: 0,
    rationale: "POCSO Section 19 makes reporting mandatory; failure is itself an offence.",
    source: "POCSO 2012, Section 19",
  },
  {
    id: "q-report-pocso-2",
    type: "would_you_report",
    prompt: "An 8-year-old draws a picture of 'the bad thing' during play therapy. No words yet. Would you report?",
    options: [
      "Yes — the drawing is a disclosure signal; mandated reporting applies",
      "Wait until they can describe it in words",
      "Only if a family member confirms",
      "No — art is ambiguous",
    ],
    correct: 0,
    rationale: "Non-verbal disclosure is still disclosure; POCSO's duty is triggered by information, however conveyed.",
    source: "POCSO 2012, Section 19 (child-friendly procedures)",
  },
  {
    id: "q-report-pocso-3",
    type: "would_you_report",
    prompt: "A 15-year-old says a classmate showed them pornographic images. Would you report?",
    options: [
      "Assess whether the classmate is a minor and the context — child-on-child exposure may trigger POCSO duties",
      "Never report child-to-child matters",
      "Report the 15-year-old as an offender",
      "It's the parents' problem alone",
    ],
    correct: 0,
    rationale: "POCSO covers child-on-child offences; assessment of context precedes any action, but the duty is real.",
    source: "POCSO 2012, Section 2(d) — 'child' includes any person under 18",
  },
  {
    id: "q-report-mha-1",
    type: "would_you_report",
    prompt: "A client with an advance directive refusing ECT is now in a severe relapse, unable to consent. The family demands ECT. What do you do?",
    options: [
      "Honour the directive; only the MHA's narrow Section 5(4) pathway can override it",
      "Follow the family — they know best",
      "Do ECT because it worked before",
      "Ignore the directive as 'just paperwork'",
    ],
    correct: 0,
    rationale: "MHA 2017 Section 5 makes advance directives binding; exceptions are narrow and procedurally defined.",
    source: "Mental Healthcare Act 2017, Section 5",
  },
  {
    id: "q-report-mha-2",
    type: "would_you_report",
    prompt: "You witness a patient at a facility being tied to the bed 'because he shouted'. Would you report?",
    options: [
      "Yes — restraint beyond the MHA's narrow emergency conditions is a violation with a reporting duty",
      "No — hospitals know their business",
      "Only if the patient asks you to",
      "Mention it casually to the nurse, then drop it",
    ],
    correct: 0,
    rationale: "MHA 2017 restricts restraint sharply and requires recording/reporting; witnessing a violation carries a duty.",
    source: "Mental Healthcare Act 2017, Section 98 (restraint)",
  },
  {
    id: "q-report-mha-3",
    type: "would_you_report",
    prompt: "A student client in therapy reveals they were turned away from a government clinic for being 'too complex'. Would you report?",
    options: [
      "Yes — MHA 2017 gives a right to mental healthcare and complaint mechanisms for denial",
      "No — it's not your business",
      "Only if they pay you to",
      "Advise them to try a private clinic instead",
    ],
    correct: 0,
    rationale: "MHA 2017 establishes the right to accessible mental healthcare; denial can be raised through its mechanisms.",
    source: "Mental Healthcare Act 2017, Section 18-19 (right to services)",
  },
  // ---- Standard-of-care vs common-practice ----
  {
    id: "q-soc-1",
    type: "standard_vs_common",
    prompt: "A first-episode patient's family wants 'a diagnosis in writing' after one session. Which is standard of care?",
    options: [
      "Explain assessment is ongoing; premature labelling is harmful (standard)",
      "Write the diagnosis to keep the family happy (common but wrong)",
      "Refuse to ever document anything",
      "Diagnose what the family suspects",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "Diagnosis follows assessment; a label without it is an error that shapes the patient's identity.",
    source: "RCI code of ethics — practice within competence",
  },
  {
    id: "q-soc-2",
    type: "standard_vs_common",
    prompt: "A client asks you to recommend starting or stopping their antidepressant. Which is standard?",
    options: [
      "Describe your observations; medication decisions sit with the prescriber (standard)",
      "Advise the dose change yourself (common but outside scope)",
      "Tell them to stop immediately",
      "Double the dose yourself",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "Dose decisions are prescriber decisions; counselling scope covers observation and support, not titration.",
    source: "RCI scope of practice",
  },
  {
    id: "q-soc-3",
    type: "standard_vs_common",
    prompt: "A worried mother asks you to 'test my son for ADHD' in the first session. Which is standard?",
    options: [
      "Multi-informant assessment over time, with the teacher's report as one input (standard)",
      "A one-session label to end the worry (common but wrong)",
      "Refuse to see the child at all",
      "Diagnose from the mother's description alone",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "ADHD assessment requires multiple informants and settings; a first-session label is malpractice.",
    source: "ICD-11 / DSM-5 diagnostic requirements",
  },
  // ---- Best-response ----
  {
    id: "q-br-1",
    type: "best_response",
    prompt: "A patient says 'I'm not feeling fresh.' What is the highest-yield next question?",
    options: [
      "'Walk me through yesterday morning — from waking up to leaving the house.'",
      "'Are you feeling sad?'",
      "'Have you tried yoga?'",
      "'That usually means depression.'",
    ],
    correct: 0,
    rationale: "Instantiate, don't guess — 'not feeling fresh' carries constipation, sleep, anaemia and mood; the description disambiguates.",
    source: "Nichter, Idioms of Distress (1981); DSM-5 CFI",
  },
  {
    id: "q-br-2",
    type: "best_response",
    prompt: "A patient says 'I think about dying a lot.' What do you say next?",
    options: [
      "'Thank you for telling me. When you say dying, what have you been thinking exactly?'",
      "'Don't worry, that's normal.'",
      "'Let's talk about something happier.'",
      "'You'll be fine, trust me.'",
    ],
    correct: 0,
    rationale: "Take the disclosure seriously, thank them, and probe the specifics — reassurance before exploration is the #1 novice error.",
    source: "WHO mhGAP-IG 2.0 (2016)",
  },
  // ---- Spot-the-error ----
  {
    id: "q-spot-1",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'My husband says I'm losing my mind.'\nStudent: 'Don't worry, you're definitely not!'",
    options: [
      "The patient's self-report is the concern",
      "Reassuring before exploring the fear",
      "Noting the husband's words",
      "Listening without interrupting",
    ],
    correct: 1,
    rationale: "Premature reassurance closes exploration — the fear deserves to be named and examined, not dismissed.",
    source: "mhGAP-IG 2.0 (2016); motivational interviewing literature",
  },
  {
    id: "q-spot-2",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Student: 'How's your sleep?'\nPatient: 'Terrible.'\nStudent: 'So you sleep terribly. Is it your wife's cooking?'",
    options: [
      "Asking about sleep",
      "Reflecting the answer",
      "Guessing the cause (the wife's cooking)",
      "Pausing for the patient",
    ],
    correct: 2,
    rationale: "A leading, guessing question closes the real story — the open 'what keeps you awake?' invites description.",
    source: "Clinical interviewing literature (open questions)",
  },
  {
    id: "q-spot-3",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'The doctor said my son is hyperactive and needs testing.'\nStudent: 'Let's test him for ADHD right away.'",
    options: [
      "Listening to the mother's account",
      "Ordering a label after one report",
      "Noting the teacher's concern",
      "Asking about the child's behaviour",
    ],
    correct: 1,
    rationale: "One informant's report is not an assessment — ADHD needs multi-informant evaluation over time.",
    source: "DSM-5 ADHD criteria (multiple settings)",
  },
  // ---- Order-the-steps: MSE completion + OSCE completion hooks ----
  {
    id: "q-order-osce-1",
    type: "order_steps",
    prompt: "Order the breaking-bad-news sequence (OSCE station 3).",
    options: [
      "Warning shot → the news plainly → check understanding & emotion → next steps & support",
      "The news first, no preamble → leave",
      "Details first, news last",
      "Ask the family to leave before starting",
    ],
    correct: 0,
    rationale: "The warning shot, plain statement, emotional check, and next steps are the standard protocol.",
    source: "SPIKES protocol (Baile et al., 2000)",
  },
  {
    id: "q-order-osce-2",
    type: "order_steps",
    prompt: "Order the capacity-assessment components (OSCE station 4).",
    options: [
      "Understand → retain → weigh → communicate the decision",
      "Weigh first, understand last",
      "Ask the family what they think",
      "Assume capacity because he's coherent",
    ],
    correct: 0,
    rationale: "Capacity = understanding, retention, weighing and communication — the four-part test.",
    source: "Mental Capacity framework (UK MCA 2005; parallel Indian doctrine)",
  },
];