/**
 * Quiz bank (v5 §4.1 / brief §11.3 content volume) — 20 sourced items,
 * order-the-steps + would-you-report focus, wired into MSE and OSCE
 * completion. Every item carries a one-line rationale citing its source.
 * No item ships without one.
 */

import type { QuizItem } from "./quiz";

export const QUIZ_BANK: QuizItem[] = [
  // ---- Order-the-steps: risk assessment / intake sequence ----
  {
    id: "q-order-risk-1",
    type: "order_steps",
    prompt: "Order the risk-assessment sequence in a first session where a patient mentions hopelessness.",
    options: [
      "Screen in clear language → explore plan/means/intent → check protective factors → make a safety plan",
      "Explore the mood first → end the session → note risk 'for next time'",
      "Ask the family → then the patient → then decide",
      "Reassure early → move to another topic → document 'no risk'",
    ],
    correct: 0,
    rationale: "Risk asked directly, then plan/means/intent, then protective factors, then a concrete safety plan — in that order.",
    source: "WHO mhGAP-IG 2.0 (2016), assessment & management of self-harm/suicide",
  },
  {
    id: "q-order-risk-2",
    type: "order_steps",
    prompt: "A patient says 'sometimes I think it would be easier to not be here.' Order the correct next steps.",
    options: [
      "Ask about plan and means → assess intent → involve support if imminent → document",
      "Tell them 'everyone feels that way' → change topic",
      "End the session early to avoid escalation",
      "Call the family before asking anything more",
    ],
    correct: 0,
    rationale: "Passive ideation still demands the plan/means/intent probe; support and documentation follow.",
    source: "WHO mhGAP-IG 2.0 (2016)",
  },
  {
    id: "q-order-intake-1",
    type: "order_steps",
    prompt: "Order the first-session intake sequence.",
    options: [
      "Presenting complaint in own words → history (sleep/appetite/function) → risk screen → expectations & consent",
      "Diagnosis first → then questions",
      "Family's account only → then the patient",
      "Forms first → then talk",
    ],
    correct: 0,
    rationale: "The complaint in the patient's own words opens; the physical/function triad and risk follow before any framing.",
    source: "DSM-5 Cultural Formulation Interview (2013) + mhGAP",
  },
  {
    id: "q-order-crisis-1",
    type: "order_steps",
    prompt: "A client has a specific plan and the means available tonight. Order your actions.",
    options: [
      "Stay with them → activate support/referral → involve emergency services if needed → document",
      "End the session → call tomorrow",
      "Give a leaflet → schedule next week",
      "Promise confidentiality → let them leave alone",
    ],
    correct: 0,
    rationale: "Imminent risk: you do not leave them alone; support and emergency involvement happen before documentation.",
    source: "WHO mhGAP-IG 2.0 (2016) — imminent self-harm",
  },
  {
    id: "q-order-mse-1",
    type: "order_steps",
    prompt: "Order the MSE write-up domains in the standard sequence.",
    options: [
      "Appearance → behaviour → speech → mood → affect → thought form/content → perception → cognition → insight → judgment",
      "Mood first, appearance last",
      "Perception before speech",
      "Insight before mood",
    ],
    correct: 0,
    rationale: "The standard MSE order moves from the observable surface inward to thought, perception and judgment.",
    source: "Standard MSE structure (British Psychological Society guidance)",
  },
  // ---- Would-you-report: MHA 2017 / POCSO applied ----
  {
    id: "q-report-pocso-1",
    type: "would_you_report",
    prompt: "A 13-year-old tells you a tutor has been touching her. She begs you not to tell. Would you report?",
    options: [
      "Yes — POCSO mandates reporting to police/Childline, no discretion",
      "Only with parental consent",
      "Only if she repeats it next session",
      "No — confidentiality protects the disclosure",
    ],
    correct: 0,
    rationale: "POCSO Section 19 makes reporting mandatory; failure is itself an offence.",
    source: "POCSO 2012, Section 19",
  },
  {
    id: "q-report-pocso-2",
    type: "would_you_report",
    prompt: "An 8-year-old draws a picture of 'the bad thing' during play therapy. No words yet. Would you report?",
    options: [
      "Yes — the drawing is a disclosure signal; mandated reporting applies",
      "Wait until they can describe it in words",
      "Only if a family member confirms",
      "No — art is ambiguous",
    ],
    correct: 0,
    rationale: "Non-verbal disclosure is still disclosure; POCSO's duty is triggered by information, however conveyed.",
    source: "POCSO 2012, Section 19 (child-friendly procedures)",
  },
  {
    id: "q-report-pocso-3",
    type: "would_you_report",
    prompt: "A 15-year-old says a classmate showed them pornographic images. Would you report?",
    options: [
      "Assess whether the classmate is a minor and the context — child-on-child exposure may trigger POCSO duties",
      "Never report child-to-child matters",
      "Report the 15-year-old as an offender",
      "It's the parents' problem alone",
    ],
    correct: 0,
    rationale: "POCSO covers child-on-child offences; assessment of context precedes any action, but the duty is real.",
    source: "POCSO 2012, Section 2(d) — 'child' includes any person under 18",
  },
  {
    id: "q-report-mha-1",
    type: "would_you_report",
    prompt: "A client with an advance directive refusing ECT is now in a severe relapse, unable to consent. The family demands ECT. What do you do?",
    options: [
      "Honour the directive; only the MHA's narrow Section 5(4) pathway can override it",
      "Follow the family — they know best",
      "Do ECT because it worked before",
      "Ignore the directive as 'just paperwork'",
    ],
    correct: 0,
    rationale: "MHA 2017 Section 5 makes advance directives binding; exceptions are narrow and procedurally defined.",
    source: "Mental Healthcare Act 2017, Section 5",
  },
  {
    id: "q-report-mha-2",
    type: "would_you_report",
    prompt: "You witness a patient at a facility being tied to the bed 'because he shouted'. Would you report?",
    options: [
      "Yes — restraint beyond the MHA's narrow emergency conditions is a violation with a reporting duty",
      "No — hospitals know their business",
      "Only if the patient asks you to",
      "Mention it casually to the nurse, then drop it",
    ],
    correct: 0,
    rationale: "MHA 2017 restricts restraint sharply and requires recording/reporting; witnessing a violation carries a duty.",
    source: "Mental Healthcare Act 2017, Section 98 (restraint)",
  },
  {
    id: "q-report-mha-3",
    type: "would_you_report",
    prompt: "A student client in therapy reveals they were turned away from a government clinic for being 'too complex'. Would you report?",
    options: [
      "Yes — MHA 2017 gives a right to mental healthcare and complaint mechanisms for denial",
      "No — it's not your business",
      "Only if they pay you to",
      "Advise them to try a private clinic instead",
    ],
    correct: 0,
    rationale: "MHA 2017 establishes the right to accessible mental healthcare; denial can be raised through its mechanisms.",
    source: "Mental Healthcare Act 2017, Section 18-19 (right to services)",
  },
  // ---- Standard-of-care vs common-practice ----
  {
    id: "q-soc-1",
    type: "standard_vs_common",
    prompt: "A first-episode patient's family wants 'a diagnosis in writing' after one session. Which is standard of care?",
    options: [
      "Explain assessment is ongoing; premature labelling is harmful (standard)",
      "Write the diagnosis to keep the family happy (common but wrong)",
      "Refuse to ever document anything",
      "Diagnose what the family suspects",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "Diagnosis follows assessment; a label without it is an error that shapes the patient's identity.",
    source: "RCI code of ethics — practice within competence",
  },
  {
    id: "q-soc-2",
    type: "standard_vs_common",
    prompt: "A client asks you to recommend starting or stopping their antidepressant. Which is standard?",
    options: [
      "Describe your observations; medication decisions sit with the prescriber (standard)",
      "Advise the dose change yourself (common but outside scope)",
      "Tell them to stop immediately",
      "Double the dose yourself",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "Dose decisions are prescriber decisions; counselling scope covers observation and support, not titration.",
    source: "RCI scope of practice",
  },
  {
    id: "q-soc-3",
    type: "standard_vs_common",
    prompt: "A worried mother asks you to 'test my son for ADHD' in the first session. Which is standard?",
    options: [
      "Multi-informant assessment over time, with the teacher's report as one input (standard)",
      "A one-session label to end the worry (common but wrong)",
      "Refuse to see the child at all",
      "Diagnose from the mother's description alone",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "ADHD assessment requires multiple informants and settings; a first-session label is malpractice.",
    source: "ICD-11 / DSM-5 diagnostic requirements",
  },
  // ---- Best-response ----
  {
    id: "q-br-1",
    type: "best_response",
    prompt: "A patient says 'I'm not feeling fresh.' What is the highest-yield next question?",
    options: [
      "'Walk me through yesterday morning — from waking up to leaving the house.'",
      "'Are you feeling sad?'",
      "'Have you tried yoga?'",
      "'That usually means depression.'",
    ],
    correct: 0,
    rationale: "Instantiate, don't guess — 'not feeling fresh' carries constipation, sleep, anaemia and mood; the description disambiguates.",
    source: "Nichter, Idioms of Distress (1981); DSM-5 CFI",
  },
  {
    id: "q-br-2",
    type: "best_response",
    prompt: "A patient says 'I think about dying a lot.' What do you say next?",
    options: [
      "'Thank you for telling me. When you say dying, what have you been thinking exactly?'",
      "'Don't worry, that's normal.'",
      "'Let's talk about something happier.'",
      "'You'll be fine, trust me.'",
    ],
    correct: 0,
    rationale: "Take the disclosure seriously, thank them, and probe the specifics — reassurance before exploration is the #1 novice error.",
    source: "WHO mhGAP-IG 2.0 (2016)",
  },
  // ---- Spot-the-error ----
  {
    id: "q-spot-1",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'My husband says I'm losing my mind.'\nStudent: 'Don't worry, you're definitely not!'",
    options: [
      "The patient's self-report is the concern",
      "Reassuring before exploring the fear",
      "Noting the husband's words",
      "Listening without interrupting",
    ],
    correct: 1,
    rationale: "Premature reassurance closes exploration — the fear deserves to be named and examined, not dismissed.",
    source: "mhGAP-IG 2.0 (2016); motivational interviewing literature",
  },
  {
    id: "q-spot-2",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Student: 'How's your sleep?'\nPatient: 'Terrible.'\nStudent: 'So you sleep terribly. Is it your wife's cooking?'",
    options: [
      "Asking about sleep",
      "Reflecting the answer",
      "Guessing the cause (the wife's cooking)",
      "Pausing for the patient",
    ],
    correct: 2,
    rationale: "A leading, guessing question closes the real story — the open 'what keeps you awake?' invites description.",
    source: "Clinical interviewing literature (open questions)",
  },
  {
    id: "q-spot-3",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'The doctor said my son is hyperactive and needs testing.'\nStudent: 'Let's test him for ADHD right away.'",
    options: [
      "Listening to the mother's account",
      "Ordering a label after one report",
      "Noting the teacher's concern",
      "Asking about the child's behaviour",
    ],
    correct: 1,
    rationale: "One informant's report is not an assessment — ADHD needs multi-informant evaluation over time.",
    source: "DSM-5 ADHD criteria (multiple settings)",
  },
  // ---- Order-the-steps: MSE completion + OSCE completion hooks ----
  {
    id: "q-order-osce-1",
    type: "order_steps",
    prompt: "Order the breaking-bad-news sequence (OSCE station 3).",
    options: [
      "Warning shot → the news plainly → check understanding & emotion → next steps & support",
      "The news first, no preamble → leave",
      "Details first, news last",
      "Ask the family to leave before starting",
    ],
    correct: 0,
    rationale: "The warning shot, plain statement, emotional check, and next steps are the standard protocol.",
    source: "SPIKES protocol (Baile et al., 2000)",
  },
  {
    id: "q-order-osce-2",
    type: "order_steps",
    prompt: "Order the capacity-assessment components (OSCE station 4).",
    options: [
      "Understand → retain → weigh → communicate the decision",
      "Weigh first, understand last",
      "Ask the family what they think",
      "Assume capacity because he's coherent",
    ],
    correct: 0,
    rationale: "Capacity = understanding, retention, weighing and communication — the four-part test.",
    source: "Mental Capacity framework (UK MCA 2005; parallel Indian doctrine)",
  },
  {
    id: "q-decode-1",
    type: "best_response",
    prompt: "A patient says 'Doctor, I have ghabrahat.' What is the first question?",
    options: [
      "'When the ghabrahat comes, what exactly happens in your body?'",
      "'Do you have anxiety?'",
      "'It's probably stress — try to relax.'",
      "'Is someone at home troubling you?'",
    ],
    correct: 0,
    rationale: "Ghabrahat covers panic, thyroid and withdrawal — the physical description disambiguates before any label.",
    source: "Nichter (1981); Kirmayer & Young (1998)",
  },
  {
    id: "q-decode-2",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'I'm not feeling fresh these days.'\nStudent: 'That's how depression starts. Let me tell you about treatment.'",
    options: [
      "Hearing the phrase as a complaint",
      "Labelling depression before asking what 'fresh' means",
      "Offering treatment information",
      "Starting with the patient's words",
    ],
    correct: 1,
    rationale: "'Not feeling fresh' can mean constipation, sleep, anaemia or mood — the label closed the funnel.",
    source: "Nichter (1981); DSM-5 CFI",
  },
  {
    id: "q-decode-3",
    type: "standard_vs_common",
    prompt: "A young man reports kamzori and, hesitantly, distress about nocturnal emission. Which is standard of care?",
    options: [
      "Psychoeducation that semen loss is normal physiology, plus the psychological work (standard)",
      "Tests to prove semen is being lost (common but wrong)",
      "Dismissing it as 'all in your head'",
      "Prescribing a tonic to 'strengthen'",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "Dhat distress is treated by normal-physiology psychoeducation + the psychological work — not collusion, not dismissal.",
    source: "Sumathipala et al. (2004); DSM-5 cultural concepts",
  },
  {
    id: "q-decode-4",
    type: "order_steps",
    prompt: "Order the funnel for a vague complaint.",
    options: [
      "Open → specify → instantiate → quantify → contextualise → attribute",
      "Attribute first → then open",
      "Quantify before open",
      "Specify after diagnosing",
    ],
    correct: 0,
    rationale: "The funnel moves from opening to specifying to 'walk me through yesterday morning' to quantity, function and attribution.",
    source: "DSM-5 CFI; clinical interviewing literature",
  },
  {
    id: "q-decode-5",
    type: "would_you_report",
    prompt: "A patient's family insists the 'possession' is real and wants you to confirm it to the temple. Would you confirm?",
    options: [
      "No — I can describe what I observed and explore the meaning, but 'possession' is not my confirmation to give",
      "Yes — the family's belief is the culture",
      "Yes, if the patient agrees",
      "No, and refuse to discuss it at all",
    ],
    correct: 0,
    rationale: "The clinician neither confirms nor denies the cultural attribution — the work is exploring its function without dismissing it.",
    source: "Kirmayer & Young (1998); DSM-5 CFI",
  },
  {
    id: "q-decode-6",
    type: "best_response",
    prompt: "A patient says 'my mind doesn't work' (dimag kaam nahi karta). Next?",
    options: [
      "'What does a day look like — where does the mind fail you most?'",
      "'That's a sign of early dementia.'",
      "'Have you tried brain games?'",
      "'It's just stress, ignore it.'",
    ],
    correct: 0,
    rationale: "'Mind doesn't work' is the cognitive idiom of depression — the functional description decides, not the label.",
    source: "Indian cognitive-idiom literature; mhGAP",
  },
  {
    id: "q-decode-7",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'The doctor said my BP is high when I'm angry.'\nStudent: 'So you have hypertension. Let's manage your anger.'",
    options: [
      "Noting the BP reading",
      "Confirming hypertension from the idiom alone",
      "Offering anger management",
      "Asking about the episodes",
    ],
    correct: 1,
    rationale: "'BP high ho gaya' is the idiom for 'got very upset' — confirming the disease from the phrase is the trap.",
    source: "Borrowed-biomedical idioms literature",
  },
  {
    id: "q-decode-8",
    type: "standard_vs_common",
    prompt: "A student asks what to write for a patient's 'possession' in the MSE. Which is standard?",
    options: [
      "Describe the observed behaviour and the patient's own account, without 'possession' as a diagnosis (standard)",
      "Write 'possession' as the diagnosis (common but wrong)",
      "Refuse to write anything",
      "Write 'culturally normal, no assessment needed'",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "The MSE describes phenomena and the patient's account — the cultural label is formulation, not diagnosis.",
    source: "MSE standard practice; Kirmayer & Young (1998)",
  },
  {
    id: "q-decode-9",
    type: "would_you_report",
    prompt: "A client tells you their family consulted a baba who said the illness is 'graha dosh' (planetary affliction) and prescribed a ritual. Would you report the family?",
    options: [
      "No — the baba is a cultural resource, not a reportable offence; the work is exploring the client's view without colluding",
      "Yes — ritual advice is harmful",
      "Yes — any non-medical care is abuse",
      "Only if the ritual involved physical harm",
    ],
    correct: 0,
    rationale: "Traditional healers are a common first contact in Indian help-seeking — the clinical task is respectful exploration, not reporting.",
    source: "NMHS help-seeking data; mhGAP cultural considerations",
  },
  {
    id: "q-decode-10",
    type: "best_response",
    prompt: "A patient says 'kisi ne kuch kar diya' (someone did something to me). Next?",
    options: [
      "'What do you think was done, and what has it felt like since?'",
      "'That's not possible — let's be scientific.'",
      "'Who did it? I'll report them.'",
      "'It's a superstition you should drop.'",
    ],
    correct: 0,
    rationale: "The attribution is the client's frame — exploring its function and the distress it names is the work, not correcting it.",
    source: "Attributional idioms; DSM-5 CFI",
  },
  {
    id: "q-decode-11",
    type: "order_steps",
    prompt: "Order the CFI domains for eliciting an explanatory model.",
    options: [
      "Perceived cause → meaning → course → expected treatment",
      "Treatment first → cause last",
      "Meaning before asking anything",
      "Course only",
    ],
    correct: 0,
    rationale: "The CFI moves from what the patient thinks caused it, to what it means, to the expected course and treatment.",
    source: "DSM-5 Cultural Formulation Interview (2013)",
  },
  {
    id: "q-decode-12",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'I have tension since my brother's business failed.'\nStudent: 'Tension is normal — everyone has it.'",
    options: [
      "Hearing the word tension",
      "Reassuring before exploring what the tension is",
      "Noting the trigger",
      "Asking about the brother",
    ],
    correct: 1,
    rationale: "'Tension' is the most generic distress word — it needs specification (about what, since when, what it stops), not dismissal.",
    source: "Pan-Indian 'tension' literature",
  },
  {
    id: "q-decode-13",
    type: "standard_vs_common",
    prompt: "A young woman reports 'white discharge' weakness. Which is standard?",
    options: [
      "Explore her concern and any physical red flags, normalise physiology, and screen mood (standard)",
      "Confirm 'white discharge syndrome' as a diagnosis (common but wrong)",
      "Tell her it's imaginary",
      "Prescribe a 'discharge tonic'",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "The white-discharge idiom is a common South Asian distress presentation — the work is understanding, not confirming or dismissing.",
    source: "South Asian bodily-idiom literature",
  },
  {
    id: "q-decode-14",
    type: "best_response",
    prompt: "A patient says 'I'm stressed' but also mentions 3 hours of sleep and new grand plans. Next?",
    options: [
      "'Three hours of sleep with grand plans — tell me about the energy since that started.'",
      "'Stress is manageable — let's do breathing.'",
      "'Are you sure it's not just excitement?'",
      "'Let's wait and see.'",
    ],
    correct: 0,
    rationale: "The 'stressed' frame hides hypomania — the sleep and grandiosity need the direct question, not the stress label.",
    source: "Bipolar-spectrum under-diagnosis literature",
  },
  {
    id: "q-decode-15",
    type: "would_you_report",
    prompt: "A client's 'nazar lag gayi' belief follows their business failure. There's no psychosis, no distress beyond the attribution. Would you report?",
    options: [
      "No — the attribution is cultural and non-pathological; the work is the loss, not the belief",
      "Yes — any delusion-like belief must be reported",
      "Yes — the family should be warned",
      "Only if they act on it",
    ],
    correct: 0,
    rationale: "An attributional belief without fixity, impairment or distress is a cultural frame, not a delusion — the loss is the clinical content.",
    source: "Attributional idioms; Kirmayer & Young (1998)",
  },
];