/**
 * Quiz bank (v5 §4.1 / brief §11.3 content volume) — 20 sourced items,
 * order-the-steps + would-you-report focus, wired into MSE and OSCE
 * completion. Every item carries a one-line rationale citing its source.
 * No item ships without one.
 */

import type { QuizItem } from "./quiz";
import { PHASE1_QUIZ_ITEMS } from "./phase1-bank";

export const QUIZ_BANK: QuizItem[] = [
  // ---- Order-the-steps: risk assessment / intake sequence ----
  {
    id: "q-order-risk-1",
    type: "order_steps",
    prompt: "Order the risk-assessment sequence in a first session where a patient mentions hopelessness.",
    options: [
      "Screen in clear language → explore plan/means/intent → check protective factors → make a safety plan",
      "Explore the mood first → end the session → note risk 'for next time'",
      "Ask the family → then the patient → then decide",
      "Reassure early → move to another topic → document 'no risk'",
    ],
    correct: 0,
    rationale: "Risk asked directly, then plan/means/intent, then protective factors, then a concrete safety plan — in that order.",
    source: "WHO mhGAP-IG 2.0 (2016), assessment & management of self-harm/suicide",
  },
  {
    id: "q-order-risk-2",
    type: "order_steps",
    prompt: "A patient says 'sometimes I think it would be easier to not be here.' Order the correct next steps.",
    options: [
      "Ask about plan and means → assess intent → involve support if imminent → document",
      "Tell them 'everyone feels that way' → change topic",
      "End the session early to avoid escalation",
      "Call the family before asking anything more",
    ],
    correct: 0,
    rationale: "Passive ideation still demands the plan/means/intent probe; support and documentation follow.",
    source: "WHO mhGAP-IG 2.0 (2016)",
  },
  {
    id: "q-order-intake-1",
    type: "order_steps",
    prompt: "Order the first-session intake sequence.",
    options: [
      "Presenting complaint in own words → history (sleep/appetite/function) → risk screen → expectations & consent",
      "Diagnosis first → then questions",
      "Family's account only → then the patient",
      "Forms first → then talk",
    ],
    correct: 0,
    rationale: "The complaint in the patient's own words opens; the physical/function triad and risk follow before any framing.",
    source: "DSM-5 Cultural Formulation Interview (2013) + mhGAP",
  },
  {
    id: "q-order-crisis-1",
    type: "order_steps",
    prompt: "A client has a specific plan and the means available tonight. Order your actions.",
    options: [
      "Stay with them → activate support/referral → involve emergency services if needed → document",
      "End the session → call tomorrow",
      "Give a leaflet → schedule next week",
      "Promise confidentiality → let them leave alone",
    ],
    correct: 0,
    rationale: "Imminent risk: you do not leave them alone; support and emergency involvement happen before documentation.",
    source: "WHO mhGAP-IG 2.0 (2016) — imminent self-harm",
  },
  {
    id: "q-order-mse-1",
    type: "order_steps",
    prompt: "Order the MSE write-up domains in the standard sequence.",
    options: [
      "Appearance → behaviour → speech → mood → affect → thought form/content → perception → cognition → insight → judgment",
      "Mood first, appearance last",
      "Perception before speech",
      "Insight before mood",
    ],
    correct: 0,
    rationale: "The standard MSE order moves from the observable surface inward to thought, perception and judgment.",
    source: "Standard MSE structure (British Psychological Society guidance)",
  },
  // ---- Would-you-report: MHA 2017 / POCSO applied ----
  {
    id: "q-report-pocso-1",
    type: "would_you_report",
    prompt: "A 13-year-old tells you a tutor has been touching her. She begs you not to tell. Would you report?",
    options: [
      "Yes — POCSO mandates reporting to police/Childline, no discretion",
      "Only with parental consent",
      "Only if she repeats it next session",
      "No — confidentiality protects the disclosure",
    ],
    correct: 0,
    rationale: "POCSO Section 19 makes reporting mandatory; failure is itself an offence.",
    source: "POCSO 2012, Section 19",
  },
  {
    id: "q-report-pocso-2",
    type: "would_you_report",
    prompt: "An 8-year-old draws a picture of 'the bad thing' during play therapy. No words yet. Would you report?",
    options: [
      "Yes — the drawing is a disclosure signal; mandated reporting applies",
      "Wait until they can describe it in words",
      "Only if a family member confirms",
      "No — art is ambiguous",
    ],
    correct: 0,
    rationale: "Non-verbal disclosure is still disclosure; POCSO's duty is triggered by information, however conveyed.",
    source: "POCSO 2012, Section 19 (child-friendly procedures)",
  },
  {
    id: "q-report-pocso-3",
    type: "would_you_report",
    prompt: "A 15-year-old says a classmate showed them pornographic images. Would you report?",
    options: [
      "Assess whether the classmate is a minor and the context — child-on-child exposure may trigger POCSO duties",
      "Never report child-to-child matters",
      "Report the 15-year-old as an offender",
      "It's the parents' problem alone",
    ],
    correct: 0,
    rationale: "POCSO covers child-on-child offences; assessment of context precedes any action, but the duty is real.",
    source: "POCSO 2012, Section 2(d) — 'child' includes any person under 18",
  },
  {
    id: "q-report-mha-1",
    type: "would_you_report",
    prompt: "A client with an advance directive refusing ECT is now in a severe relapse, unable to consent. The family demands ECT. What do you do?",
    options: [
      "Honour the directive; only the MHA's narrow Section 5(4) pathway can override it",
      "Follow the family — they know best",
      "Do ECT because it worked before",
      "Ignore the directive as 'just paperwork'",
    ],
    correct: 0,
    rationale: "MHA 2017 Section 5 makes advance directives binding; exceptions are narrow and procedurally defined.",
    source: "Mental Healthcare Act 2017, Section 5",
  },
  {
    id: "q-report-mha-2",
    type: "would_you_report",
    prompt: "You witness a patient at a facility being tied to the bed 'because he shouted'. Would you report?",
    options: [
      "Yes — restraint beyond the MHA's narrow emergency conditions is a violation with a reporting duty",
      "No — hospitals know their business",
      "Only if the patient asks you to",
      "Mention it casually to the nurse, then drop it",
    ],
    correct: 0,
    rationale: "MHA 2017 restricts restraint sharply and requires recording/reporting; witnessing a violation carries a duty.",
    source: "Mental Healthcare Act 2017, Section 98 (restraint)",
  },
  {
    id: "q-report-mha-3",
    type: "would_you_report",
    prompt: "A student client in therapy reveals they were turned away from a government clinic for being 'too complex'. Would you report?",
    options: [
      "Yes — MHA 2017 gives a right to mental healthcare and complaint mechanisms for denial",
      "No — it's not your business",
      "Only if they pay you to",
      "Advise them to try a private clinic instead",
    ],
    correct: 0,
    rationale: "MHA 2017 establishes the right to accessible mental healthcare; denial can be raised through its mechanisms.",
    source: "Mental Healthcare Act 2017, Section 18-19 (right to services)",
  },
  // ---- Standard-of-care vs common-practice ----
  {
    id: "q-soc-1",
    type: "standard_vs_common",
    prompt: "A first-episode patient's family wants 'a diagnosis in writing' after one session. Which is standard of care?",
    options: [
      "Explain assessment is ongoing; premature labelling is harmful (standard)",
      "Write the diagnosis to keep the family happy (common but wrong)",
      "Refuse to ever document anything",
      "Diagnose what the family suspects",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "Diagnosis follows assessment; a label without it is an error that shapes the patient's identity.",
    source: "RCI code of ethics — practice within competence",
  },
  {
    id: "q-soc-2",
    type: "standard_vs_common",
    prompt: "A client asks you to recommend starting or stopping their antidepressant. Which is standard?",
    options: [
      "Describe your observations; medication decisions sit with the prescriber (standard)",
      "Advise the dose change yourself (common but outside scope)",
      "Tell them to stop immediately",
      "Double the dose yourself",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "Dose decisions are prescriber decisions; counselling scope covers observation and support, not titration.",
    source: "RCI scope of practice",
  },
  {
    id: "q-soc-3",
    type: "standard_vs_common",
    prompt: "A worried mother asks you to 'test my son for ADHD' in the first session. Which is standard?",
    options: [
      "Multi-informant assessment over time, with the teacher's report as one input (standard)",
      "A one-session label to end the worry (common but wrong)",
      "Refuse to see the child at all",
      "Diagnose from the mother's description alone",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "ADHD assessment requires multiple informants and settings; a first-session label is malpractice.",
    source: "ICD-11 / DSM-5 diagnostic requirements",
  },
  // ---- Best-response ----
  {
    id: "q-br-1",
    type: "best_response",
    prompt: "A patient says 'I'm not feeling fresh.' What is the highest-yield next question?",
    options: [
      "'Walk me through yesterday morning — from waking up to leaving the house.'",
      "'Are you feeling sad?'",
      "'Have you tried yoga?'",
      "'That usually means depression.'",
    ],
    correct: 0,
    rationale: "Instantiate, don't guess — 'not feeling fresh' carries constipation, sleep, anaemia and mood; the description disambiguates.",
    source: "Nichter, Idioms of Distress (1981); DSM-5 CFI",
  },
  {
    id: "q-br-2",
    type: "best_response",
    prompt: "A patient says 'I think about dying a lot.' What do you say next?",
    options: [
      "'Thank you for telling me. When you say dying, what have you been thinking exactly?'",
      "'Don't worry, that's normal.'",
      "'Let's talk about something happier.'",
      "'You'll be fine, trust me.'",
    ],
    correct: 0,
    rationale: "Take the disclosure seriously, thank them, and probe the specifics — reassurance before exploration is the #1 novice error.",
    source: "WHO mhGAP-IG 2.0 (2016)",
  },
  // ---- Spot-the-error ----
  {
    id: "q-spot-1",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'My husband says I'm losing my mind.'\nStudent: 'Don't worry, you're definitely not!'",
    options: [
      "The patient's self-report is the concern",
      "Reassuring before exploring the fear",
      "Noting the husband's words",
      "Listening without interrupting",
    ],
    correct: 1,
    rationale: "Premature reassurance closes exploration — the fear deserves to be named and examined, not dismissed.",
    source: "mhGAP-IG 2.0 (2016); motivational interviewing literature",
  },
  {
    id: "q-spot-2",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Student: 'How's your sleep?'\nPatient: 'Terrible.'\nStudent: 'So you sleep terribly. Is it your wife's cooking?'",
    options: [
      "Asking about sleep",
      "Reflecting the answer",
      "Guessing the cause (the wife's cooking)",
      "Pausing for the patient",
    ],
    correct: 2,
    rationale: "A leading, guessing question closes the real story — the open 'what keeps you awake?' invites description.",
    source: "Clinical interviewing literature (open questions)",
  },
  {
    id: "q-spot-3",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'The doctor said my son is hyperactive and needs testing.'\nStudent: 'Let's test him for ADHD right away.'",
    options: [
      "Listening to the mother's account",
      "Ordering a label after one report",
      "Noting the teacher's concern",
      "Asking about the child's behaviour",
    ],
    correct: 1,
    rationale: "One informant's report is not an assessment — ADHD needs multi-informant evaluation over time.",
    source: "DSM-5 ADHD criteria (multiple settings)",
  },
  // ---- Order-the-steps: MSE completion + OSCE completion hooks ----
  {
    id: "q-order-osce-1",
    type: "order_steps",
    prompt: "Order the breaking-bad-news sequence (OSCE station 3).",
    options: [
      "Warning shot → the news plainly → check understanding & emotion → next steps & support",
      "The news first, no preamble → leave",
      "Details first, news last",
      "Ask the family to leave before starting",
    ],
    correct: 0,
    rationale: "The warning shot, plain statement, emotional check, and next steps are the standard protocol.",
    source: "SPIKES protocol (Baile et al., 2000)",
  },
  {
    id: "q-order-osce-2",
    type: "order_steps",
    prompt: "Order the capacity-assessment components (OSCE station 4).",
    options: [
      "Understand → retain → weigh → communicate the decision",
      "Weigh first, understand last",
      "Ask the family what they think",
      "Assume capacity because he's coherent",
    ],
    correct: 0,
    rationale: "Capacity = understanding, retention, weighing and communication — the four-part test.",
    source: "Mental Capacity framework (UK MCA 2005; parallel Indian doctrine)",
  },
  {
    id: "q-decode-1",
    type: "best_response",
    prompt: "A patient says 'Doctor, I have ghabrahat.' What is the first question?",
    options: [
      "'When the ghabrahat comes, what exactly happens in your body?'",
      "'Do you have anxiety?'",
      "'It's probably stress — try to relax.'",
      "'Is someone at home troubling you?'",
    ],
    correct: 0,
    rationale: "Ghabrahat covers panic, thyroid and withdrawal — the physical description disambiguates before any label.",
    source: "Nichter (1981); Kirmayer & Young (1998)",
  },
  {
    id: "q-decode-2",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'I'm not feeling fresh these days.'\nStudent: 'That's how depression starts. Let me tell you about treatment.'",
    options: [
      "Hearing the phrase as a complaint",
      "Labelling depression before asking what 'fresh' means",
      "Offering treatment information",
      "Starting with the patient's words",
    ],
    correct: 1,
    rationale: "'Not feeling fresh' can mean constipation, sleep, anaemia or mood — the label closed the funnel.",
    source: "Nichter (1981); DSM-5 CFI",
  },
  {
    id: "q-decode-3",
    type: "standard_vs_common",
    prompt: "A young man reports kamzori and, hesitantly, distress about nocturnal emission. Which is standard of care?",
    options: [
      "Psychoeducation that semen loss is normal physiology, plus the psychological work (standard)",
      "Tests to prove semen is being lost (common but wrong)",
      "Dismissing it as 'all in your head'",
      "Prescribing a tonic to 'strengthen'",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "Dhat distress is treated by normal-physiology psychoeducation + the psychological work — not collusion, not dismissal.",
    source: "Sumathipala et al. (2004); DSM-5 cultural concepts",
  },
  {
    id: "q-decode-4",
    type: "order_steps",
    prompt: "Order the funnel for a vague complaint.",
    options: [
      "Open → specify → instantiate → quantify → contextualise → attribute",
      "Attribute first → then open",
      "Quantify before open",
      "Specify after diagnosing",
    ],
    correct: 0,
    rationale: "The funnel moves from opening to specifying to 'walk me through yesterday morning' to quantity, function and attribution.",
    source: "DSM-5 CFI; clinical interviewing literature",
  },
  {
    id: "q-decode-5",
    type: "would_you_report",
    prompt: "A patient's family insists the 'possession' is real and wants you to confirm it to the temple. Would you confirm?",
    options: [
      "No — I can describe what I observed and explore the meaning, but 'possession' is not my confirmation to give",
      "Yes — the family's belief is the culture",
      "Yes, if the patient agrees",
      "No, and refuse to discuss it at all",
    ],
    correct: 0,
    rationale: "The clinician neither confirms nor denies the cultural attribution — the work is exploring its function without dismissing it.",
    source: "Kirmayer & Young (1998); DSM-5 CFI",
  },
  {
    id: "q-decode-6",
    type: "best_response",
    prompt: "A patient says 'my mind doesn't work' (dimag kaam nahi karta). Next?",
    options: [
      "'What does a day look like — where does the mind fail you most?'",
      "'That's a sign of early dementia.'",
      "'Have you tried brain games?'",
      "'It's just stress, ignore it.'",
    ],
    correct: 0,
    rationale: "'Mind doesn't work' is the cognitive idiom of depression — the functional description decides, not the label.",
    source: "Indian cognitive-idiom literature; mhGAP",
  },
  {
    id: "q-decode-7",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'The doctor said my BP is high when I'm angry.'\nStudent: 'So you have hypertension. Let's manage your anger.'",
    options: [
      "Noting the BP reading",
      "Confirming hypertension from the idiom alone",
      "Offering anger management",
      "Asking about the episodes",
    ],
    correct: 1,
    rationale: "'BP high ho gaya' is the idiom for 'got very upset' — confirming the disease from the phrase is the trap.",
    source: "Borrowed-biomedical idioms literature",
  },
  {
    id: "q-decode-8",
    type: "standard_vs_common",
    prompt: "A student asks what to write for a patient's 'possession' in the MSE. Which is standard?",
    options: [
      "Describe the observed behaviour and the patient's own account, without 'possession' as a diagnosis (standard)",
      "Write 'possession' as the diagnosis (common but wrong)",
      "Refuse to write anything",
      "Write 'culturally normal, no assessment needed'",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "The MSE describes phenomena and the patient's account — the cultural label is formulation, not diagnosis.",
    source: "MSE standard practice; Kirmayer & Young (1998)",
  },
  {
    id: "q-decode-9",
    type: "would_you_report",
    prompt: "A client tells you their family consulted a baba who said the illness is 'graha dosh' (planetary affliction) and prescribed a ritual. Would you report the family?",
    options: [
      "No — the baba is a cultural resource, not a reportable offence; the work is exploring the client's view without colluding",
      "Yes — ritual advice is harmful",
      "Yes — any non-medical care is abuse",
      "Only if the ritual involved physical harm",
    ],
    correct: 0,
    rationale: "Traditional healers are a common first contact in Indian help-seeking — the clinical task is respectful exploration, not reporting.",
    source: "NMHS help-seeking data; mhGAP cultural considerations",
  },
  {
    id: "q-decode-10",
    type: "best_response",
    prompt: "A patient says 'kisi ne kuch kar diya' (someone did something to me). Next?",
    options: [
      "'What do you think was done, and what has it felt like since?'",
      "'That's not possible — let's be scientific.'",
      "'Who did it? I'll report them.'",
      "'It's a superstition you should drop.'",
    ],
    correct: 0,
    rationale: "The attribution is the client's frame — exploring its function and the distress it names is the work, not correcting it.",
    source: "Attributional idioms; DSM-5 CFI",
  },
  {
    id: "q-decode-11",
    type: "order_steps",
    prompt: "Order the CFI domains for eliciting an explanatory model.",
    options: [
      "Perceived cause → meaning → course → expected treatment",
      "Treatment first → cause last",
      "Meaning before asking anything",
      "Course only",
    ],
    correct: 0,
    rationale: "The CFI moves from what the patient thinks caused it, to what it means, to the expected course and treatment.",
    source: "DSM-5 Cultural Formulation Interview (2013)",
  },
  {
    id: "q-decode-12",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Patient: 'I have tension since my brother's business failed.'\nStudent: 'Tension is normal — everyone has it.'",
    options: [
      "Hearing the word tension",
      "Reassuring before exploring what the tension is",
      "Noting the trigger",
      "Asking about the brother",
    ],
    correct: 1,
    rationale: "'Tension' is the most generic distress word — it needs specification (about what, since when, what it stops), not dismissal.",
    source: "Pan-Indian 'tension' literature",
  },
  {
    id: "q-decode-13",
    type: "standard_vs_common",
    prompt: "A young woman reports 'white discharge' weakness. Which is standard?",
    options: [
      "Explore her concern and any physical red flags, normalise physiology, and screen mood (standard)",
      "Confirm 'white discharge syndrome' as a diagnosis (common but wrong)",
      "Tell her it's imaginary",
      "Prescribe a 'discharge tonic'",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "The white-discharge idiom is a common South Asian distress presentation — the work is understanding, not confirming or dismissing.",
    source: "South Asian bodily-idiom literature",
  },
  {
    id: "q-decode-14",
    type: "best_response",
    prompt: "A patient says 'I'm stressed' but also mentions 3 hours of sleep and new grand plans. Next?",
    options: [
      "'Three hours of sleep with grand plans — tell me about the energy since that started.'",
      "'Stress is manageable — let's do breathing.'",
      "'Are you sure it's not just excitement?'",
      "'Let's wait and see.'",
    ],
    correct: 0,
    rationale: "The 'stressed' frame hides hypomania — the sleep and grandiosity need the direct question, not the stress label.",
    source: "Bipolar-spectrum under-diagnosis literature",
  },
  {
    id: "q-decode-15",
    type: "would_you_report",
    prompt: "A client's 'nazar lag gayi' belief follows their business failure. There's no psychosis, no distress beyond the attribution. Would you report?",
    options: [
      "No — the attribution is cultural and non-pathological; the work is the loss, not the belief",
      "Yes — any delusion-like belief must be reported",
      "Yes — the family should be warned",
      "Only if they act on it",
    ],
    correct: 0,
    rationale: "An attributional belief without fixity, impairment or distress is a cultural frame, not a delusion — the loss is the clinical content.",
    source: "Attributional idioms; Kirmayer & Young (1998)",
  },
  {
    id: "q-mse-1",
    type: "spot_the_error",
    prompt: "Which line is the error in this MSE excerpt?",
    excerpt: "Appearance: well-groomed. Behaviour: cooperative. Speech: normal rate. Mood: patient reports 'low every day'. Affect: flat. Thought form: linear. Thought content: no delusions. Perception: 'hears a voice when alone' — hallucination, schizophrenia confirmed.",
    options: [
      "Recording affect as flat",
      "Diagnosing schizophrenia from one MSE line",
      "Asking the patient's mood in their words",
      "Noting the hallucination",
    ],
    correct: 1,
    rationale: "The MSE describes; diagnosis follows assessment. Naming schizophrenia from a perception line is the conclusion-the-MSE-is-meant-to-prevent.",
    source: "MSE standard practice",
  },
  {
    id: "q-mse-2",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Student writes: 'The patient is very anxious and clearly has an anxiety disorder. He was restless during the interview.'",
    options: [
      "Describing restlessness",
      "Labelling the disorder before the assessment",
      "Noting anxiety",
      "Observing during the interview",
    ],
    correct: 1,
    rationale: "Describe before you label — 'anxious' as an observation of behaviour vs a diagnosis are different registers.",
    source: "MSE discipline (describe-don't-diagnose)",
  },
  {
    id: "q-mse-3",
    type: "order_steps",
    prompt: "Order the correct way to record affect.",
    options: [
      "Observed range → congruence with mood → quality (flat/blunted/labile)",
      "Diagnosis first → then affect",
      "The patient's self-report alone",
      "Skip affect if the mood is clear",
    ],
    correct: 0,
    rationale: "Affect is observed (range, congruence, quality) — never inferred from mood or omitted because mood is reported.",
    source: "MSE standard structure",
  },
  {
    id: "q-mse-4",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Perception: 'patient reports hearing voices commenting on him — auditory hallucination. Refer for antipsychotics immediately.'",
    options: [
      "Recording the voice report",
      "Recommending antipsychotics from the MSE alone",
      "Naming the phenomenon an auditory hallucination",
      "Quoting the patient",
    ],
    correct: 1,
    rationale: "Even with clear perceptual findings, medication decisions need the full assessment — the MSE is description, not prescription.",
    source: "RCI scope; MSE discipline",
  },
  {
    id: "q-mse-5",
    type: "order_steps",
    prompt: "Order the judgement assessment.",
    options: [
      "Future-oriented question → observed decision-making → documented examples",
      "Assume judgment from speech",
      "Skip if insight seems fine",
      "Diagnose from one answer",
    ],
    correct: 0,
    rationale: "Judgment is assessed by concrete future scenarios and the quality of actual decisions — never assumed from fluency.",
    source: "MSE standard structure",
  },
  {
    id: "q-mse-6",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Insight: 'Patient has poor insight because he disagrees that medication is essential.'",
    options: [
      "Recording disagreement",
      "Measuring insight by agreement",
      "Noting the medication view",
      "Documenting insight as a domain",
    ],
    correct: 1,
    rationale: "Insight is graded recognition of illness (full/partial/poor/absent), NOT agreement with treatment — conflating the two is a classic error.",
    source: "Insight literature (graded, domain-specific)",
  },
  {
    id: "q-mse-7",
    type: "order_steps",
    prompt: "Order the perception assessment.",
    options: [
      "Open question → hallucinations (modality, frequency) → illusions → insight into the experience",
      "Ask 'do you hallucinate?' first",
      "Skip if the patient denies voices",
      "Diagnose before asking",
    ],
    correct: 0,
    rationale: "The open question first, then modalities and frequency, then the patient's own explanation — never the label-led question.",
    source: "MSE standard structure",
  },
  {
    id: "q-mse-8",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Thought content: 'preoccupied with guilt. Delusional guilt suggests depression with psychotic features.'",
    options: [
      "Recording the preoccupation",
      "Naming 'delusional guilt' and the disorder from one observation",
      "Noting the content",
      "Writing the content plain",
    ],
    correct: 1,
    rationale: "Guilt as content is a description; 'delusional' and 'suggests X disorder' is the conclusion the description must precede.",
    source: "MSE discipline",
  },
  {
    id: "q-mse-9",
    type: "order_steps",
    prompt: "Order the speech assessment.",
    options: [
      "Rate → volume → tone → quantity → fluency",
      "Volume before rate, fluency last",
      "Content before delivery",
      "Jump straight to meaning",
    ],
    correct: 0,
    rationale: "Speech describes delivery first (rate/volume/tone/quantity/fluency) — content belongs to thought, not speech.",
    source: "MSE standard structure",
  },
  {
    id: "q-mse-10",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Cognition: 'oriented to person, place and time. Memory intact because the patient answered the date correctly.'",
    options: [
      "Checking orientation",
      "Inferring memory from one date answer",
      "Recording orientation",
      "Testing person-place-time",
    ],
    correct: 1,
    rationale: "Memory needs its own assessment (recent, remote, registration/recall) — orientation alone never establishes it.",
    source: "MSE standard structure",
  },
  {
    id: "q-mse-11",
    type: "order_steps",
    prompt: "Order documenting thought form.",
    options: [
      "Observed connections → exemplar quotes → named pattern (flight/tangential/circumstantial)",
      "Named pattern first",
      "Skip if speech is fluent",
      "Quotes without interpretation",
    ],
    correct: 0,
    rationale: "Form is named from observed connections, supported by quoted examples — the quote justifies the name.",
    source: "MSE standard structure",
  },
  {
    id: "q-mse-12",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Mood: 'patient is depressed.' Affect: 'patient displays inappropriate affect.'",
    options: [
      "Recording the mood report",
      "Labelling mood from observation (depression is the patient's report or the diagnosis, not the observation)",
      "Noting affect as inappropriate",
      "Documenting both domains",
    ],
    correct: 1,
    rationale: "Mood is reported; affect is observed. Writing 'patient is depressed' blends the two registers the MSE exists to separate.",
    source: "MSE discipline (mood vs affect)",
  },
  {
    id: "q-mse-13",
    type: "order_steps",
    prompt: "Order the correct MSE write-up flow.",
    options: [
      "Observe each domain fresh → write descriptions first → add defensible interpretations at the end",
      "Write the diagnosis then fill the domains",
      "Skip domains that seem normal",
      "Write only abnormal findings",
    ],
    correct: 0,
    rationale: "The MSE describes all domains in order; interpretations are flagged separately as such — write-then-interpret, never the reverse.",
    source: "MSE standard practice",
  },
  {
    id: "q-mse-14",
    type: "spot_the_error",
    prompt: "Which line is the error?",
    excerpt: "Behaviour: 'patient is manipulative and attention-seeking — refused to answer questions.'",
    options: [
      "Recording the refusal",
      "Labelling behaviour as manipulative (a judgement, not an observation)",
      "Noting the refusal to answer",
      "Documenting behaviour",
    ],
    correct: 1,
    rationale: "'Manipulative' is a judgment, not an observation — the behaviour ('refused to answer') is what belongs in the MSE.",
    source: "MSE discipline; anti-bias guidance",
  },
  {
    id: "q-mse-15",
    type: "order_steps",
    prompt: "Order documenting insight.",
    options: [
      "Per domain (illness? treatment? causes?) → graded full/partial/poor/absent → note discrepancy across domains",
      "One global judgement",
      "Agreement-with-clinician as the measure",
      "Skip when the patient denies illness",
    ],
    correct: 0,
    rationale: "Insight is graded and domain-specific — a patient can accept mood illness while denying psychosis; both get documented.",
    source: "Insight literature (graded, domain-specific)",
  },
  {
    id: "q-mha-amend-1",
    type: "would_you_report",
    prompt: "A patient in a private clinic is charged double the standard rate for 'mental health care' and is told it's 'specialised'. Would you report?",
    options: [
      "Yes — exploitative charging against vulnerable patients is a breach the MHA's complaint mechanisms address",
      "No — private clinics can charge what they like",
      "Only if the patient asks you to",
      "No — it's between the clinic and the patient",
    ],
    correct: 0,
    rationale: "The MHA 2017 framework and professional codes prohibit exploiting mental illness for profit; complaint pathways exist.",
    source: "MHA 2017; RCI code of ethics",
  },
  {
    id: "q-mha-amend-2",
    type: "would_you_report",
    prompt: "A facility continues secluding a patient overnight 'because she's noisy' — no doctor's order, no review. Would you report?",
    options: [
      "Yes — seclusion beyond the narrow conditions with no order or review is a violation with a reporting duty",
      "No — night staff know best",
      "Only if the patient is harmed",
      "Mention it to the nurse, then drop it",
    ],
    correct: 0,
    rationale: "MHA 2017 restricts seclusion/restraint to narrow emergency conditions with mandatory recording and reporting.",
    source: "MHA 2017, Section 98",
  },
  {
    id: "q-mha-amend-3",
    type: "would_you_report",
    prompt: "A client's family asks you to certify them 'fit for marriage' without them knowing, to settle a family dispute. Would you comply?",
    options: [
      "No — certification without the person's knowledge is both a consent violation and a fraud risk",
      "Yes — the family needs it",
      "Only if the client is unmarried",
      "Yes, if the family is respected in the community",
    ],
    correct: 0,
    rationale: "Any certification requires the person's informed participation — family-prompted secret certification is a consent and integrity breach.",
    source: "MHA 2017 consent provisions; RCI ethics",
  },
  {
    id: "q-pocso-proc-1",
    type: "standard_vs_common",
    prompt: "A 10-year-old discloses abuse in your school session. Which is standard for the reporting process?",
    options: [
      "Report to the mandated channel and involve a child-friendly procedure that protects her from repeat statements (standard)",
      "Interrogate her in detail yourself to 'get the full story' first (common but harmful)",
      "Ask the family to mediate first",
      "Wait for a written statement from her",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "Child-friendly procedures minimise repeated interviews; the mandated channel leads, not the counsellor's interrogation.",
    source: "POCSO 2012, child-friendly procedures; Section 19",
  },
  {
    id: "q-pocso-proc-2",
    type: "standard_vs_common",
    prompt: "A 13-year-old says a relative 'did something wrong' but asks you to 'tell my parents first, gently'. Which is standard?",
    options: [
      "Inform the mandated authority per the Act, while supporting the disclosure to parents within that process (standard)",
      "Tell the parents first so they can 'handle it in the family' (common but dangerous)",
      "Keep it secret until she is ready",
      "Wait for a second disclosure",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "The abuser is a relative — the mandated channel leads; family-first risks tipping off the abuser and pressuring the child.",
    source: "POCSO 2012, Section 19; child-protection best practice",
  },
  {
    id: "q-pocso-proc-3",
    type: "standard_vs_common",
    prompt: "A school counsellor learns of abuse and the principal says 'report it quietly, don't make a fuss'. Which is standard?",
    options: [
      "Report through the mandated channel regardless of the principal's preference (standard)",
      "Let the principal decide how 'quietly' to handle it (common but wrong)",
      "Only report if the family agrees",
      "Document it and do nothing",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "The reporting duty belongs to the person in contact with the child — institutional preference cannot override POCSO.",
    source: "POCSO 2012, Section 19",
  },
  {
    id: "q-pocso-proc-4",
    type: "would_you_report",
    prompt: "A 16-year-old in a consensual relationship with a 17-year-old classmate tells you 'everyone's doing it'. Would you report?",
    options: [
      "Assess the context — peer-consensual minor relationships need careful assessment; POCSO's intent is protection from exploitation, not punishment of peers",
      "Report both as offenders immediately",
      "Never discuss it",
      "Tell the parents to handle it",
    ],
    correct: 0,
    rationale: "POCSO covers child-on-child conduct, but the protective intent and context assessment come first — the response is safeguarding, not criminalisation of peers.",
    source: "POCSO 2012; child-protection guidance",
  },
  {
    id: "q-pocso-proc-5",
    type: "standard_vs_common",
    prompt: "A 12-year-old's disclosure is doubted by staff because 'children make things up'. Which is standard?",
    options: [
      "Treat the disclosure seriously, record it, and follow the mandated pathway — disbelief is not a screening tool (standard)",
      "Ignore it until corroboration exists (common but wrong)",
      "Ask the child to prove it",
      "Blame the child for the delay",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "Children rarely fabricate abuse; the mandated duty is triggered by the disclosure itself, not by proof.",
    source: "POCSO 2012; child-disclosure research",
  },
  {
    id: "q-mha-amend-4",
    type: "would_you_report",
    prompt: "A patient with a nominated representative is treated without any consultation with them, repeatedly, 'because they're inconvenient'. Would you report?",
    options: [
      "Yes — the nominated representative's role is statutory under MHA 2017; ignoring it is a procedural breach",
      "No — representatives are optional",
      "Only if the patient objects",
      "It's the hospital's internal matter",
    ],
    correct: 0,
    rationale: "MHA 2017 gives the nominated representative a defined role in supported decision-making; bypassing it breaches the Act.",
    source: "MHA 2017, Sections 14-16",
  },
  {
    id: "q-mha-amend-5",
    type: "would_you_report",
    prompt: "A client's employer pressures you to share the client's therapy details 'for the annual review'. The client has not consented. Would you share?",
    options: [
      "No — employer pressure without consent never unlocks clinical information",
      "Yes — the employer pays",
      "Share a summary without details",
      "Share if the employer signs a form",
    ],
    correct: 0,
    rationale: "Payment creates no disclosure right — the MHA's privacy provisions and the ethics codes are absolute on this.",
    source: "MHA 2017, Sections 22-24; RCI code",
  },
  {
    id: "q-mha-amend-6",
    type: "standard_vs_common",
    prompt: "A patient is discharged from an inpatient unit with no follow-up appointment and no medication plan explained. Which is standard?",
    options: [
      "Discharge planning includes a written follow-up + medication/support plan understood by the patient (standard)",
      "Discharge with a 'come back if needed' (common but a known relapse risk)",
      "Family handles it all",
      "No plan until the next episode",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "Transition without a plan is a foreseeable harm — continuity of care is part of the standard.",
    source: "MHA 2017 continuity provisions; mhGAP",
  },
  {
    id: "q-pocso-proc-6",
    type: "standard_vs_common",
    prompt: "A 15-year-old tells you about abuse but begs you not to 'break the family'. Which is standard?",
    options: [
      "Explain the mandatory duty honestly, involve the child-protection pathway, and support the family through the process (standard)",
      "Promise secrecy to preserve the family (common but wrong)",
      "Let the family resolve it internally",
      "Delay until she changes her mind",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "The duty is mandatory and non-deferrable; honesty about it preserves trust better than a false promise.",
    source: "POCSO 2012, Section 19",
  },
  {
    id: "q-mha-amend-7",
    type: "would_you_report",
    prompt: "A psychiatrist at a facility prescribes an antipsychotic for a patient with no documented assessment and tells you 'we always start with this'. Would you report?",
    options: [
      "Yes — prescribing without documented assessment is a standard-of-care breach with a reporting duty",
      "No — psychiatrists know best",
      "Only if harm occurs",
      "It's outside your scope to question",
    ],
    correct: 0,
    rationale: "Documented assessment before treatment is foundational; the reporting duty covers witnessed practice violations.",
    source: "MHA 2017 informed-consent provisions; professional standards",
  },
  {
    id: "q-mha-amend-8",
    type: "standard_vs_common",
    prompt: "A patient with a mental illness is denied admission to a general hospital ward 'because we don't treat those patients'. Which is standard?",
    options: [
      "Mental illness is a health condition like any other — denial of care is a breach of the right to treatment (standard)",
      "General hospitals can refuse mental-health patients (common but wrong)",
      "Only tertiary psychiatric hospitals must admit",
      "Admission is a privilege",
    ],
    correct: 0,
    isStandardCare: true,
    rationale: "MHA 2017 gives equal right to treatment in general hospitals; 'we don't treat those' is the discrimination the Act targets.",
    source: "MHA 2017, Section 18-19",
  },
  {
    id: "q-mha-amend-9",
    type: "would_you_report",
    prompt: "A colleague posts a patient's case details (with initials) on a WhatsApp group 'for learning'. Would you report?",
    options: [
      "Yes — identifying clinical information in an unsecured channel is a confidentiality breach with a reporting duty",
      "No — initials make it anonymous",
      "Only if the patient finds out",
      "It's common practice, ignore it",
    ],
    correct: 0,
    rationale: "Initials + context are identifying; the MHA privacy provisions and ethics codes cover all channels.",
    source: "MHA 2017, Sections 22-24; RCI code",
  },
  {
    id: "q-decode-follow-1",
    type: "best_response",
    prompt: "A student decoded 'ghabrahat' as panic and moved on. The patient's episodes are at rest, twice, with a racing heart and sweating. The cardiac workup is normal. What did the student miss?",
    options: [
      "Nothing — panic is the answer",
      "The physical screen (thyroid, cardiac) before the panic label",
      "The patient's family history",
      "The onset date",
    ],
    correct: 1,
    rationale: "Panic is a diagnosis of the pattern after the physical screen — 'ghabrahat' still deserves the thyroid/cardiac check.",
    source: "Kirmayer & Young (1998); panic-spectrum assessment",
  },
  {
    id: "q-decode-follow-2",
    type: "best_response",
    prompt: "A student correctly asked 'what do YOU think is causing it?' after a 'sar bhari' complaint. The patient said 'gas, my mother says'. What is the correct next move?",
    options: [
      "Explore the medical picture AND what the mother's frame means for help-seeking",
      "Correct the mother immediately",
      "Agree it's gas",
      "Change the subject to mood",
    ],
    correct: 0,
    rationale: "The attributional frame is clinical content — the physical workup and the meaning (family belief, help-seeking) run together.",
    source: "DSM-5 CFI; attributional idioms literature",
  },
  {
    id: "q-decode-follow-3",
    type: "order_steps",
    prompt: "Order the post-decode handling when the physical workup comes back normal.",
    options: [
      "Share the results honestly → re-frame the symptom (not imagined, real pain) → address the worry → behavioural plan",
      "Hide the results and reassure vaguely",
      "Tell them 'nothing is wrong' and close",
      "Send them for a second opinion to be safe",
    ],
    correct: 0,
    rationale: "Normal workups need honest results + symptom validation + the anxiety loop treated — 'it's all fine' is not a plan.",
    source: "Health-anxiety literature; somatic-symptom guidance",
  },
  {
    id: "q-decode-follow-4",
    type: "best_response",
    prompt: "A patient with 'not feeling fresh' turns out to have constipation, and is relieved: 'so I'm not going mad'. What is the best next line?",
    options: [
      "Validate the relief and explain the constipation-diet-motion link — then check whether anything under the fresh is still there",
      "'I told you it was nothing'",
      "Immediately pivot to mood screening",
      "End the session — resolved",
    ],
    correct: 0,
    rationale: "The relieved patient still needs the second glance — the idiom often carries both the physical and the psychological at once.",
    source: "Nichter (1981); DSM-5 CFI",
  },
  {
    id: "q-ood-audit-1",
    type: "spot_the_error",
    prompt: "Which is the error in this referral decision?",
    excerpt: "A client with stable grief, functioning well, is referred to a psychiatrist 'because grief is serious'. The psychiatrist asks why they were sent.",
    options: [
      "The grief itself is the reason to refer",
      "Referral without a clinical reason over-burdens the system and abandons the client",
      "Documenting the referral",
      "Informing the client",
    ],
    correct: 1,
    rationale: "Over-referral is a real harm — stable grief belongs with the counsellor; the referral was the anxious move, not the clinical one.",
    source: "Out-of-depth reasoning; over-referral literature",
  },
  {
    id: "q-ood-audit-2",
    type: "best_response",
    prompt: "A student is torn between 'continue' and 'refer' for a client with moderate anxiety who asks for medication. What decides?",
    options: [
      "The fear of missing something → refer",
      "The referral WORKS when the treatment genuinely exceeds your scope — moderate anxiety with a medication question belongs with the prescriber only for the drug; the therapy continues with you",
      "Whatever the client prefers",
      "Whatever the family prefers",
    ],
    correct: 1,
    rationale: "Referral is task-specific — the medication question goes to the prescriber, the therapy stays; abandoning both is the error.",
    source: "RCI scope; out-of-depth framework",
  },
  {
    id: "q-ood-audit-3",
    type: "spot_the_error",
    prompt: "Which is the error?",
    excerpt: "A counsellor refers every client with any suicidal thought to emergency psychiatry, without a risk assessment first, 'to be safe'.",
    options: [
      "Assessing suicidality in the session",
      "The blanket emergency referral without severity assessment — it over-floods the ER and avoids the clinical work",
      "Asking about suicidal thoughts at all",
      "Documenting risk",
    ],
    correct: 1,
    rationale: "The risk assessment is the counselling skill — referral follows the assessment, not the thought alone.",
    source: "Risk-assessment frameworks; mhGAP",
  },
  {
    id: "q-ood-audit-4",
    type: "order_steps",
    prompt: "Order the appropriate-response sequence when a client's needs exceed your scope.",
    options: [
      "Assess the actual need → identify what exceeds scope → refer the specific piece → stay or hand over with explanation + follow-up",
      "Refer everything immediately",
      "Keep everything regardless",
      "Ask the family what they want",
    ],
    correct: 0,
    rationale: "The scoping sequence is: specific need → specific referral → continuity or honest handover with follow-up.",
    source: "Out-of-depth framework",
  },
  {
    id: "q-decode-follow-5",
    type: "spot_the_error",
    prompt: "Which is the error?",
    excerpt: "Patient: 'kamzori, doctor, since the night out.'\nStudent: 'That's your body's natural loss — don't worry about it.' (moves on)",
    options: [
      "Naming the physiology",
      "Dismissing the worry after one line — the shame and the distress need the respectful space, not a one-liner",
      "Addressing the physical concern",
      "Using plain language",
    ],
    correct: 1,
    rationale: "Dhat distress needs psychoeducation AND the emotional work — a dismissive one-liner leaves the shame untouched.",
    source: "Sumathipala et al. (2004)",
  },
  {
    id: "q-ood-audit-5",
    type: "best_response",
    prompt: "A client's case genuinely needs psychiatric medication review. What does the counsellor owe the client at the handover?",
    options: [
      "Nothing beyond the referral — the psychiatrist takes over",
      "A warm handover: explain the referral honestly, share relevant history (with consent), and commit to continuing the non-medication work",
      "A full clinical notes transfer",
      "An apology for failing",
    ],
    correct: 1,
    rationale: "The referral is a co-managed handover, not a handoff — the counsellor stays for the therapy while psychiatry handles the medication.",
    source: "Integrated-care guidance; RCI scope",
  },
];

// Phase 1 §3 — the new-type bank (decode_idiom, whats_missing,
// predict_consequence, confidence_mcq, unpopular_right + restraint set).
QUIZ_BANK.push(...PHASE1_QUIZ_ITEMS);
