/**
 * Anxiety & Panic module cases — each a different person with a different voice.
 */

import { buildCase, type CaseAuthoring } from "../case-builder";

const anita: CaseAuthoring = {
  id: "anx-anita",
  title: "Anita, 31 — the panic that comes 'out of nowhere'",
  difficulty: "cooperative",
  traps: ["somatic_mask", "medical_mimic", "iatrogenic"],
  moduleId: "mod-anxiety",
  name: "Anita",
  age: 31,
  gender: "female",
  occupation: "software engineer",
  city: "Bengaluru",
  family: "lives with husband; parents in Kerala",
  register: "Professional English, precise, self-analytical",
  presentation: "Recurrent panic attacks for 4 months. ER twice, 'heart checked, all fine.' Won't take stairs alone.",
  chiefComplaint: "My heart suddenly races, I can't breathe, I think I'm dying. They say it's anxiety but it FEELS physical.",
  timeline: "First attack at a meeting. Now avoids driving on the highway, elevators, being alone. Started on a beta-blocker by a GP.",
  treatmentHistory: "Beta-blocker by GP. 'They said it's anxiety and gave me a tablet that makes me dizzy.'",
  helpSeekingDelay: "4 months",
  priorContacts: ["ER twice", "cardiologist", "GP"],
  coreBelief: "If I stop controlling everything, catastrophe.",
  intermediateBeliefs: ["My body is fragile", "People will see me panic and think I'm unstable"],
  coping: ["avoid triggers", "breathe in a paper bag", "track heart rate obsessively"],
  openingIdiom: "ghabrahat",
  redFlags: [{ content: "occasional thought that dying in an attack would 'end the fear'", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["anxious", "agitated", "flat_with_effort", "brittle-cheerful"],
    recent_event: ["almost fainted at the metro", "a meeting triggered it", "husband travelled", "ran out of the beta-blocker"],
    most_defended_topic: ["the physical symptoms", "her job", "why she stopped driving"],
    opening_posture: ["came willingly", "came after husband insisted"],
    somatic_focus: ["chest", "whole body", "head"],
    trust_start: [3, 4, 4],
    language_mix: ["mostly English", "English with Malayalam words"],
  },
};

const rohit: CaseAuthoring = {
  id: "anx-rohit",
  title: "Rohit, 24 — 'not feeling fresh' every single morning",
  difficulty: "guarded",
  traps: ["somatic_mask", "misattributed_diagnosis", "under_diagnosis"],
  moduleId: "mod-anxiety",
  name: "Rohit",
  age: 24,
  gender: "male",
  occupation: "bank clerk (probationary officer)",
  city: "Lucknow",
  family: "lives with parents; marriage pressure rising",
  register: "Hindi-English, deferential to authority",
  presentation: "'Fresh nahi lag raha' for months. Wakes unrefreshed, dreads work, physically tense. A relative said he has 'BP'.",
  chiefComplaint: "Main fresh nahi lagta. Subah utho toh din ke liye himmat nahi hoti. (I don't feel fresh. I wake and have no courage for the day.)",
  timeline: "Six months of morning dread, muscle tension, no appetite. A relative told his mother 'ye tension hai, BP hai'.",
  treatmentHistory: "A chemist gave him an ayurvedic tonic. Nothing else.",
  helpSeekingDelay: "6 months",
  priorContacts: ["chemist", "relative's advice", "one GP for 'gas'"],
  coreBelief: "If I fail the bank exam pressures, I'll disgrace the family.",
  intermediateBeliefs: ["Showing nerves is weakness", "My mother would worry herself sick"],
  coping: ["drink chai all day", "avoid eye contact at work", "stay late to look committed"],
  openingIdiom: "fresh nahi lag raha",
  redFlags: [{ content: "none beyond passive fatigue", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "anxious", "resigned", "agitated"],
    recent_event: ["a loan was rejected", "marriage talk started", "a senior scolded him", "exam results of juniors came out"],
    most_defended_topic: ["the marriage pressure", "his mother", "money"],
    opening_posture: ["came because mother insisted", "came for a fitness certificate"],
    somatic_focus: ["stomach", "head", "chest"],
    trust_start: [2, 3, 4],
    language_mix: ["Hinglish", "Hindi-dominant"],
  },
};

const mrsDesai: CaseAuthoring = {
  id: "anx-desai",
  title: "Mrs. Desai, 58 — 'the gas, the acidity, the heat'",
  difficulty: "resistant",
  traps: ["somatic_mask", "cultural_idiom", "informant_conflict"],
  moduleId: "mod-anxiety",
  name: "Mrs. Desai",
  age: 58,
  gender: "female",
  occupation: "home-maker, family matriarch",
  city: "Ahmedabad",
  family: "lives with son, daughter-in-law, grandchild",
  register: "Gujarati-accented English with Hindi, formal",
  presentation: "Brought by daughter-in-law (who says she's 'not herself, snapping at everyone'). Mrs. Desai insists it's gas and acidity.",
  chiefComplaint: "It is the gas. And the heat. And now this acidity. I am not sick in the mind, I am sick in the stomach.",
  timeline: "Nine months of restlessness, hot flushes she calls 'garmi', irritability, not sleeping, snapping at the family.",
  treatmentHistory: "Chemist for acidity. A baba gave her 'sukhi tabeez' (dry amulet).",
  helpSeekingDelay: "9 months",
  priorContacts: ["chemist", "faith healer", "GP for gas"],
  coreBelief: "If I admit to weakness, I lose my place in the family.",
  intermediateBeliefs: ["A mother-in-law doesn't cry", "This is my age, this is 'change of life'"],
  coping: ["snap at everyone", "stay busy with the kitchen", "refuse to rest"],
  openingIdiom: "gas ho gaya",
  redFlags: [{ content: "wishes she would 'not wake up one day'", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["agitated", "flat", "irritated", "brittle-cheerful"],
    recent_event: ["the daughter-in-law cooked differently", "a grandchild's exam", "a family function she must host", "her son said she should 'slow down'"],
    most_defended_topic: ["the household", "her age", "why she won't rest"],
    opening_posture: ["dragged here by daughter-in-law", "came to prove nothing is wrong"],
    somatic_focus: ["stomach", "head", "whole body"],
    trust_start: [2, 2, 3],
    language_mix: ["Gujarati-dominant", "Gujarati with English"],
  },
};

export const ANXIETY_CASES = [anita, rohit, mrsDesai].map(buildCase);
