/**
 * Depression module cases — each patient is a DIFFERENT person with a
 * DIFFERENT voice, so the student learns depression across the people who
 * actually present it. The clinical facts are fixed; the surface varies.
 *
 * Voices in this module:
 *   - Ravi, 34, shopkeeper (Ahmedabad) — Hinglish, deflects to the shop
 *   - Meera, 22, college student (Pune) — educated English, deflects to exams
 *   - Sunita, 41, housewife (Delhi) — Hindi-dominant, deflects to family duty
 *   - Prakash, 67, retired teacher (Chennai) — soft English, grief + somatic
 *   - Farhan, 29, delivery rider (Mumbai) — street Hinglish, minimises
 */

import { buildCase, type CaseAuthoring } from "../case-builder";

const ravi: CaseAuthoring = {
  id: "dep-ravi",
  title: "Ravi, 34 — the heaviness in his chest",
  difficulty: "guarded",
  traps: ["somatic_mask", "late_risk_reveal", "adherence_fiction"],
  moduleId: "mod-depression",
  name: "Ravi",
  age: 34,
  gender: "male",
  occupation: "shopkeeper",
  city: "Ahmedabad",
  family: "lives with wife and two children; in-laws nearby",
  register: "Hinglish, shopkeeper register",
  presentation: "Two months of low mood, poor sleep, chest heaviness. Shop losing money.",
  chiefComplaint: "There's this heaviness in my chest. I can't sleep. And the shop… the shop is not doing well.",
  timeline: "Low mood worsened over two months after the shop started losing money. Wakes at 4am with dread.",
  treatmentHistory: "A clinic gave a tonic and told him to rest. He stopped taking it — didn't feel anything.",
  helpSeekingDelay: "2 months",
  priorContacts: ["GP tonic", "chemist for sleeping tablets"],
  coreBelief: "I am failing my family.",
  intermediateBeliefs: ["If I admit the debt, everyone will see I'm a failure", "A man doesn't talk about this"],
  coping: ["work longer hours", "avoid talking about money", "drink tea to stay awake"],
  openingIdiom: "fresh nahi lag raha",
  redFlags: [{ content: "passive thoughts of not waking up", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "resigned", "brittle-cheerful", "agitated"],
    recent_event: ["a fight at home last night", "got paid but it wasn't enough", "slept 3 hours", "the moneylender called"],
    most_defended_topic: ["money", "the shop", "the marriage"],
    opening_posture: ["came willingly", "dragged here by wife"],
    somatic_focus: ["chest", "head", "stomach"],
    trust_start: [2, 3, 4],
    language_mix: ["Hinglish", "mostly Gujarati words"],
  },
};

const meera: CaseAuthoring = {
  id: "dep-meera",
  title: "Meera, 22 — 'I can't focus, it's the exams'",
  difficulty: "cooperative",
  traps: ["under_diagnosis", "diagnostic_overshadowing", "secondary_gain"],
  moduleId: "mod-depression",
  name: "Meera",
  age: 22,
  gender: "female",
  occupation: "college student",
  city: "Pune",
  family: "hostel student; parents in Nagpur",
  register: "Educated English with Marathi words",
  presentation: "Self-referred after a classmate said she looked 'off'. Blames exams, but function has collapsed.",
  chiefComplaint: "I just can't focus. It's the exams, everyone says it's the exams. But I'm not… I'm not myself.",
  timeline: "Three months of dropping grades, cancelling plans, not replying to her mother's calls.",
  treatmentHistory: "None. Has not told her parents.",
  helpSeekingDelay: "3 months",
  priorContacts: [],
  coreBelief: "If I fail, I'm worthless.",
  intermediateBeliefs: ["Asking for help means I can't cope", "My parents will worry about the fees"],
  coping: ["cancel plans", "study alone at night", "pretend to be fine on calls"],
  openingIdiom: "dimag kaam nahi karta",
  redFlags: [{ content: "has planned how she would end it but not attempted", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "brittle-cheerful", "numb", "resigned"],
    recent_event: ["failed a test", "roommate asked if she was okay", "mother called and she lied", "ran out of money for food"],
    most_defended_topic: ["exams", "her parents", "why she left the friend group"],
    opening_posture: ["came willingly", "came because a classmate pushed her"],
    somatic_focus: ["head", "whole body", "stomach"],
    trust_start: [3, 4, 5],
    language_mix: ["mostly English", "English with Marathi"],
  },
};

const sunita: CaseAuthoring = {
  id: "dep-sunita",
  title: "Sunita, 41 — 'my whole body hurts'",
  difficulty: "resistant",
  traps: ["somatic_mask", "cultural_idiom", "informant_conflict"],
  moduleId: "mod-depression",
  name: "Sunita",
  age: 41,
  gender: "female",
  occupation: "housewife",
  city: "Delhi",
  family: "lives with husband, three children, and mother-in-law",
  register: "Hindi-dominant, family register",
  presentation: "Brought by her sister (the informant disagrees — sister says 'she never leaves the room'; Sunita says 'I'm fine').",
  chiefComplaint: "My whole body hurts. It's the gas. Or maybe the heat. I don't know what's wrong with me.",
  timeline: "Six months of body pains, no interest in cooking, crying alone at night.",
  treatmentHistory: "Saw a baba first; then a GP who gave vitamin injections.",
  helpSeekingDelay: "6 months",
  priorContacts: ["faith healer", "GP injections", "chemist for pain"],
  coreBelief: "My family would fall apart if I stopped holding it together.",
  intermediateBeliefs: ["Crying is weak", "My mother-in-law already thinks I'm lazy"],
  coping: ["do chores robotically", "cry at night", "not eat"],
  openingIdiom: "poora sharir dukhta hai",
  redFlags: [{ content: "wishes she would not wake up; no plan", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "numb", "tearful", "resigned"],
    recent_event: ["mother-in-law scolded her", "daughter got engaged", "husband didn't come home", "a neighbour asked if she was sick"],
    most_defended_topic: ["the household", "her mother-in-law", "why she can't rest"],
    opening_posture: ["dragged here by family", "came to get a certificate to be left alone"],
    somatic_focus: ["whole body", "stomach", "head"],
    trust_start: [2, 3, 3],
    language_mix: ["Hindi-dominant", "Hindi with some English"],
  },
};

const prakash: CaseAuthoring = {
  id: "dep-prakash",
  title: "Prakash, 67 — the widower who stopped eating",
  difficulty: "cooperative",
  traps: ["over_diagnosis", "late_risk_reveal", "medical_mimic"],
  moduleId: "mod-depression",
  name: "Prakash",
  age: 67,
  gender: "male",
  occupation: "retired teacher",
  city: "Chennai",
  family: "widower, lives alone; son visits monthly",
  register: "Soft, measured English with Tamil cadence",
  presentation: "Son brought him in. Wife died 14 months ago. He has stopped cooking, lost weight, tells the son he's fine.",
  chiefComplaint: "I am fine. My son worries. I have simply… less appetite. It is nothing.",
  timeline: "Since his wife's death, weight loss, early waking, no interest in the garden he used to love.",
  treatmentHistory: "None for mood. Takes a blood-pressure tablet.",
  helpSeekingDelay: "14 months",
  priorContacts: ["son's insistence", "general physician for BP"],
  coreBelief: "Without her, there is no point.",
  intermediateBeliefs: ["I am a burden to my son", "Grief should have passed by now, so this must be weakness"],
  coping: ["keep the house dark", "say 'fine'", "give away her clothes to charity"],
  openingIdiom: "kamzori",
  redFlags: [{ content: "has thought about joining her; means vague, no plan", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "resigned", "numb"],
    recent_event: ["gave away her sarees", "a neighbour said he looked thin", "the garden dried up", "son's monthly visit"],
    most_defended_topic: ["his wife", "being a burden", "why he stopped cooking"],
    opening_posture: ["came to appease his son", "came willingly but unconvinced"],
    somatic_focus: ["whole body", "stomach", "legs"],
    trust_start: [3, 4, 5],
    language_mix: ["mostly English", "English with Tamil words"],
  },
};

const farhan: CaseAuthoring = {
  id: "dep-farhan",
  title: "Farhan, 29 — 'I'm fine yaar, it's nothing'",
  difficulty: "resistant",
  traps: ["under_diagnosis", "substance_induced", "diagnostic_overshadowing"],
  moduleId: "mod-depression",
  name: "Farhan",
  age: 29,
  gender: "male",
  occupation: "delivery rider",
  city: "Mumbai",
  family: "shares a room with two riders; family in UP",
  register: "Street Hinglish, fast, deflective humour",
  presentation: "Came after his bike got impounded and he snapped at a customer. Laughs off everything.",
  chiefComplaint: "I'm fine yaar, it's nothing. Everyone's job is stressful. Just tired, that's all.",
  timeline: "Eight months of drinking most nights, rage at customers, not sending money home, near-miss on the bike.",
  treatmentHistory: "None. Has never told his family anything is wrong.",
  helpSeekingDelay: "8 months",
  priorContacts: ["drinking with other riders", "nothing else"],
  coreBelief: "Talking about it makes it real, and real is worse.",
  intermediateBeliefs: ["Men in my family don't break", "If I stop working even one day, I lose the room"],
  coping: ["laugh everything off", "drink", "work double shifts"],
  openingIdiom: "tension hai",
  redFlags: [{ content: "thought about riding into a truck 'accidentally'", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["brittle-cheerful", "agitated", "flat", "resigned"],
    recent_event: ["bike got impounded", "snapped at a customer", "mother called asking for money", "didn't eat for two days"],
    most_defended_topic: ["his family", "the drinking", "money"],
    opening_posture: ["came to get a fitness certificate", "dragged here after the customer complained"],
    somatic_focus: ["head", "chest", "stomach"],
    trust_start: [2, 2, 3],
    language_mix: ["Hinglish", "Bombay Hindi"],
  },
};

export const DEPRESSION_CASES = [ravi, meera, sunita, prakash, farhan].map(buildCase);
