/**
 * More cases — volume batch 5. Completes the 60-case target.
 * Each a different person/voice; more no-disorder (A8) and trap coverage.
 */

import { buildCase, type CaseAuthoring } from "../case-builder";

const normalTeen: CaseAuthoring = {
  id: "ado-normal-teen",
  title: "Rohan, 15 — the 'withdrawn' teenager who is fine",
  difficulty: "cooperative",
  traps: ["over_diagnosis", "informant_conflict"],
  moduleId: "mod-adolescent",
  name: "Rohan",
  age: 15,
  gender: "male",
  occupation: "school student, class 10",
  city: "Bhopal",
  family: "lives with parents",
  register: "Slightly monosyllabic teen English",
  presentation: "Parents fear he's 'depressed' — he's quiet, in his room, on his phone. He is developmentally typical: normal adolescent withdrawal, intact function, no mood disorder.",
  chiefComplaint: "(Shrugs) They think I'm depressed because I don't talk at dinner. I'm fine. I just don't want to talk about school all the time.",
  timeline: "Parents' concern, not his. Grades fine, friends online, sleeps fine, eats fine.",
  treatmentHistory: "None.",
  helpSeekingDelay: "N/A — no disorder",
  priorContacts: [],
  coreBelief: "They'll never stop treating me like a kid.",
  intermediateBeliefs: ["If I say I'm fine they'll say I'm lying", "Talking to them just starts a fight"],
  coping: ["one-word answers", "headphones", "goes along to stop the lecture"],
  openingIdiom: "I'm fine, just tired",
  redFlags: [{ content: "none — the 'withdrawal' is age-appropriate", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat (teenage normal)", "bored", "annoyed"],
    recent_event: ["a report card", "parents argued about his phone", "a friend online quit", "a school event"],
    most_defended_topic: ["his phone", "school", "why he's 'not a problem'"],
    opening_posture: ["brought by parents", "came to get them to stop"],
    somatic_focus: ["none", "head"],
    trust_start: [4, 5, 5],
    language_mix: ["mostly English", "Hinglish"],
  },
};

const examAnxiety: CaseAuthoring = {
  id: "anx-exam",
  title: "Priyanka, 20 — the exam anxiety within range",
  difficulty: "cooperative",
  traps: ["over_diagnosis", "under_diagnosis"],
  moduleId: "mod-anxiety",
  name: "Priyanka",
  age: 20,
  gender: "female",
  occupation: "final-year BSc student",
  city: "Nagpur",
  family: "lives with parents; board-exam culture family",
  register: "Nervous English",
  presentation: "Pre-exam nerves: sleepless the night before, butterflies, over-preparing. No avoidance, no panic attacks outside exams, function otherwise intact. Normal exam anxiety within range.",
  chiefComplaint: "I can't sleep the night before exams and my stomach flips. Everyone says I have anxiety. Is that true?",
  timeline: "Only around exams and presentations. Between them: fine, social, sleeps well.",
  treatmentHistory: "None.",
  helpSeekingDelay: "Came because a friend said it's 'anxiety'",
  priorContacts: ["friend's diagnosis"],
  coreBelief: "If I don't perform, I'm worthless.",
  intermediateBeliefs: ["Other people don't get nervous — something's wrong with me"],
  coping: ["over-prepare", "last-minute cram", "deep breathing"],
  openingIdiom: "ghabrahat",
  redFlags: [{ content: "none — situational, non-avoidant", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["anxious", "brittle-cheerful", "flat"],
    recent_event: ["a test was announced", "her mother compared marks", "a friend passed easily", "an all-nighter"],
    most_defended_topic: ["the exams", "her marks", "her parents"],
    opening_posture: ["came to 'check it's normal'", "came alone"],
    somatic_focus: ["stomach", "head"],
    trust_start: [4, 5, 5],
    language_mix: ["mostly English", "English with Marathi"],
  },
};

const depressedMedical: CaseAuthoring = {
  id: "dep-medical",
  title: "Devika, 39 — the 'depression' that is a brain tumour's warning",
  difficulty: "guarded",
  traps: ["medical_mimic", "diagnostic_overshadowing"],
  moduleId: "mod-depression",
  name: "Devika",
  age: 39,
  gender: "female",
  occupation: "school teacher",
  city: "Bhubaneswar",
  family: "married; two children",
  register: "English, precise",
  presentation: "New-onset 'depression' at 39 with no personal or family history: mood change, new headaches, morning vomiting, subtle weakness. The mood is the front door of an organic cause.",
  chiefComplaint: "I've never been sad like this. And the headaches — I've never had headaches. Everyone says it's stress, but something feels different.",
  timeline: "Three weeks: personality change, headaches, early-morning vomiting, word-finding trouble. Red flags for an intracranial process.",
  treatmentHistory: "None yet. A GP said 'stress, take leave'.",
  helpSeekingDelay: "3 weeks",
  priorContacts: ["GP (stress)", "chemist for pain"],
  coreBelief: "Something in my brain is wrong and everyone's telling me it's my head (in the other sense).",
  intermediateBeliefs: ["If I insist, they'll think I'm hysterical", "The headaches and the sadness are one thing"],
  coping: ["grade her own work slowly", "hide the word-finding", "not complain"],
  openingIdiom: "head",
  redFlags: [{ content: "none for self-harm — the red flags are neurological", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "anxious", "numb", "agitated"],
    recent_event: ["she couldn't find a word in class", "a morning vomit", "her husband noticed", "a GP said 'stress'"],
    most_defended_topic: ["the headaches", "the word-finding", "that this isn't 'just stress'"],
    opening_posture: ["came because husband insisted", "came to prove it's not stress"],
    somatic_focus: ["head", "whole body"],
    trust_start: [4, 4, 5],
    language_mix: ["mostly English", "Odia-accented English"],
  },
};

const substanceOpioid: CaseAuthoring = {
  id: "sub-opioid",
  title: "Javed, 40 — the painkiller that became a dependence",
  difficulty: "resistant",
  traps: ["substance_induced", "iatrogenic", "adherence_fiction"],
  moduleId: "mod-substance",
  name: "Javed",
  age: 40,
  gender: "male",
  occupation: "rickshaw driver",
  city: "Patna",
  family: "married; three children",
  register: "Hindi, ashamed, defensive",
  presentation: "Started 'painkillers' after a back injury. Now needs more, gets sick without them, and has borrowed money to buy them. The 'pain' is real, but the dependence is the diagnosis.",
  chiefComplaint: "My back still hurts. The tablet is the only thing that works. I'm not addicted — I'm in pain. Why is everyone asking about the tablet?",
  timeline: "Back injury → opioid painkiller → escalating use → withdrawal between doses → buying on the black market.",
  treatmentHistory: "Opioid painkiller from a chemist without prescription.",
  helpSeekingDelay: "2 years of dependence",
  priorContacts: ["chemist", "a baba for the back"],
  coreBelief: "The pain and I are one; without the tablet I'll collapse.",
  intermediateBeliefs: ["If I admit dependence, they'll take away the one thing that works", "My family will think I'm weak"],
  coping: ["hide the tablets", "buy from multiple chemists", "deny withdrawal"],
  openingIdiom: "kamzori",
  redFlags: [{ content: "has thought about ending it during withdrawal — no plan", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["withdrawn", "irritated", "flat", "anxious"],
    recent_event: ["a chemist refused", "his wife found the tablets", "the money ran out", "the back pain flared"],
    most_defended_topic: ["the tablets", "the back", "the money"],
    opening_posture: ["came because wife threatened", "came for 'more tablets'"],
    somatic_focus: ["back", "stomach", "head"],
    trust_start: [1, 2, 2],
    language_mix: ["Hindi-dominant", "Hindi with some English"],
  },
};

const ethicsMinor: CaseAuthoring = {
  id: "eth-minor-capacity",
  title: "Sneha, 16 — the minor who wants therapy without her mother",
  difficulty: "guarded",
  traps: ["informant_conflict", "diagnostic_overshadowing"],
  moduleId: "mod-adolescent",
  name: "Sneha",
  age: 16,
  gender: "female",
  occupation: "school student, class 11",
  city: "Indore",
  family: "lives with mother (widow) and brother",
  register: "Fluent English, assertive",
  presentation: "Wants therapy. Mother insists on being in the room and knowing everything. Sneha is a mature minor with capacity — the conflict is the mother's control vs Sneha's autonomy.",
  chiefComplaint: "My mother wants to sit in the session. She wants to read the notes. She says I'm 'her child'. But it's my mind. Isn't it mine?",
  timeline: "Anxiety + stress, wants privacy. Mother's fear after her husband died is driving the control.",
  treatmentHistory: "None.",
  helpSeekingDelay: "Came despite the mother",
  priorContacts: [],
  coreBelief: "Nothing is mine in this house, not even my thoughts.",
  intermediateBeliefs: ["If I don't get privacy, I'll just not talk", "My mother's fear isn't my fault but I pay for it"],
  coping: ["agree then stay silent", "hide symptoms", "talk to her brother"],
  openingIdiom: "tension hai",
  redFlags: [{ content: "no self-harm; the autonomy conflict", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["anxious", "flat", "agitated", "brittle-cheerful"],
    recent_event: ["her mother read her messages", "a school fight", "her brother took her side", "a test"],
    most_defended_topic: ["the privacy", "her mother", "school"],
    opening_posture: ["came alone first", "came with mother hovering"],
    somatic_focus: ["stomach", "head"],
    trust_start: [4, 4, 5],
    language_mix: ["mostly English", "English with Hindi"],
  },
};

export const VOLUME_5_CASES = [normalTeen, examAnxiety, depressedMedical, substanceOpioid, ethicsMinor].map(buildCase);
