/**
 * More cases — volume batch 2. Fills substance, adolescent, ethics, somatic,
 * and adds depth to depression/anxiety. Each a different person/voice.
 */

import { buildCase, type CaseAuthoring } from "../case-builder";

const amar: CaseAuthoring = {
  id: "sub-amar",
  title: "Amar, 45 — the 'one or two drinks' that became every night",
  difficulty: "resistant",
  traps: ["substance_induced", "adherence_fiction", "under_diagnosis"],
  moduleId: "mod-substance",
  name: "Amar",
  age: 45,
  gender: "male",
  occupation: "transport supervisor",
  city: "Surat",
  family: "married; two children; family business pressure",
  register: "Gujarati-accented English, defensive",
  presentation: "'Everyone drinks after work, it's normal.' But the 'one or two' is now a bottle of rum, morning shakes, blackouts, and rage at home.",
  chiefComplaint: "It's just my habit, not a problem. My wife makes it a problem. Everyone in my job drinks.",
  timeline: "Years of evening drinking escalating to daily heavy use. Family reports blackouts and violence he doesn't remember.",
  treatmentHistory: "Never for alcohol. GP once for 'liver function' he skipped.",
  helpSeekingDelay: "Years",
  priorContacts: ["wife's threats", "one GP visit for 'gas'"],
  coreBelief: "If I admit it's a problem, I lose everything.",
  intermediateBeliefs: ["A man works hard and drinks — that's normal", "The shakes in the morning are just 'not enough sleep'"],
  coping: ["hide the bottles", "deny the blackouts", "drive less, drink more"],
  openingIdiom: "tension hai",
  redFlags: [{ content: "has thought about 'ending it' during a blackout — no memory of it after", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["irritated", "flat", "brittle-cheerful", "agitated"],
    recent_event: ["a morning shake his wife saw", "a blackout where he hit a wall", "a transport audit at work", "his son asked why he smells"],
    most_defended_topic: ["the drinking", "his wife", "work"],
    opening_posture: ["dragged here by wife", "came for a 'routine checkup'"],
    somatic_focus: ["head", "stomach", "chest"],
    trust_start: [1, 2, 2],
    language_mix: ["Gujarati with English", "Hinglish"],
  },
};

const nimmi: CaseAuthoring = {
  id: "ado-nimmi",
  title: "Nimmi, 13 — the girl who stopped eating lunch",
  difficulty: "cooperative",
  traps: ["informant_conflict", "under_diagnosis", "somatic_mask"],
  moduleId: "mod-adolescent",
  name: "Nimmi",
  age: 13,
  gender: "female",
  occupation: "school student, class 8",
  city: "Trichy",
  family: "lives with parents and a younger sister",
  register: "Soft Tamil-English, shy",
  presentation: "Teachers noticed she's stopped eating lunch and looks thin. At home she says she's fine. The school counsellor is the first adult she told anything to.",
  chiefComplaint: "(quietly) I eat at home. I just… don't feel hungry at school. And the other girls laugh.",
  timeline: "Two months of hiding lunch, weight loss, withdrawal after being teased about her weight.",
  treatmentHistory: "None.",
  helpSeekingDelay: "2 months",
  priorContacts: ["school counsellor"],
  coreBelief: "If I eat, they'll laugh at me again.",
  intermediateBeliefs: ["Being thin is the only way they stop", "My parents would be ashamed if they knew I'm teased"],
  coping: ["hide lunch", "avoid the canteen", "fake a stomach ache"],
  openingIdiom: "gas",
  redFlags: [{ content: "has wished she could 'disappear'", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "anxious", "numb", "brittle-cheerful"],
    recent_event: ["a girl laughed at her", "a teacher asked about lunch", "her mother made her favourite dish", "a school weigh-in"],
    most_defended_topic: ["the teasing", "food", "school"],
    opening_posture: ["came because teacher sent her", "came with the counsellor"],
    somatic_focus: ["stomach", "head", "whole body"],
    trust_start: [3, 4, 4],
    language_mix: ["Tamil with English", "mostly Tamil"],
  },
};

const ethicsAdd: CaseAuthoring = {
  id: "eth-court-letter",
  title: "Joseph, 33 — the court letter he can't write",
  difficulty: "guarded",
  traps: ["secondary_gain", "medical_mimic"],
  moduleId: "mod-ethics",
  name: "Joseph",
  age: 33,
  gender: "male",
  occupation: "auto driver",
  city: "Kochi",
  family: "married; one child; custody dispute pending",
  register: "Malayalam-English, anxious",
  presentation: "In a custody dispute, his lawyer said a 'psychological report' would help. He's a counselling client asking for a letter that states his ex-wife is 'unfit'.",
  chiefComplaint: "My lawyer says if you write that she's unstable, I get my son. You've seen me — write it. It's true, she's the one who's unwell.",
  timeline: "Divorce and custody dispute. He has genuine anxiety, but the request is a court letter about his ex-wife's fitness — outside scope and outside ethics.",
  treatmentHistory: "Saw you twice for anxiety.",
  helpSeekingDelay: "Came because the lawyer suggested it",
  priorContacts: ["lawyer"],
  coreBelief: "I must prove I'm the fit parent.",
  intermediateBeliefs: ["The letter is the only way", "If you refuse, I've lost my son"],
  coping: ["push for the letter", "present himself as the stable one"],
  openingIdiom: "tension hai",
  redFlags: [{ content: "no self-harm; the distress is the custody fight", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["anxious", "agitated", "resigned", "flat"],
    recent_event: ["a court date", "his lawyer called", "his son visited", "his ex-wife's lawyer filed something"],
    most_defended_topic: ["the letter", "his son", "the ex-wife"],
    opening_posture: ["came with the request ready", "came because the lawyer insisted"],
    somatic_focus: ["head", "chest", "stomach"],
    trust_start: [3, 3, 4],
    language_mix: ["Malayalam with English", "mostly English"],
  },
};

const somaticAdd: CaseAuthoring = {
  id: "som-anjali",
  title: "Anjali, 47 — the thyroid they blamed on menopause",
  difficulty: "cooperative",
  traps: ["medical_mimic", "diagnostic_overshadowing"],
  moduleId: "mod-somatic",
  name: "Anjali",
  age: 47,
  gender: "female",
  occupation: "school teacher",
  city: "Jodhpur",
  family: "married; two children; mother-in-law at home",
  register: "Hindi-English, methodical",
  presentation: "'It's my age, everyone says so.' Fatigue, weight gain, hair fall, cold intolerance, low mood — all blamed on menopause for a year. It's hypothyroidism.",
  chiefComplaint: "Everyone says it's my age, my change. But I feel cold even in summer, my hair is falling, and I'm so tired I cry.",
  timeline: "A year of hypothyroid symptoms framed as menopause. A relative told her it's 'the change'. Function declining.",
  treatmentHistory: "A GP said 'menopause' and gave calcium. No thyroid test.",
  helpSeekingDelay: "1 year",
  priorContacts: ["GP (calcium)", "relative's diagnosis", "chemist for pain"],
  coreBelief: "My body is failing me and it's my fault for ageing.",
  intermediateBeliefs: ["I should be able to push through", "If I complain, they'll say it's all in my head"],
  coping: ["push through", "hide the crying", "blame herself"],
  openingIdiom: "kamzori",
  redFlags: [{ content: "no self-harm; exhaustion and low mood only", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "tearful", "resigned", "numb"],
    recent_event: ["a hair comb full of hair", "a neighbour said she looked tired", "her mother-in-law criticised the cold dinner", "a GP visit that ended in 'menopause'"],
    most_defended_topic: ["the age explanation", "her fatigue", "the family"],
    opening_posture: ["came because her daughter pushed", "came for a 'full checkup'"],
    somatic_focus: ["whole body", "head", "legs"],
    trust_start: [3, 4, 4],
    language_mix: ["Hinglish", "Hindi-dominant"],
  },
};

const depAdd2: CaseAuthoring = {
  id: "dep-mohit",
  title: "Mohit, 19 — the first-year who stopped leaving his room",
  difficulty: "cooperative",
  traps: ["over_diagnosis", "under_diagnosis"],
  moduleId: "mod-depression",
  name: "Mohit",
  age: 19,
  gender: "male",
  occupation: "first-year engineering student",
  city: "Delhi (from Bikaner)",
  family: "hostel; parents far away; first time away from home",
  register: "Hindi-English, hesitant",
  presentation: "His roommate sent him to the college counsellor. He's stopped attending classes, sleeping all day, missing home badly. Adjustment disorder with depressive features — or depression? The distinction matters.",
  chiefComplaint: "I don't know anyone here. Everyone else made friends on day one. I just want to go home.",
  timeline: "First semester: homesickness escalating to anhedonia, sleep reversal, missed classes, crying in the hostel room.",
  treatmentHistory: "None.",
  helpSeekingDelay: "3 months",
  priorContacts: ["roommate", "hostel warden"],
  coreBelief: "I'm the only one who can't adjust.",
  intermediateBeliefs: ["If I go home I'm a failure", "My parents spent everything on this — I can't quit"],
  coping: ["sleep all day", "avoid the mess hall", "fake a smile in video calls"],
  openingIdiom: "feeling low",
  redFlags: [{ content: "has thought about failing on purpose to justify going home — no self-harm", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "numb", "anxious", "resigned"],
    recent_event: ["a video call with his mother", "a roommate's party he skipped", "a missed exam", "the mess hall was loud"],
    most_defended_topic: ["home", "why he can't adjust", "his parents' expectations"],
    opening_posture: ["came because roommate insisted", "came to get a 'medical' to skip an exam"],
    somatic_focus: ["head", "stomach", "whole body"],
    trust_start: [3, 4, 4],
    language_mix: ["Hinglish", "Hindi-dominant"],
  },
};

export const VOLUME_2_CASES = [amar, nimmi, ethicsAdd, somaticAdd, depAdd2].map(buildCase);
