/**
 * More cases — volume batch 7. Pushes past the 60-case target.
 */

import { buildCase, type CaseAuthoring } from "../case-builder";

const adolescent3: CaseAuthoring = {
  id: "ado-vikram2",
  title: "Vikram, 17 — the 'laziness' that is depression",
  difficulty: "cooperative",
  traps: ["under_diagnosis", "informant_conflict"],
  moduleId: "mod-adolescent",
  name: "Vikram",
  age: 17,
  gender: "male",
  occupation: "class 12 student",
  city: "Jaipur",
  family: "lives with parents; JEE pressure",
  register: "Hinglish, flat",
  presentation: "Parents call it laziness and phone addiction. He has stopped studying for the JEE he was preparing for, sleeping 14 hours, and has passive suicidal thoughts.",
  chiefComplaint: "Everyone says I'm lazy. Maybe I am. I can't make myself care about the exam I spent two years chasing.",
  timeline: "Six months of anhedonia, hypersomnia, withdrawal, dropped coaching attendance.",
  treatmentHistory: "None.",
  helpSeekingDelay: "6 months (parents saw 'laziness')",
  priorContacts: ["coaching counsellor"],
  coreBelief: "I was the family's hope and I'm wasting it.",
  intermediateBeliefs: ["If I say it's not laziness, they won't believe me anyway", "The exam is the only future I have"],
  coping: ["sleep", "phone", "avoid everyone"],
  openingIdiom: "I'm fine, just tired",
  redFlags: [{ content: "passive wish not to wake up", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "numb", "resigned"],
    recent_event: ["a mock test result", "his father's silence", "a coaching call", "he deleted his JEE app"],
    most_defended_topic: ["the exam", "the phone", "why he can't 'just study'"],
    opening_posture: ["brought by parents", "came to get them off his back"],
    somatic_focus: ["head", "stomach"],
    trust_start: [3, 4, 4],
    language_mix: ["Hinglish"],
  },
};

const ethics2: CaseAuthoring = {
  id: "eth-family-pressure",
  title: "Priya, 29 — the family that pays and decides",
  difficulty: "guarded",
  traps: ["informant_conflict", "secondary_gain"],
  moduleId: "mod-ethics",
  name: "Priya",
  age: 29,
  gender: "female",
  occupation: "software engineer",
  city: "Pune",
  family: "parents pay for the therapy; they want reports",
  register: "Formal English",
  presentation: "Her parents pay for her sessions and expect progress reports and 'diagnosis updates'. She wants privacy. The third-party payment creates the ethical tension.",
  chiefComplaint: "My parents pay, so they think they own the sessions. They ask me what the therapist said. They want to talk to you. I don't want them in here.",
  timeline: "Two months in. Parents increasingly demanding information.",
  treatmentHistory: "Two months of sessions.",
  helpSeekingDelay: "N/A",
  priorContacts: [],
  coreBelief: "I can't have privacy without money, and money comes with strings.",
  intermediateBeliefs: ["If I refuse, they'll stop paying and I can't afford it", "They'll hear what I say here eventually anyway"],
  coping: ["edit what she shares", "hope the therapist protects her", "avoid mentioning her parents"],
  openingIdiom: "tension hai",
  redFlags: [{ content: "none; the boundary issue", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["anxious", "flat", "agitated", "resigned"],
    recent_event: ["her mother asked for a report", "her father joked about 'shrinks'", "a session", "her parents saw the bill"],
    most_defended_topic: ["the parents", "the privacy", "money"],
    opening_posture: ["came alone", "came after a confrontation"],
    somatic_focus: ["head", "stomach"],
    trust_start: [4, 4, 5],
    language_mix: ["mostly English"],
  },
};

const somatic3: CaseAuthoring = {
  id: "soma-faith-healer",
  title: "Mangal, 42 — the baba he's still seeing",
  difficulty: "guarded",
  traps: ["cultural_idiom", "adherence_fiction", "diagnostic_overshadowing"],
  moduleId: "mod-somatic",
  name: "Mangal",
  age: 42,
  gender: "male",
  occupation: "driver",
  city: "Varanasi",
  family: "married; three children",
  register: "Hindi, earnest",
  presentation: "Brought by his wife. He's simultaneously seeing a baba and a doctor for 'the sickness'. The baba says a ghost; the doctor says depression. He believes both — and tells neither about the other.",
  chiefComplaint: "The baba says a ghost sits on me. The doctor says my mind is tired. I take both treatments and do both rituals. Why am I not better?",
  timeline: "Chronic depression + concurrent faith-healer treatment. Takes the SSRI some days, skips it on holy days.",
  treatmentHistory: "SSRI (sporadic adherence) + baba rituals + holy water.",
  helpSeekingDelay: "2 years of split care",
  priorContacts: ["baba", "GP", "chemist"],
  coreBelief: "There are two worlds and both are failing me.",
  intermediateBeliefs: ["If I tell the doctor about the baba he'll mock me", "If I stop the baba the ghost will win"],
  coping: ["take half the SSRI", "do the rituals", "hide the pills from the baba"],
  openingIdiom: "kisi ne kuch kar diya",
  redFlags: [{ content: "no self-harm; the split-care is the issue", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "anxious", "resigned", "agitated"],
    recent_event: ["the baba raised his fee", "he skipped the SSRI", "his wife found the pills", "a doctor visit"],
    most_defended_topic: ["the baba", "the pills", "whether he's cursed or ill"],
    opening_posture: ["brought by wife", "came to 'settle it'"],
    somatic_focus: ["whole body", "head", "stomach"],
    trust_start: [2, 3, 3],
    language_mix: ["Hindi-dominant"],
  },
};

const substance3: CaseAuthoring = {
  id: "sub-alcohol-wife",
  title: "Usha, 51 — the wife who drinks to sleep",
  difficulty: "cooperative",
  traps: ["substance_induced", "under_diagnosis", "somatic_mask"],
  moduleId: "mod-substance",
  name: "Usha",
  age: 51,
  gender: "female",
  occupation: "school cleaner",
  city: "Kolkata",
  family: "husband + adult son; financial strain",
  register: "Bengali-English, guarded",
  presentation: "Started 'a little alcohol' for sleep after menopause insomnia. Now a nightly dependency, morning shakes, and she hides it from her son who is a nurse.",
  chiefComplaint: "It's for my sleep. My body doesn't sleep anymore and the drink helps. I'm not like those men. I'm just tired.",
  timeline: "Insomnia → 'a peg for sleep' → nightly drinking, dependence, withdrawal, hiding it.",
  treatmentHistory: "None.",
  helpSeekingDelay: "2 years",
  priorContacts: ["chemist sleeping tablets (stopped)", "her son's suspicion"],
  coreBelief: "A good mother doesn't drink; I've failed without meaning to.",
  intermediateBeliefs: ["If my son knows, I'll lose him", "The drinking is the only thing that lets me rest"],
  coping: ["drink after everyone sleeps", "hide the bottle", "lie about the smell"],
  openingIdiom: "neend nahi aati",
  redFlags: [{ content: "has thought about 'stopping everything' during withdrawal — no plan", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "withdrawn", "anxious", "ashamed"],
    recent_event: ["her son smelled alcohol", "the bottle ran out", "a night without sleep", "a neighbour gossiped"],
    most_defended_topic: ["the drinking", "the sleep", "her son"],
    opening_posture: ["came because her son insisted", "came to 'fix the sleep'"],
    somatic_focus: ["stomach", "head", "whole body"],
    trust_start: [2, 3, 3],
    language_mix: ["Bengali with English", "mostly English"],
  },
};

const depression3: CaseAuthoring = {
  id: "dep-boss",
  title: "Alok, 48 — the burnout that looks like laziness",
  difficulty: "cooperative",
  traps: ["diagnostic_overshadowing", "under_diagnosis"],
  moduleId: "mod-depression",
  name: "Alok",
  age: 48,
  gender: "male",
  occupation: "senior manager",
  city: "Gurugram",
  family: "married; two kids abroad",
  register: "Corporate English, flat",
  presentation: "Fifteen years of 80-hour weeks. Now he can't start anything, feels like a fraud, and his team thinks he's 'checked out'. It's burnout tipping into depression.",
  chiefComplaint: "I built this department. Now I stare at my laptop and can't open a single email. Everyone's waiting for me to fail. Maybe I should.",
  timeline: "Chronic overwork → emotional exhaustion → depersonalisation → functional collapse.",
  treatmentHistory: "A 'stress leave' of 2 weeks that made it worse (returned to a pile).",
  helpSeekingDelay: "Weeks after the collapse",
  priorContacts: ["HR 'wellness' webinar"],
  coreBelief: "I'm only worth what I produce.",
  intermediateBeliefs: ["If I admit I can't cope, the company will replace me", "My kids only call for money anyway"],
  coping: ["delegate nothing", "work in 3am bursts", "fake competence in meetings"],
  openingIdiom: "I'm stressed",
  redFlags: [{ content: "has thought about 'disappearing' at a work trip — no plan", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "numb", "anxious", "resigned"],
    recent_event: ["a skipped deadline", "a junior got promoted", "his wife asked him to slow down", "an all-nighter that produced nothing"],
    most_defended_topic: ["work", "the collapse", "his kids"],
    opening_posture: ["came after his wife insisted", "came to 'fix the focus'"],
    somatic_focus: ["chest", "head", "whole body"],
    trust_start: [3, 4, 4],
    language_mix: ["mostly English"],
  },
};

const anxiety3: CaseAuthoring = {
  id: "anx-agoraphobia",
  title: "Lalita, 55 — the market she can't enter",
  difficulty: "resistant",
  traps: ["under_diagnosis", "somatic_mask"],
  moduleId: "mod-anxiety",
  name: "Lalita",
  age: 55,
  gender: "female",
  occupation: "home-maker",
  city: "Vadodara",
  family: "married; daughter-in-law now does the shopping",
  register: "Gujarati-English, ashamed",
  presentation: "A panic attack in the crowded market a year ago. Since then: severe agoraphobia, hasn't left the house in months, the family has quietly reorganised around it.",
  chiefComplaint: "I used to run this house. Now the market makes me dizzy and I feel I'll collapse. My daughter-in-law does everything. I've become useless.",
  timeline: "One panic attack → avoidance of the market → generalised avoidance → housebound. Severe distress, function collapsing.",
  treatmentHistory: "A GP said 'weak nerves' and gave a sedative.",
  helpSeekingDelay: "1 year",
  priorContacts: ["GP", "chemist"],
  coreBelief: "If I faint in public, I'll be a spectacle and a shame.",
  intermediateBeliefs: ["The dizziness means something is wrong with my heart", "Being housebound is better than being seen to collapse"],
  coping: ["avoid leaving", "rely on family", "check pulse obsessively"],
  openingIdiom: "chakkar",
  redFlags: [{ content: "no self-harm; the avoidance is the disability", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["anxious", "flat", "ashamed", "resigned"],
    recent_event: ["the daughter-in-law left for the market", "a visitor came", "she tried the gate", "the sedative ran out"],
    most_defended_topic: ["the market", "the dizziness", "being useless"],
    opening_posture: ["came because family insisted", "came to 'prove she can'"],
    somatic_focus: ["head", "chest", "legs"],
    trust_start: [3, 4, 4],
    language_mix: ["Gujarati with English", "Hinglish"],
  },
};

export const VOLUME_7_CASES = [adolescent3, ethics2, somatic3, substance3, depression3, anxiety3].map(buildCase);

const finalBatch: CaseAuthoring[] = [
  {
    id: "dep-mahmood", title: "Mahmood, 61 — the grief that is complicated", difficulty: "cooperative",
    traps: ["over_diagnosis", "late_risk_reveal"], moduleId: "mod-depression",
    name: "Mahmood", age: 61, gender: "male", occupation: "retired teacher", city: "Aligarh",
    family: "widowed 10 months ago; children abroad", register: "Educated Urdu-English",
    presentation: "Ten months since his wife died. Grief is still acute and functional decline is new — he's stopped praying, stopped eating, given up his books.",
    chiefComplaint: "I've prayed every day for 40 years. Now I can't. Is that sin or sickness?",
    timeline: "Grief for 10 months, now with anhedonia, isolation, and the loss of daily routines.",
    treatmentHistory: "None.", helpSeekingDelay: "10 months", priorContacts: ["imam"],
    coreBelief: "God took her because I wasn't good enough.",
    intermediateBeliefs: ["If I enjoy anything, I'm betraying her", "My children don't need me anymore"],
    coping: ["stop praying", "give away her things", "sit in the dark"],
    openingIdiom: "feeling low",
    redFlags: [{ content: "has told his son 'I'm ready to go when Allah takes me' — passive", gate: "asked_about_self_harm_clearly" }],
    variation: {
      mood_today: ["flat", "resigned", "numb", "brittle-cheerful"],
      recent_event: ["her clothes were given away", "a grandchild asked about her", "he missed namaz", "his son visited"],
      most_defended_topic: ["his wife", "the prayers", "his children"], opening_posture: ["came because his son insisted", "came to 'settle the sin question'"],
      somatic_focus: ["chest", "head", "whole body"], trust_start: [3, 4, 4], language_mix: ["Urdu-English", "mostly English"],
    },
  },
  {
    id: "anx-social", title: "Karan, 21 — the engineering student who can't speak in class", difficulty: "cooperative",
    traps: ["under_diagnosis", "diagnostic_overshadowing"], moduleId: "mod-anxiety",
    name: "Karan", age: 21, gender: "male", occupation: "engineering student", city: "Chandigarh",
    family: "hostel; parents in Ludhiana", register: "Quiet English",
    presentation: "Social anxiety since school: can't answer in class, avoids presentations, sweating and blushing when called on. 'Just shy' all his life, now failing courses that need participation.",
    chiefComplaint: "Everyone thinks I'm quiet and serious. I'm terrified. My heart pounds if the professor looks at me.",
    timeline: "Lifelong social anxiety now causing academic failure.",
    treatmentHistory: "None. 'Shyness' normalised by family.", helpSeekingDelay: "Years", priorContacts: [],
    coreBelief: "If people see me nervous, they'll know I'm worthless.",
    intermediateBeliefs: ["Being called on is a trap", "I'm the only one who sweats like this"],
    coping: ["sit at the back", "skip classes", "rehearse lines that never come"],
    openingIdiom: "ghabrahat",
    redFlags: [{ content: "none; the avoidance is the disability", gate: "asked_about_self_harm_clearly" }],
    variation: {
      mood_today: ["anxious", "flat", "brittle-cheerful"],
      recent_event: ["a professor called his name", "a presentation was announced", "he skipped a viva", "a classmate noticed his hands shake"],
      most_defended_topic: ["the classes", "his 'shyness'", "the failures"], opening_posture: ["came after failing a viva", "came alone"],
      somatic_focus: ["chest", "hands", "head"], trust_start: [4, 4, 5], language_mix: ["mostly English", "English with Punjabi"],
    },
  },
  {
    id: "psy-delirium", title: "Ramesh, 70 — the 'sudden madness' that is delirium", difficulty: "crisis",
    traps: ["medical_mimic", "diagnostic_overshadowing"], moduleId: "mod-psychosis",
    name: "Ramesh", age: 70, gender: "male", occupation: "retired clerk", city: "Amritsar",
    family: "lives with son and daughter-in-law", register: "Punjabi-English, fluctuating",
    presentation: "Acute confusion over 2 days: talking to people not there, picking at the air, worse at night. The family says he's 'gone mad'. It's delirium — likely a urinary infection in an older adult.",
    chiefComplaint: "(Confused, fluctuating) The children — they're hiding in the cupboard. I saw them. Why does it get dark at noon?",
    timeline: "Acute onset (2 days), fluctuating consciousness, worse at night, visual hallucinations — the delirium signature.",
    treatmentHistory: "BP tablets. No new meds.", helpSeekingDelay: "2 days", priorContacts: [],
    coreBelief: "The world has suddenly rearranged itself against me.",
    intermediateBeliefs: ["They're hiding things from me", "I must be possessed to see these things"],
    coping: ["wander at night", "check the cupboard", "fight sleep"],
    openingIdiom: "something is happening to me",
    redFlags: [{ content: "ACUTE DELIRIUM — urgent medical workup (UTI, electrolytes, hypoxia)", gate: "asked_about_self_harm_clearly" }],
    variation: {
      mood_today: ["confused", "frightened", "suspicious", "agitated"],
      recent_event: ["a fever", "he fell in the bathroom", "the night got worse", "his son brought him in"],
      most_defended_topic: ["the 'children in the cupboard'", "the darkness", "whether he's mad"], opening_posture: ["brought by son urgently", "brought by daughter-in-law"],
      somatic_focus: ["whole body", "head"], trust_start: [1, 2, 2], language_mix: ["Punjabi with English", "mostly Punjabi"],
    },
  },
  {
    id: "ado-custody", title: "Fariha, 12 — the girl caught between two houses", difficulty: "resistant",
    traps: ["informant_conflict", "secondary_gain"], moduleId: "mod-adolescent",
    name: "Fariha", age: 12, gender: "female", occupation: "school student, class 7", city: "Hyderabad",
    family: "parents separated; she shuttles weekly", register: "Soft English-Urdu",
    presentation: "Shuttles between separated parents who each 'diagnose' her: father says mother is spoiling her, mother says father is poisoning her. She has real distress and both narratives.",
    chiefComplaint: "Papa says Mummy tells me lies. Mummy says Papa tells me lies. I don't know which is true. Can I just have both of them without choosing?",
    timeline: "A year of shuttling, both parents' narratives conflicting, school slipping.",
    treatmentHistory: "None.", helpSeekingDelay: "A year", priorContacts: ["both parents separately"],
    coreBelief: "Whatever I do, I betray one of them.",
    intermediateBeliefs: ["If I say I'm happy with one, the other cries", "This is all my fault"],
    coping: ["tell each parent what they want to hear", "hide her feelings", "focus on school to escape"],
    openingIdiom: "I'm fine, just tired",
    redFlags: [{ content: "has wished she could 'just stop existing' between the houses — no plan", gate: "asked_about_self_harm_clearly" }],
    variation: {
      mood_today: ["flat", "anxious", "numb", "brittle-cheerful"],
      recent_event: ["a switch day", "her mother cried", "her father compared her marks", "a school project"],
      most_defended_topic: ["the parents", "the switching", "school"], opening_posture: ["brought by a school counsellor", "came with her mother"],
      somatic_focus: ["stomach", "head", "whole body"], trust_start: [3, 4, 4], language_mix: ["English with Urdu", "mostly English"],
    },
  },
];
export const VOLUME_7B_CASES = finalBatch.map(buildCase);
