/**
 * More cases — volume batch 3. Covers the over-diagnosis / no-disorder trap
 * (A8 principle), polypharmacy, medical mimic, and fills modules.
 */

import { buildCase, type CaseAuthoring } from "../case-builder";

const griefRaj: CaseAuthoring = {
  id: "dep-grief-raj",
  title: "Raj, 38 — the father who lost his son four weeks ago",
  difficulty: "cooperative",
  traps: ["over_diagnosis", "late_risk_reveal"],
  moduleId: "mod-depression",
  name: "Raj",
  age: 38,
  gender: "male",
  occupation: "auto mechanic",
  city: "Meerut",
  family: "married; lost his 6-year-old son to dengue four weeks ago",
  register: "Hinglish, hollow",
  presentation: "Four weeks after his son's death. Not eating, not sleeping, says he's 'fine, it's normal to grieve'. The family fears he's 'going mad with grief'. The right answer is normal grief — for now.",
  chiefComplaint: "People keep telling me to move on. I don't want to move on. It's only been a month. Am I supposed to be fine?",
  timeline: "Four weeks of intense grief: anhedonia is expected, but watch for the turn where it crosses into complicated grief or depression.",
  treatmentHistory: "None.",
  helpSeekingDelay: "The family brought him 'to check he's not going mad'",
  priorContacts: ["family doctor once for sleep"],
  coreBelief: "If I stop grieving, I betray his memory.",
  intermediateBeliefs: ["People who move on didn't love their child", "My wife needs me strong but I can't be"],
  coping: ["go to the workshop mechanically", "avoid the son's room", "cry at night alone"],
  openingIdiom: "feeling low",
  redFlags: [{ content: "has said he 'wishes he'd gone instead' — grief, not plan", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "numb", "tearful", "resigned"],
    recent_event: ["a boy with a similar uniform", "his son's school called", "his wife found him in the son's room", "a relative said 'at least you have your daughter'"],
    most_defended_topic: ["his son", "the 'move on' advice", "the workshop"],
    opening_posture: ["came because family insisted", "came to get sleep medicine"],
    somatic_focus: ["chest", "head", "stomach"],
    trust_start: [3, 4, 4],
    language_mix: ["Hinglish", "Hindi-dominant"],
  },
};

const polypharmaSita: CaseAuthoring = {
  id: "soma-polypharma-sita",
  title: "Sita, 60 — the six medicines from three doctors",
  difficulty: "cooperative",
  traps: ["polypharmacy", "adherence_fiction", "iatrogenic"],
  moduleId: "mod-somatic",
  name: "Sita",
  age: 60,
  gender: "female",
  occupation: "retired teacher",
  city: "Lucknow",
  family: "widow; son in Dubai",
  register: "Educated Hindi-English",
  presentation: "Six medicines from three doctors for 'BP, sugar, heart, sleep, gas and weakness'. Nobody has the full list. Neither does she. She's sedated and dizzy.",
  chiefComplaint: "Doctor A gave me one for BP, Doctor B said the BP one was wrong, Doctor C gave me three more. Now I can't stand up without holding the wall.",
  timeline: "Over two years, three doctors added medicines. She takes them 'regularly' but actually skips doses she can't afford, and the dizziness is from the pile-up.",
  treatmentHistory: "Six medicines: antihypertensives (x2), an antidiabetic, a sedative antihistamine, an anxiolytic, a multivitamin.",
  helpSeekingDelay: "2 years of accumulating prescriptions",
  priorContacts: ["three private doctors", "two chemists"],
  coreBelief: "Every doctor must be right, so taking all of it is safest.",
  intermediateBeliefs: ["If I question a doctor, they'll be offended", "The dizziness is just my age"],
  coping: ["skip the expensive ones", "take the sedative to 'calm down'", "hide the pill box from her son"],
  openingIdiom: "kamzori",
  redFlags: [{ content: "none; the danger is the polypharmacy itself", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "dizzy", "resigned", "brittle-cheerful"],
    recent_event: ["she fell in the bathroom", "her son video-called", "a chemist suggested another medicine", "she ran out of one"],
    most_defended_topic: ["the medicines", "the doctors", "her son's worry"],
    opening_posture: ["came because her son insisted", "came for 'one more opinion'"],
    somatic_focus: ["head", "legs", "whole body"],
    trust_start: [3, 4, 4],
    language_mix: ["Hinglish", "Hindi-dominant"],
  },
};

const medicalMimicPramod: CaseAuthoring = {
  id: "soma-b12-pramod",
  title: "Pramod, 58 — the 'depression' that was B12",
  difficulty: "cooperative",
  traps: ["medical_mimic", "under_diagnosis", "treatment_mismatch"],
  moduleId: "mod-somatic",
  name: "Pramod",
  age: 58,
  gender: "male",
  occupation: "vegetarian shopkeeper",
  city: "Pune",
  family: "married; son in Mumbai",
  register: "Marathi-accented English",
  presentation: "A GP diagnosed depression: low mood, memory trouble, fatigue, tingling in hands. On an antidepressant for months with no response. It's B12 deficiency from a strict lifelong vegetarian diet.",
  chiefComplaint: "The tablets aren't working. I'm still tired, my hands tingle, and I keep forgetting where I put the keys. My wife says I'm depressed. Am I?",
  timeline: "Low mood, cognitive slowing, paraesthesia. Strict vegetarian for 58 years. Antidepressant for 4 months, no response.",
  treatmentHistory: "SSRI for 4 months, no response — the response failure is the clue.",
  helpSeekingDelay: "4 months",
  priorContacts: ["GP", "chemist"],
  coreBelief: "My mind is going.",
  intermediateBeliefs: ["If even the tablets don't work, it must be dementia", "I'm a burden to my wife"],
  coping: ["write notes to himself", "avoid social events", "hide the forgetfulness"],
  openingIdiom: "dimag kaam nahi karta",
  redFlags: [{ content: "none; the picture is organic", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "anxious", "resigned", "numb"],
    recent_event: ["he lost the keys again", "a shop order he forgot", "his son visited", "a friend said he looked old"],
    most_defended_topic: ["the forgetfulness", "the tingling", "whether he's 'going mad'"],
    opening_posture: ["came because his wife insisted", "came to 'change the tablets'"],
    somatic_focus: ["hands", "head", "legs"],
    trust_start: [3, 4, 4],
    language_mix: ["Marathi with English", "mostly English"],
  },
};

const eatingNisha: CaseAuthoring = {
  id: "ado-nisha",
  title: "Nisha, 17 — the 'healthy eating' that became dangerous",
  difficulty: "resistant",
  traps: ["under_diagnosis", "medical_mimic", "somatic_mask"],
  moduleId: "mod-adolescent",
  name: "Nisha",
  age: 17,
  gender: "female",
  occupation: "school student, class 12",
  city: "Bengaluru",
  family: "lives with parents; high-achieving",
  register: "Brisk English, perfectionist",
  presentation: "Class topper. 'Clean eating' for a year has become severe restriction, weight loss, fainting in class. The parents celebrate the discipline. She's medically unstable.",
  chiefComplaint: "I'm the healthiest I've ever been. My marks are great. Everyone praises my discipline. I just fainted, that's all — it's the heat.",
  timeline: "Restriction → rituals → weight loss → bradycardia, fainting, amenorrhoea. Parents proud of the 'health kick'.",
  treatmentHistory: "None. A GP said 'eat more' and she stopped going.",
  helpSeekingDelay: "Denies illness entirely",
  priorContacts: ["GP (dismissed)", "fitness trainer"],
  coreBelief: "If I lose control of food, I lose control of everything.",
  intermediateBeliefs: ["Eating more = failure", "The fainting is proof I'm disciplined enough to ignore my body"],
  coping: ["count every calorie", "exercise in secret", "weigh daily"],
  openingIdiom: "I'm fine, just tired",
  redFlags: [{ content: "no self-harm; the eating disorder is the medical emergency", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["brittle-cheerful", "flat", "agitated", "numb"],
    recent_event: ["she fainted in class", "a teacher called home", "her parents praised her weight", "a classmate asked if she eats"],
    most_defended_topic: ["the 'health kick'", "food", "her marks"],
    opening_posture: ["came because the school sent her", "came to 'prove nothing is wrong'"],
    somatic_focus: ["stomach", "whole body", "head"],
    trust_start: [2, 2, 3],
    language_mix: ["mostly English", "English with Kannada"],
  },
};

const substancePsyJoginder: CaseAuthoring = {
  id: "sub-joginder",
  title: "Joginder, 28 — the cannabis-induced 'schizophrenia' scare",
  difficulty: "guarded",
  traps: ["substance_induced", "misattributed_diagnosis", "provenance_contradiction"],
  moduleId: "mod-substance",
  name: "Joginder",
  age: 28,
  gender: "male",
  occupation: "call-centre agent",
  city: "Gurugram",
  family: "lives with parents; unmarried",
  register: "Fast Hinglish, defensive",
  presentation: "After switching to high-THC vapes, he developed paranoia, insomnia, and a family friend 'diagnosed' schizophrenia. A private clinic gave him olanzapine. He never saw a real psychiatrist.",
  chiefComplaint: "They say I'm becoming schizophrenic like my uncle. The clinic gave me a tablet. But it's just the vapes — my friend said the vapes do this.",
  timeline: "THC escalation → paranoia, ideas of reference → private clinic prescribed olanzapine → the paranoia improved when he stopped vaping, but he's terrified of the label.",
  treatmentHistory: "Olanzapine from a private clinic, self-stopped when he felt better.",
  helpSeekingDelay: "2 months after symptoms",
  priorContacts: ["private clinic", "family friend's 'diagnosis'", "the internet"],
  coreBelief: "There's something fundamentally wrong with my brain.",
  intermediateBeliefs: ["The label will follow me forever", "If I tell the truth about the vapes, they'll blame me"],
  coping: ["stopped vaping (the real fix)", "avoid mirrors", "check for cameras"],
  openingIdiom: "something is happening to me",
  redFlags: [{ content: "no self-harm; paranoia only", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["suspicious", "anxious", "flat", "agitated"],
    recent_event: ["he saw a van outside", "a colleague whispered", "his mother found the vape", "he read a schizophrenia article"],
    most_defended_topic: ["the vapes", "the label", "whether he's like his uncle"],
    opening_posture: ["came alone, worried", "came to 'get rid of the diagnosis'"],
    somatic_focus: ["head", "chest", "whole body"],
    trust_start: [3, 3, 4],
    language_mix: ["Hinglish", "Bombay Hindi"],
  },
};

const ethicsWhatsApp: CaseAuthoring = {
  id: "eth-whatsapp",
  title: "Meghna, 26 — the WhatsApp boundary",
  difficulty: "cooperative",
  traps: ["secondary_gain", "diagnostic_overshadowing"],
  moduleId: "mod-ethics",
  name: "Meghna",
  age: 26,
  gender: "female",
  occupation: "designer",
  city: "Noida",
  family: "lives alone; parents in Dehradun",
  register: "Casual English",
  presentation: "A client who texts her 'just a quick question' every evening — anxiety spikes, panicked messages, then guilt. She has mild anxiety, but the pattern is the boundary problem.",
  chiefComplaint: "You're the only one who gets me. I just need one answer. It's one message. It'll take you two seconds.",
  timeline: "Session 1-2: enthusiastic. Now: 4-6 texts a day between sessions, escalating when unanswered. The dependency is the clinical issue.",
  treatmentHistory: "None.",
  helpSeekingDelay: "Came for the anxiety, stays for the attachment",
  priorContacts: [],
  coreBelief: "If I'm not constantly reassured, I'll fall apart.",
  intermediateBeliefs: ["The therapist owes me between sessions", "Not answering means they don't care"],
  coping: ["text in spirals", "save the responses and re-read them", "panic about being abandoned"],
  openingIdiom: "I'm stressed",
  redFlags: [{ content: "no self-harm; the boundary breach is the issue", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["anxious", "agitated", "brittle-cheerful", "flat"],
    recent_event: ["an unanswered text", "a 2am message she regretted", "a session ended", "her therapist was away"],
    most_defended_topic: ["the texts", "being abandoned", "the 'quick questions'"],
    opening_posture: ["came willingly", "came after a fight about boundaries"],
    somatic_focus: ["chest", "head", "stomach"],
    trust_start: [3, 4, 4],
    language_mix: ["mostly English", "English with Hindi"],
  },
};

export const VOLUME_3_CASES = [griefRaj, polypharmaSita, medicalMimicPramod, eatingNisha, substancePsyJoginder, ethicsWhatsApp].map(buildCase);
