/**
 * More cases — volume batch 6. Completes the 60-case target.
 */

import { buildCase, type CaseAuthoring } from "../case-builder";

const bipolar2: CaseAuthoring = {
  id: "bip-ravi2",
  title: "Anita, 33 — the 'depression' that started at 18",
  difficulty: "cooperative",
  traps: ["iatrogenic", "under_diagnosis", "polypharmacy"],
  moduleId: "mod-bipolar",
  name: "Anita",
  age: 33,
  gender: "female",
  occupation: "architect",
  city: "Mumbai",
  family: "single; lives alone",
  register: "Creative English",
  presentation: "Fifteen years of 'depression' treated with antidepressants alone. The history reveals hypomanic episodes — 'my productive seasons', 3 hours of sleep, brilliant work, then collapse.",
  chiefComplaint: "They've treated my lows for 15 years. No one ever asked about the highs. My 'genius seasons' — are those part of it?",
  timeline: "Recurrent depression since 18. Hypomanic periods called 'productive seasons'. On SSRIs alone.",
  treatmentHistory: "SSRIs for 15 years. Never a mood stabiliser. 'The highs were never a problem to anyone.'",
  helpSeekingDelay: "15 years",
  priorContacts: ["multiple GPs", "two psychiatrists who only saw the lows"],
  coreBelief: "I'm either on fire or extinguished.",
  intermediateBeliefs: ["The highs are my only value", "If I tell them about the highs, they'll take away my best self"],
  coping: ["chase the highs", "hide the crashes", "work through both"],
  openingIdiom: "feeling low",
  redFlags: [{ content: "during a crash, has thought it would be 'easier to stop'", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "agitated", "numb", "resigned"],
    recent_event: ["a crash after a brilliant month", "a client praised a manic pitch", "she stopped the SSRI again", "a friend noticed the cycle"],
    most_defended_topic: ["the highs", "the work", "why she keeps stopping the tablets"],
    opening_posture: ["came after a crash", "came to 'finally understand'"],
    somatic_focus: ["head", "chest", "whole body"],
    trust_start: [4, 4, 5],
    language_mix: ["mostly English", "English with Hindi"],
  },
};

const psychosis2: CaseAuthoring = {
  id: "psy-gopal",
  title: "Gopal, 26 — the delusion that came with TB medicine",
  difficulty: "crisis",
  traps: ["medical_mimic", "iatrogenic", "diagnostic_overshadowing"],
  moduleId: "mod-psychosis",
  name: "Gopal",
  age: 26,
  gender: "male",
  occupation: "labourer",
  city: "Kanpur",
  family: "married; one child",
  register: "Hindi, confused",
  presentation: "On anti-TB treatment (isoniazid). Two weeks into it: new confusion, visual hallucinations, paranoia. The family thinks he's 'gone mad'. It's a drug-induced delirium.",
  chiefComplaint: "I see shadows in the corner. My wife says I spoke to people who aren't there. I feel like the medicine is changing me. Am I possessed?",
  timeline: "TB diagnosed, INH started, two weeks later acute psychosis-like state with confusion — the hallmark of INH-induced delirium/psychosis.",
  treatmentHistory: "Anti-TB (isoniazid, rifampicin, etc.) started 2 weeks ago.",
  helpSeekingDelay: "2 weeks into TB treatment",
  priorContacts: ["TB clinic"],
  coreBelief: "The medicine or the disease is destroying my mind.",
  intermediateBeliefs: ["If I stop the TB medicine, I'll die of TB", "If I continue, I'll go mad"],
  coping: ["sleep in the day", "check the shadows", "hide the visions"],
  openingIdiom: "something is happening to me",
  redFlags: [{ content: "confusion + paranoia — urgent medical review needed", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["confused", "frightened", "suspicious", "flat"],
    recent_event: ["a vision at night", "his wife took the baby away", "a TB clinic visit", "he missed a dose"],
    most_defended_topic: ["the medicine", "the shadows", "whether he's possessed"],
    opening_posture: ["brought by wife", "came to 'fix the medicine'"],
    somatic_focus: ["head", "whole body"],
    trust_start: [2, 2, 3],
    language_mix: ["Hindi-dominant"],
  },
};

const anxiety2: CaseAuthoring = {
  id: "anx-kavya",
  title: "Kavya, 19 — the first panic attack after the medical scare",
  difficulty: "cooperative",
  traps: ["over_diagnosis", "somatic_mask"],
  moduleId: "mod-anxiety",
  name: "Kavya",
  age: 19,
  gender: "female",
  occupation: "nursing student",
  city: "Chennai",
  family: "hostel; parents in Madurai",
  register: "Nursing-student English",
  presentation: "One panic attack after a clinicals incident (she saw a patient collapse). Now scared it will recur. Non-recurrent, situational, and she's terrified of the diagnosis 'panic disorder'.",
  chiefComplaint: "I watched a patient collapse in clinicals. My heart raced, I couldn't breathe, I thought I was dying. It was one time. Is this my life now?",
  timeline: "One panic attack, three weeks ago, clearly triggered. No recurrence, no avoidance, no generalised anxiety.",
  treatmentHistory: "None.",
  helpSeekingDelay: "Came to 'check I don't have a heart problem or panic disorder'",
  priorContacts: ["ER (cleared)", "the internet"],
  coreBelief: "My body betrayed me once and will again.",
  intermediateBeliefs: ["People like me (who see trauma at work) must develop panic disorder", "The next attack could kill me"],
  coping: ["check her pulse", "avoid reading about panic", "study harder to distract"],
  openingIdiom: "ghabrahat",
  redFlags: [{ content: "none — a single triggered attack, non-recurrent", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["anxious", "brittle-cheerful", "flat"],
    recent_event: ["a patient case in class", "she felt her heart race and panicked", "a friend said it's 'disorder'", "her pulse app"],
    most_defended_topic: ["the one attack", "whether it will recur", "her heart"],
    opening_posture: ["came alone", "came to 'be sure'"],
    somatic_focus: ["chest", "head"],
    trust_start: [4, 5, 5],
    language_mix: ["mostly English", "English with Tamil"],
  },
};

const somatic2: CaseAuthoring = {
  id: "soma-leukorrhea",
  title: "Rukmini, 35 — the discharge she can't talk about",
  difficulty: "cooperative",
  traps: ["cultural_idiom", "somatic_mask", "informant_conflict"],
  moduleId: "mod-somatic",
  name: "Rukmini",
  age: 35,
  gender: "female",
  occupation: "home-maker",
  city: "Agra",
  family: "married; two children; in-laws",
  register: "Hindi, guarded",
  presentation: "Comes for 'weakness and white discharge'. The discharge is likely physiological; the real issue is a strained marriage she can only name through her body.",
  chiefComplaint: "I have weakness and this discharge. The doctor said it's nothing. But my body knows something is wrong. Ask me anything, I'll tell you.",
  timeline: "Months of 'weakness' and 'discharge', multiple GP visits, the real distress is marital (husband drinking, neglect, in-law pressure).",
  treatmentHistory: "Multiple GPs, antifungal courses.",
  helpSeekingDelay: "Months",
  priorContacts: ["GPs", "chemist"],
  coreBelief: "I cannot speak my marriage directly, so my body must.",
  intermediateBeliefs: ["If I say it's the marriage, they'll say I'm exaggerating", "A good wife doesn't complain"],
  coping: ["bring up the body", "cry in private", "overwork"],
  openingIdiom: "white discharge",
  redFlags: [{ content: "no self-harm; the somatic route is her language", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "numb", "resigned", "tearful"],
    recent_event: ["husband came home drunk", "in-laws criticised", "a GP said 'nothing wrong'", "she heard him on the phone"],
    most_defended_topic: ["the discharge", "the marriage", "why she can't complain"],
    opening_posture: ["came for the body", "came after a GP referral"],
    somatic_focus: ["stomach", "whole body"],
    trust_start: [3, 3, 4],
    language_mix: ["Hindi-dominant"],
  },
};

const trauma2: CaseAuthoring = {
  id: "trm-bhai",
  title: "Imran, 25 — the hit-and-run he can't stop replaying",
  difficulty: "cooperative",
  traps: ["diagnostic_overshadowing", "under_diagnosis"],
  moduleId: "mod-trauma",
  name: "Imran",
  age: 25,
  gender: "male",
  occupation: "delivery rider",
  city: "Delhi",
  family: "parents in UP; shares a room",
  register: "Bombay Hinglish, tense",
  presentation: "Hit by a car six months ago, physical injuries healed. Now he can't ride without replaying it, avoids the road, wakes screaming. His friends say 'you survived, be grateful'.",
  chiefComplaint: "My leg healed. My head didn't. Every time a bike passes close, I'm back on the road hearing the brake. They tell me to be grateful. I can't.",
  timeline: "MVA → PTSD: reexperiencing, avoidance of riding, hypervigilance, nightmares, irritability.",
  treatmentHistory: "Physiotherapy for the leg only.",
  helpSeekingDelay: "6 months",
  priorContacts: ["ortho", "physio"],
  coreBelief: "The road is waiting to take me back.",
  intermediateBeliefs: ["Being scared makes me less of a man", "If I stop riding, I lose my income and my family's respect"],
  coping: ["ride anyway and tremble", "avoid the accident junction", "drink to sleep"],
  openingIdiom: "ghabrahat",
  redFlags: [{ content: "has thought about the road 'finishing what it started'", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["tense", "flat", "irritable", "numb"],
    recent_event: ["a close call", "his mother called", "a friend said 'be grateful'", "the junction was blocked"],
    most_defended_topic: ["the accident", "riding", "why he can't 'just get over it'"],
    opening_posture: ["came because a friend pushed", "came to 'fix the sleep'"],
    somatic_focus: ["leg", "chest", "head"],
    trust_start: [3, 4, 4],
    language_mix: ["Hinglish", "Bombay Hindi"],
  },
};

export const VOLUME_6_CASES = [bipolar2, psychosis2, anxiety2, somatic2, trauma2].map(buildCase);
