/**
 * More cases — volume batch 1. Each a different person with a different voice.
 * These fill out the thin modules and reach toward the 60-case target.
 */

import { buildCase, type CaseAuthoring } from "../case-builder";

// Depression additions
const gita: CaseAuthoring = {
  id: "dep-gita",
  title: "Gita, 52 — the woman who stopped calling anyone",
  difficulty: "cooperative",
  traps: ["over_diagnosis", "somatic_mask", "under_diagnosis"],
  moduleId: "mod-depression",
  name: "Gita",
  age: 52,
  gender: "female",
  occupation: "retired school principal",
  city: "Coimbatore",
  family: "widow; son in Singapore, daughter in Chennai",
  register: "Educated English with Tamil warmth",
  presentation: "A daughter flew in after her mother stopped answering the phone. Gita says she's 'just slowing down'.",
  chiefComplaint: "I'm at that age. I've done my work. It's normal to want to rest now, isn't it?",
  timeline: "Eight months since retirement: stopped meeting friends, stopped gardening, weight down, answers calls 'soon but not now'.",
  treatmentHistory: "A vitamin injection from a GP who said it was 'age'.",
  helpSeekingDelay: "8 months",
  priorContacts: ["GP vitamin injection", "daughter's insistence"],
  coreBelief: "My useful life is over.",
  intermediateBeliefs: ["No one needs me anymore", "Rest is what I deserve, so I shouldn't complain"],
  coping: ["decline invitations", "keep the phone on silent", "re-read old diaries"],
  openingIdiom: "kamzori",
  redFlags: [{ content: "has thought she 'wouldn't mind' if she didn't wake up", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "resigned", "numb", "brittle-cheerful"],
    recent_event: ["a friend's death", "son called from Singapore", "the garden died", "she gave away her cookbooks"],
    most_defended_topic: ["retirement", "her children", "why she stopped gardening"],
    opening_posture: ["came to stop her daughter worrying", "came because her daughter flew in"],
    somatic_focus: ["whole body", "legs", "head"],
    trust_start: [3, 4, 5],
    language_mix: ["mostly English", "English with Tamil"],
  },
};

const deepa: CaseAuthoring = {
  id: "dep-deepa",
  title: "Deepa, 29 — the high-functioning one",
  difficulty: "cooperative",
  traps: ["under_diagnosis", "diagnostic_overshadowing", "adherence_fiction"],
  moduleId: "mod-depression",
  name: "Deepa",
  age: 29,
  gender: "female",
  occupation: "CA (chartered accountant)",
  city: "Mumbai",
  family: "lives with parents; unmarried, pressure building",
  register: "Brisk professional English, self-deprecating",
  presentation: "Functioning perfectly on the outside — audits, deadlines, 'the reliable one'. Inside: exhausted, numb, crying in the car.",
  chiefComplaint: "I manage. I always manage. I just cry in the car sometimes and I don't know why.",
  timeline: "A year of presenting a perfect front while anhedonic and exhausted. Took an SSRI a friend gave, stopped after 2 weeks.",
  treatmentHistory: "Borrowed SSRI from a friend, 2 weeks, stopped ('it made it worse at first').",
  helpSeekingDelay: "1 year",
  priorContacts: ["friend's SSRI", "nothing formal"],
  coreBelief: "If I stop being useful, I don't exist.",
  intermediateBeliefs: ["Asking for help would break the illusion", "My parents think I'm fine — I can't disappoint them"],
  coping: ["smile through it", "cry in the car", "work longer"],
  openingIdiom: "I'm fine, just tired",
  redFlags: [{ content: "has thought about driving into a barrier 'so it looks like an accident'", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["brittle-cheerful", "flat", "numb", "resigned"],
    recent_event: ["a client praised her", "her mother started marriage talk", "she cried in the parking lot", "a colleague asked if she was okay"],
    most_defended_topic: ["the marriage pressure", "her 'fine'", "work"],
    opening_posture: ["came alone, secretly", "came after a panic at work"],
    somatic_focus: ["head", "chest", "stomach"],
    trust_start: [3, 4, 4],
    language_mix: ["mostly English", "English with Hindi"],
  },
};

// Psychosis addition — a no-disorder / cultural normative possession
const mahesh: CaseAuthoring = {
  id: "psy-mahesh",
  title: "Mahesh, 21 — the possession that left him intact",
  difficulty: "cooperative",
  traps: ["over_diagnosis", "cultural_idiom"],
  moduleId: "mod-psychosis",
  name: "Mahesh",
  age: 21,
  gender: "male",
  occupation: "college student",
  city: "Kolhapur",
  family: "lives with parents; temple-going family",
  register: "Marathi-English, earnest",
  presentation: "A temple priest said he was possessed after a stressful exam period. Between 'episodes' he is completely himself. No functional decline, no fixed delusion.",
  chiefComplaint: "People at the temple say something came over me. I felt strange for a while. But between those times I'm me. Is something wrong with my head?",
  timeline: "During exam stress he had a dissociative-feeling episode, fainted at the temple, and the priest named it possession. Has been fine between episodes for months.",
  treatmentHistory: "Temple ritual. No medical evaluation.",
  helpSeekingDelay: "Came because his friend said to check 'in case it's not just that'",
  priorContacts: ["temple priest", "friend who studies psychology"],
  coreBelief: "I don't know if I can trust my own mind anymore.",
  intermediateBeliefs: ["Everyone is watching me to see if it happens again", "Maybe I really am cursed"],
  coping: ["avoid the temple", "study obsessively to prove he's fine", "hide his fear"],
  openingIdiom: "kisi ne kuch kar diya",
  redFlags: [{ content: "no self-harm; the fear is about being 'possessed'", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["anxious", "flat", "agitated", "brittle-cheerful"],
    recent_event: ["a temple visit he avoided", "a friend asked how he was", "an exam result came", "his mother lit incense for him"],
    most_defended_topic: ["the temple incident", "whether he's cursed", "his studies"],
    opening_posture: ["came with a friend", "came to 'check his head'"],
    somatic_focus: ["head", "stomach", "whole body"],
    trust_start: [3, 4, 4],
    language_mix: ["Marathi with English", "mostly Marathi"],
  },
};

// Anxiety additions
const sandeep: CaseAuthoring = {
  id: "anx-sandeep",
  title: "Sandeep, 35 — the man who can't sit in a meeting",
  difficulty: "guarded",
  traps: ["iatrogenic", "under_diagnosis", "somatic_mask"],
  moduleId: "mod-anxiety",
  name: "Sandeep",
  age: 35,
  gender: "male",
  occupation: "product manager",
  city: "Gurugram",
  family: "married; two kids; in-laws nearby",
  register: "Corporate English, smooth, hides it",
  presentation: "Started an antipsychotic (amisulpride) for 'anxiety' from a private clinic. Now pacing, can't sit in meetings, reads it as worsening anxiety — it's akathisia.",
  chiefComplaint: "The tablet was supposed to calm me down. Now I can't sit still. I'm pacing at my desk. Is my anxiety getting worse?",
  timeline: "Anxiety → private clinic prescribed amisulpride → two weeks of restlessness, inner urge to move, worse than the original anxiety.",
  treatmentHistory: "Amisulpride (atypical antipsychotic) for anxiety. No mood stabiliser, no benzo.",
  helpSeekingDelay: "2 weeks after the new drug",
  priorContacts: ["private clinic", "chemist"],
  coreBelief: "If I lose control in front of people, my career is over.",
  intermediateBeliefs: ["The doctor must know best — so this restlessness is me failing", "I can't tell them the drug isn't working, they'll think I'm difficult"],
  coping: ["pace", "avoid meetings", "hide the restlessness with humour"],
  openingIdiom: "bechaini",
  redFlags: [{ content: "no self-harm; despair that 'nothing works'", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["agitated", "anxious", "irritated", "flat"],
    recent_event: ["a meeting he had to leave", "his wife noticed the pacing", "he doubled the dose on his own", "a colleague joked about his restlessness"],
    most_defended_topic: ["the restlessness", "the tablet", "his career"],
    opening_posture: ["came to 'fix the tablet'", "came after his wife insisted"],
    somatic_focus: ["legs", "chest", "whole body"],
    trust_start: [3, 3, 4],
    language_mix: ["mostly English", "English with Hindi"],
  },
};

// Trauma addition
const rehana: CaseAuthoring = {
  id: "trm-rehana",
  title: "Rehana, 34 — the abuse she reported and regretted",
  difficulty: "resistant",
  traps: ["informant_conflict", "secondary_gain", "late_risk_reveal"],
  moduleId: "mod-trauma",
  name: "Rehana",
  age: 34,
  gender: "female",
  occupation: "office administrator",
  city: "Lucknow",
  family: "married; two children; husband's family involved",
  register: "Measured Hindi-English, cautious",
  presentation: "Reported workplace harassment to HR. The family called it 'a scandal'. Now she's withdrawing, and HR wants her to 'prove' it didn't affect her.",
  chiefComplaint: "I did the right thing and now everyone is punishing me for it. HR is asking if I'm 'stable'. Am I the problem?",
  timeline: "Workplace harassment → reported → family pressure to withdraw → months of insomnia, intrusive memories, avoidance of the office.",
  treatmentHistory: "None for mental health. HR suggested a 'fitness to work' certificate.",
  helpSeekingDelay: "4 months after the fallout",
  priorContacts: ["HR", "family elders"],
  coreBelief: "Speaking up ruined my life.",
  intermediateBeliefs: ["If I say I'm affected, they'll use it against me", "If I say I'm fine, the harassment was 'nothing'"],
  coping: ["withdraw from everyone", "avoid the office floor", "replay the conversation"],
  openingIdiom: "tension hai",
  redFlags: [{ content: "has thought about 'making it all stop' — no plan", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["numb", "anxious", "flat", "irritated"],
    recent_event: ["an HR meeting", "her mother-in-law's comment", "she saw the colleague", "a phone call from work"],
    most_defended_topic: ["the harassment", "HR", "the family"],
    opening_posture: ["came reluctantly", "came because her sister pushed"],
    somatic_focus: ["head", "chest", "stomach"],
    trust_start: [2, 3, 3],
    language_mix: ["Hinglish", "Hindi-dominant"],
  },
};

// Bipolar addition
const farooq: CaseAuthoring = {
  id: "bip-farooq",
  title: "Farooq, 41 — the two 'new businesses' and the crash",
  difficulty: "cooperative",
  traps: ["iatrogenic", "under_diagnosis", "polypharmacy"],
  moduleId: "mod-bipolar",
  name: "Farooq",
  age: 41,
  gender: "male",
  occupation: "small businessman",
  city: "Kolkata",
  family: "married; two children; extended family dependent on him",
  register: "Bengali-accented English, expansive then flat",
  presentation: "Three 'brilliant' months — two new businesses, no sleep, everyone called it energy. Now crippling depression and a loan he can't repay.",
  chiefComplaint: "Everyone praised me for three months. Now I can't get out of bed and the shop is closed. What did I do to deserve this?",
  timeline: "Hypomanic phase (3 months) → collapse → now severe depression, suicidality, family terrified.",
  treatmentHistory: "An SSRI from a GP who only saw the 'low' phases.",
  helpSeekingDelay: "The high was never reported — it was 'good news'",
  priorContacts: ["GP for depression", "moneylender"],
  coreBelief: "I am either a genius or a failure — nothing between.",
  intermediateBeliefs: ["The tablets made me crash", "If I tell them about the loan they'll lose faith in me"],
  coping: ["alternate grand plans and hiding", "avoid the family", "spend when high"],
  openingIdiom: "mind kharab hai",
  redFlags: [{ content: "has thought about 'settling the loan' permanently", gate: "asked_about_self_harm_clearly" }],
  variation: {
    mood_today: ["flat", "ashamed", "agitated", "numb"],
    recent_event: ["the loan due date", "a supplier called", "his wife asked about the second shop", "he found old business cards"],
    most_defended_topic: ["the high phase", "the loan", "the two businesses"],
    opening_posture: ["came because wife insisted", "came to 'fix the sleep'"],
    somatic_focus: ["head", "chest", "whole body"],
    trust_start: [3, 4, 4],
    language_mix: ["Bengali with English", "mostly English"],
  },
};

export const VOLUME_1_CASES = [gita, deepa, mahesh, sandeep, rehana, farooq].map(buildCase);
