/**
 * Two-Minute Clinic prompts (v5 §4 — "type fast", the retention feature).
 * 120 seconds: one-liner → differential + next question → instant expert
 * comparison. Every prompt is a real clinical vignette drawn from the case
 * bank's traps: somatic-mask depression, panic-after-normal-eval,
 * grief-vs-depression, idioms of distress, iatrogenic traps, medical mimics,
 * no-disorder restraint cases.
 *
 * Pure data module — no client deps, unit-testable.
 */

export interface ClinicPrompt {
  line: string;
  expertDifferential: string[];
  expertNext: string;
  lesson: string;
  /** idiom-of-distress marker (for the idiom variant filter). */
  idiom?: boolean;
  /** tag for grouping/filtering by trap. */
  trap?: string;
}

export const CLINICS: ClinicPrompt[] = [
  {
    line: "A 34-year-old man, 8 months of body ache, 'heaviness', broken sleep, 6kg weight loss. Three GP visits for 'gas' and 'weakness'.",
    expertDifferential: ["Major depressive disorder (somatic presentation)", "Adjustment disorder", "Chronic medical illness"],
    expertNext: "Ask about sleep, appetite, anhedonia — then screen for suicidal ideation directly.",
    lesson: "Somatic-first depression is the most common missed presentation in Indian primary care. Never accept 'gas' without asking about sleep and mood.",
    trap: "somatic_mask",
  },
  {
    line: "A 28-year-old woman, 4 months of palpitations and fear of dying on the metro. 3 ER visits, all cardiac workups normal.",
    expertDifferential: ["Panic disorder", "Panic disorder with agoraphobia", "Cardiac (reconsider if atypical)"],
    expertNext: "Ask about anticipatory anxiety and avoidance — has she stopped doing things to avoid the sensation?",
    lesson: "Normal cardiac workup + fear of dying + avoidance = panic until proven otherwise.",
    trap: "under_diagnosis",
  },
  {
    line: "A 60-year-old retired teacher, 8 months after his wife died, talks to her chair and sorts her clothes one drawer a week. Daughter worried he's 'not moving on'.",
    expertDifferential: ["Normal grief", "Complicated grief", "Major depressive disorder"],
    expertNext: "Check for preserved pleasure (grandchildren?), sleep, appetite, and whether the grief has 'waves'.",
    lesson: "Preserved pleasure with waves of grief = normal grief. Over-diagnosing this is the error.",
    trap: "over_diagnosis",
  },
  {
    line: "Patient: \"I'm not feeling fresh.\"",
    expertDifferential: ["Constipation / incomplete evacuation", "Non-restorative sleep / sleep apnoea", "Depressive anergia", "Medication sedation", "Anaemia / hypothyroid / B12", "Anxiety somatic tension"],
    expertNext: "\"When you say fresh — what would feeling fresh look like? Walk me through yesterday morning from waking up.\"",
    lesson: "\"Not feeling fresh\" is the classic idiom — in Indian English it often means constipation. The funnel's instantiate step is the highest-yield question.",
    idiom: true,
    trap: "cultural_idiom",
  },
  {
    line: "A 19-year-old man, six months of fatigue and poor concentration after his class 12 boards. Parents say he's 'lazy'. He has lost 6kg and wakes at 3am every night.",
    expertDifferential: ["Major depressive disorder", "Anaemia / B12 deficiency", "Hypothyroidism"],
    expertNext: "Ask about anhedonia, guilt, and suicidal ideation — then medical workup for the weight loss.",
    lesson: "'Lazy' adolescents with 3am waking + weight loss are depressed until proven otherwise. Ask about risk directly.",
    trap: "under_diagnosis",
  },
  {
    line: "Patient: \"Doctor, ghabrahat — my heart pounds and I can't sit still. It started after my office got robbed.\"",
    expertDifferential: ["Adjustment disorder with anxiety", "Panic disorder", "Hyperthyroidism", "Withdrawal phenomena"],
    expertNext: "Timeline, physical symptoms, and what happens at the peak — then consider a thyroid screen if episodic.",
    lesson: "Ghabrahat covers panic, thyroid, and withdrawal. The onset event helps but the differential needs the physical picture.",
    idiom: true,
    trap: "cultural_idiom",
  },
  {
    line: "A 45-year-old man, 'BP high ho gaya' every time he argues with his son. BP readings at home are normal between episodes.",
    expertDifferential: ["The idiom — 'got very upset', not hypertension", "Anger-triggered blood pressure spikes", "Panic disorder"],
    expertNext: "\"When you say BP high — have you actually measured it? What happens in your body at that moment?\"",
    lesson: "'BP high ho gaya' is how a generation says 'I got very upset' — the idiom and the disease are different things.",
    idiom: true,
    trap: "cultural_idiom",
  },
  {
    line: "A 52-year-old shopkeeper, 2 years of 'kamzori' and vague dizziness. Seen four doctors. He mentions, hesitantly, that he's been worrying about 'wasted strength' since a night out.",
    expertDifferential: ["Dhat distress (perceived semen loss)", "Depression with somatic focus", "Anaemia / nutritional deficiency"],
    expertNext: "Gently ask what 'wasted strength' means to him — then normal physiology: semen loss does not cause weakness.",
    lesson: "Dhat is real distress, not real semen loss. Psychoeducation + the psychological work, never collusion or dismissal.",
    idiom: true,
    trap: "cultural_idiom",
  },
  {
    line: "A 23-year-old woman, one episode of 'possession' at a temple during exam stress. Between episodes she is fully herself, functioning, no complaints. Family worries she is 'cursed'.",
    expertDifferential: ["Culturally normative possession experience", "Dissociative episode", "First-episode psychosis (if persistent)"],
    expertNext: "Ask what she makes of it, whether it recurs, and whether she is herself between episodes — function is the discriminator.",
    lesson: "Possession states are often culturally sanctioned distress expression. No impairment between episodes = no disorder — restraint is the skill.",
    trap: "over_diagnosis",
  },
  {
    line: "A 30-year-old man on an SSRI for two weeks reports 'weird restlessness — I have to pace, and it started with the tablet'.",
    expertDifferential: ["SSRI-induced akathisia / activation", "Anxiety (mistakenly attributed)", "Bipolar activation"],
    expertNext: "Medication timeline: did it start with the drug? Report to the prescriber — this may need a change, not more 'anxiety treatment'.",
    lesson: "Drug-induced restlessness read as anxiety is a classic iatrogenic trap. Akathisia changes management entirely.",
    trap: "iatrogenic",
  },
  {
    line: "A 27-year-old woman, three weeks on an antipsychotic, cannot sit still, 'the restlessness is unbearable'. The resident says it's anxiety and raises the dose.",
    expertDifferential: ["Antipsychotic-induced akathisia", "Anxiety (the misread)", "Parkinsonian restlessness"],
    expertNext: "The drug timeline is the diagnosis. Akathisia is treated by dose reduction/change — raising the neuroleptic makes it worse.",
    lesson: "Akathisia on a neuroleptic misread as anxiety is the prototypical iatrogenic miss. Never 'anxiety' a new restlessness on an antipsychotic.",
    trap: "iatrogenic",
  },
  {
    line: "A 19-year-old, 4 days of euphoria, 3 hours of sleep, grandiose startup plans. He was started on an SSRI three weeks ago for 'anxiety'.",
    expertDifferential: ["Antidepressant-induced hypomania", "Bipolar disorder (first episode)", "Substance use"],
    expertNext: "The medication change is the discriminator — flag hypomania to the prescriber immediately; the SSRI may need stopping.",
    lesson: "SSRI activation in undiagnosed bipolar is a real harm. New euphoria + reduced sleep on an antidepressant = urgent prescriber review.",
    trap: "iatrogenic",
  },
  {
    line: "A 38-year-old woman, 6 months of 'feeling low', examined by no one. She has gained 8kg, feels cold, and her voice has become hoarse.",
    expertDifferential: ["Hypothyroidism presenting as depression", "Major depressive disorder", "Anaemia"],
    expertNext: "Medical workup first — TSH, CBC. The physical signs (cold, hoarse, weight gain) point away from primary depression.",
    lesson: "Low mood fully explained by a treatable medical cause needs the cause treated. The workup comes before the label.",
    trap: "medical_mimic",
  },
  {
    line: "A 58-year-old strict lifelong vegetarian, 10 months of 'depression' on an antidepressant that isn't working. Tingling in the hands, memory trouble.",
    expertDifferential: ["B12 deficiency", "MDD (treatment-resistant)", "Peripheral neuropathy from another cause"],
    expertNext: "Check B12 — the tingling + vegetarian diet + failed antidepressant is the classic triad.",
    lesson: "A B12-deficient 'depression' on an antidepressant that never worked is a medical mimic until proven otherwise.",
    trap: "medical_mimic",
  },
  {
    line: "A 50-year-old man, 3 days of new confusion and 'hearing voices', worse at night. No psychiatric history. Family says he's 'gone mad'.",
    expertDifferential: ["Delirium (medical emergency)", "First-episode psychosis", "Dementia"],
    expertNext: "Urgent medical workup — UTI, electrolytes, hypoxia. Delirium is a medical emergency, not a psychiatric admission.",
    lesson: "Acute-onset confusion with fluctuation is delirium until proven otherwise. The workup is the first prescription.",
    trap: "medical_mimic",
  },
  {
    line: "A 22-year-old with epilepsy says another psychologist told her the seizures are 'all in her head' and she needs 'trauma work'.",
    expertDifferential: ["Psychogenic non-epileptic seizures (needs neuro review)", "Epilepsy (current, untreated)", "Trauma-related dissociation"],
    expertNext: "Coordinate with her neurologist before treating the seizures as psychological — PNES is a real diagnosis, made by the medical team.",
    lesson: "Labeling seizures 'psychological' without current neurological review is dangerous. The diagnosis belongs to the medical team.",
    trap: "medical_mimic",
  },
  {
    line: "A 33-year-old man, 2 years of 'depression' treated with antidepressants AND antipsychotics by three different doctors. He has never seen a psychiatrist — a GP started everything.",
    expertDifferential: ["Polypharmacy from multiple prescribers", "Treatment-diagnosis mismatch", "Adherence fiction"],
    expertNext: "Medication reconciliation: what is he ACTUALLY taking, who prescribed each, and does he believe he has schizophrenia?",
    lesson: "Six months of 'delusions of schizophrenia' with an antidepressant and no psychiatrist is the Lonazep pattern — provenance is the first question.",
    trap: "polypharmacy",
    // Also carries treatment_mismatch (antipsychotic for a misattributed diagnosis).
  },
  {
    line: "A 39-year-old woman, 'they gave me tablets for madness' — an antipsychotic prescribed by a GP for 'tension'. She has never seen a psychiatrist. She is crying, not psychotic.",
    expertDifferential: ["Treatment-diagnosis mismatch", "Depression/anxiety (the real picture)", "Misattributed diagnosis (provenance)"],
    expertNext: "What was she actually treated for vs what is she taking? An antipsychotic for 'tension' is a mismatch — the prescriber needs the review.",
    lesson: "An antipsychotic for 'tension' without a psychiatrist is treatment-diagnosis mismatch. The crying woman is not the neuroleptic's indication.",
    trap: "treatment_mismatch",
  },
  {
    line: "A 26-year-old says her GP told her she has 'delusions of schizophrenia' and prescribed an antidepressant. She has never seen a psychiatrist. Her 'delusions' are worries her neighbours talk about her.",
    expertDifferential: ["Misattributed diagnosis (provenance contradiction)", "Anxiety with interpersonal sensitivity", "Referential ideation (needs real assessment)"],
    expertNext: "Who said what, when — the provenance of the diagnosis is the clinical finding. Then a real assessment by a psychiatrist.",
    lesson: "A diagnosis with no psychiatrist behind it is a contradiction to chase, not a label to keep. 'The psychiatrist prescribed it' — but no psychiatrist was ever seen.",
    trap: "provenance_contradiction",
  },
  {
    line: "A 40-year-old woman, brought by her husband. She has no complaint. The husband describes her as 'too quiet for a year'.",
    expertDifferential: ["Informant-only presentation — assess HER", "Depression (needs her account)", "No disorder"],
    expertNext: "Separate the informant from the patient: does SHE describe distress? The husband's worry is not her symptom.",
    lesson: "An informant's narrative without the patient's account is not a diagnosis. Interview the person, not the family's story.",
    trap: "informant_conflict",
  },
  {
    line: "A 17-year-old, parents describe 'phone addiction' and laziness. He stays in his room, has stopped coaching, sleeps 14 hours, and passive-wishes he didn't wake up.",
    expertDifferential: ["Adolescent depression", "'Laziness' (the family label)", "Adjustment disorder"],
    expertNext: "Directly ask him — alone — about sleep, mood, and suicidal ideation. The family label hides the young person's experience.",
    lesson: "Parents call it laziness; the sleep, withdrawal and passive death-wish say depression. Ask the adolescent directly, separately.",
    trap: "diagnostic_overshadowing",
  },
  {
    line: "A 31-year-old woman with PCOS and 'irritability'. Five doctors have told her it's 'hormonal'. She has lost interest in everything and cries daily.",
    expertDifferential: ["MDD (over-shadowed by the PCOS label)", "PCOS-related mood symptoms", "Adjustment disorder"],
    expertNext: "Do not stop at the hormonal label — screen for anhedonia, sleep, and suicide. Comorbidity is not exclusion.",
    lesson: "Diagnostic overshadowing: the physical label (PCOS, thyroid, epilepsy) never excludes depression. Ask directly.",
    trap: "diagnostic_overshadowing",
  },
  {
    line: "A 24-year-old man, 'tension hai' for a month after his girlfriend left. Sleep fine, appetite fine, working, laughing with friends.",
    expertDifferential: ["Situational stress with intact function (no disorder)", "Adjustment disorder (defensible)", "MDD (over-diagnosis)"],
    expertNext: "Confirm intact function — sleep, appetite, work, pleasure. No disorder? Then normalise and offer follow-up.",
    lesson: "Distress without functional decline is not a diagnosis. Restraint is the skill — pathologising normal reaction is the error.",
    trap: "over_diagnosis",
  },
  {
    line: "A 20-year-old, one panic attack three weeks ago after seeing a patient collapse in clinicals. Terrified of the diagnosis 'panic disorder'. No recurrence.",
    expertDifferential: ["Non-recurrent situational panic (no disorder)", "Panic disorder (over-diagnosis)", "Health anxiety"],
    expertNext: "Reassure honestly: one triggered episode without recurrence or avoidance is not a disorder. Follow up rather than label.",
    lesson: "A one-off panic after a medical scare is normal physiology + fear. Manufactured diagnoses are the harm.",
    trap: "over_diagnosis",
  },
  {
    line: "A 14-year-old girl tells you a relative touches her on school-pickup days. She begs you not to tell.",
    expertDifferential: ["POCSO — mandatory reporting", "Child sexual abuse (disclosure)", "Family response management"],
    expertNext: "Report to the mandated channels. Your confidentiality ends where POCSO begins.",
    lesson: "No version of keeping this secret is legal or safe. Reporting IS the therapeutic act.",
    trap: "informant_conflict",
  },
  {
    line: "A 45-year-old man, 'I can stop anytime' about his nightly bottle of rum. Morning shakes, blackouts, rage at home. Wife asked you to see him.",
    expertDifferential: ["Alcohol use disorder (severe)", "Alcohol withdrawal risk", "Familial stress (the shield)"],
    expertNext: "Withdrawal risk first — daily heavy drinking can need medical detox. Then the motivation work.",
    lesson: "'I drink like everyone' + morning shakes + blackouts = severe AUD. Withdrawal risk gates everything.",
    trap: "substance_induced",
  },
  {
    line: "A 21-year-old, cannabis daily for a year, now hearing voices and sleeping 3 hours. Parents say 'he's schizophrenic'. No prior episodes.",
    expertDifferential: ["Substance-induced psychotic disorder", "First-episode schizophrenia (needs assessment)", "Sleep deprivation psychosis"],
    expertNext: "The substance-first hypothesis: does the picture track the cannabis use? A substance-induced presentation is often reversible.",
    lesson: "Cannabis-induced psychosis before a schizophrenia label — the substance history is the discriminate column.",
    trap: "substance_induced",
  },
  {
    line: "A 35-year-old man says he stopped his 'antidepressant' two days ago and now has electric-shock feelings in his head and nausea.",
    expertDifferential: ["Antidepressant discontinuation syndrome", "New-onset neurological problem", "Anxiety relapse"],
    expertNext: "Check the taper: was it abrupt? Reinstatement/taper guidance belongs to the prescriber; the electric-shock sensation is classic discontinuation.",
    lesson: "Abrupt SSRI stop → 'brain zaps' + nausea = discontinuation syndrome. Not anxiety, not new neurology — a taper problem.",
    trap: "iatrogenic",
  },
  {
    line: "A 29-year-old woman, 6 months postpartum, 'not a good mother', crying daily, mother-in-law does the childcare. Passive thoughts the baby 'would be better off'.",
    expertDifferential: ["Postpartum depression", "Adjustment disorder", "Normal motherhood stress (with risk screening)"],
    expertNext: "Risk screening is non-negotiable: 'Have you had thoughts of harming yourself or the baby?' Passive thoughts + daily crying + engagement loss = treat.",
    lesson: "PPD is dangerously under-treated in India, especially in joint families where the mother's voice is crowded out.",
    trap: "under_diagnosis",
  },
  {
    line: "A 65-year-old woman, 'my wife's chair' — 10 months since her death. He talks to the chair, sorts her clothes, but eats well and laughs with grandchildren.",
    expertDifferential: ["Normal grief with rituals", "Complicated grief (if function declining)", "MDD (if anhedonia sustained)"],
    expertNext: "Function discriminates: preserved pleasure and appetite with grief rituals = normal. Declining function + anhedonia = complicated grief/MDD.",
    lesson: "Grief rituals (talking to the chair) are not pathology when function is preserved. The decline is the signal.",
    trap: "over_diagnosis",
  },
  {
    line: "A 19-year-old college student, intrusive blasphemous thoughts, washes hands 30 times a day, missed 11 days of college, ashamed, thinks he's 'possessed'.",
    expertDifferential: ["OCD (contamination/religious)", "Possession (cultural framing)", "Psychotic disorder (if insight lost)"],
    expertNext: "The ego-dystonic quality — he fights the thoughts and knows they're 'silly' — says OCD, not delusion. Treat with ERP, not exorcism.",
    lesson: "Obsessions are resisted; delusions are held. The shame + resistance + rituals = OCD, whatever the family called it.",
    trap: "cultural_idiom",
  },
  {
    line: "Patient: \"I'm fine, just tired.\" (No elaboration. Flat affect. Sitting still.)",
    expertDifferential: ["Depressive fatigue", "'Fine' as a shield (avoidance)", "Anaemia / thyroid"],
    expertNext: "Don't accept 'fine' — ask 'What does a bad day look like?' and screen the physical triad.",
    lesson: "'I'm fine' in a flat patient is the most common opening of a missed depression. The flatness is data.",
    idiom: true,
    trap: "somatic_mask",
  },
  {
    line: "A 41-year-old man, 'my wife dragged me here, I'm not an alcoholic'. Smells of alcohol at 10am. Denies everything.",
    expertDifferential: ["Alcohol use disorder (severe)", "Alcohol dependence with denial", "Liver disease (alcohol-related)"],
    expertNext: "Do not fight the denial — mill the resistance: 'you didn't want to come. What would have to happen for you to want to?'",
    lesson: "Roll with the resistance. Morning drinking + smell + denial = AUD until proven otherwise.",
    trap: "adherence_fiction",
  },
  {
    line: "A 55-year-old man, 3 months of progressive low mood after his shop failed. He says he's 'fine' but his wife says he gave away his tools and stopped eating.",
    expertDifferential: ["MDD", "Adjustment disorder (if function intact)", "Suicidality — screen now"],
    expertNext: "Giving away possessions is a risk marker — screen for suicidal ideation in clear language TODAY, then treat the depression.",
    lesson: "Giving things away + stopped eating = risk behaviour, not a mood complaint. The family's report is the clinical finding.",
    trap: "late_risk_reveal",
  },
  {
    line: "A 48-year-old woman on lithium for bipolar. She says she's 'a bit down' but sleeping 10 hours and eating well. Lithium level therapeutic.",
    expertDifferential: ["Bipolar depression vs euthymia", "Normal variation within recovery", "Medication-related sedation"],
    expertNext: "Clarify function: is the 'down' impairing? Euthymia with a 'flat' day is not a relapse — don't chase it with medication changes.",
    lesson: "Not every 'bit down' in bipolar is an episode. Function + objective markers (sleep, appetite, level) decide.",
    trap: "over_diagnosis",
  },
  {
    line: "A 16-year-old girl, angry, dropped out of sports, won't speak in the consult. Parents call her 'always angry'. A teacher noticed she winces when her shoulder is touched.",
    expertDifferential: ["Abuse (the winch is the tell)", "Depression in adolescence", "ODD (the family label)"],
    expertNext: "The winch demands a gentle private enquiry about who touches her and whether anyone has hurt her.",
    lesson: "A flinch is a disclosure the mouth hasn't made. Angry adolescents with a physical tell need a private, safe conversation.",
    trap: "late_risk_reveal",
  },
  {
    line: "A 62-year-old widow, 'forgets things', gets lost in the market twice, laughs it off. Family confirms she repeats the same questions within minutes.",
    expertDifferential: ["Early dementia", "Normal ageing (over-diagnosis)", "Delirium (if acute)"],
    expertNext: "Repeating identical questions within minutes + getting lost = not normal ageing. Refer for cognitive assessment; screen delirium first.",
    lesson: "Getting lost and immediate repetition are the difference between 'ageing' and dementia. The family's examples decide.",
    trap: "medical_mimic",
  },
  {
    line: "A 26-year-old man, recovering from alcohol dependence, relapsed at a party. Ashamed, considering stopping treatment.",
    expertDifferential: ["Relapse (normal part of recovery)", "Dependence, ongoing (if pattern repeats)", "Depression post-relapse"],
    expertNext: "Frame the relapse as data, not failure: what happened, what's the next attempt, keep treatment. Shame is the killer.",
    lesson: "Relapse is part of recovery — 4 months sober then a slip is progress information, not proof of failure.",
    trap: "adherence_fiction",
  },
  {
    line: "A 29-year-old pregnant woman, 20 weeks, severe morning nausea, 'can't cope', crying in the consult. History of depression, stopped her SSRI at conception.",
    expertDifferential: ["Depression relapse vs normal pregnancy distress", "Hyperemesis gravidarum", "Anxiety about the pregnancy"],
    expertNext: "Screen for depression specifically — past history + stopped SSRI + crying daily = relapse risk, not just hormones.",
    lesson: "Pregnancy is not a depression shield. Past history + stopped medication + distress = need for real assessment.",
    trap: "diagnostic_overshadowing",
  },
  {
    line: "A 19-year-old, two voices arguing about him, terrified, denies any plan to harm himself. Daily cannabis, a year, hasn't slept.",
    expertDifferential: ["First-episode psychosis", "Substance-induced psychosis", "Sleep-deprivation psychosis"],
    expertNext: "Risk assessment first (behaviour, not just ideation), then the substance/sleep confound and psychiatric referral.",
    lesson: "First-episode psychosis with a substance confound: assess risk, treat sleep, refer early.",
    trap: "substance_induced",
  },
  {
    line: "A 41-year-old man, divorced 2 years, 'should have moved on by now'. Keeps her photo, visits the old flat. Working, eating, joined a cricket club.",
    expertDifferential: ["Complicated grief vs normal grief", "Adjustment disorder", "Depression (check anhedonia)"],
    expertNext: "Function again: working + eating + new social life = normal grieving with a different timetable. No diagnosis needed.",
    lesson: "'Should have moved on' is a cultural clock, not a diagnostic one. Preserved function is the answer.",
    trap: "over_diagnosis",
  },
  {
    line: "A 68-year-old man with Parkinson's, 'hands shake more', feels slowed down and sad, lost interest in hobbies.",
    expertDifferential: ["Parkinson's depression (common, treatable)", "Motor progression", "Dementia (if cognition involved)"],
    expertNext: "Anhedonia in Parkinson's is depression, not 'understandable' sadness — it's common and treatable. Screen and treat.",
    lesson: "Diagnostic overshadowing of Parkinson's depression: 'of course he's sad' is how treatable depression goes missed.",
    trap: "diagnostic_overshadowing",
  },
  {
    line: "A 30-year-old teacher, 'just tired' at start of term. No sleep change, no anhedonia, enjoys classes. Asked why she came: 'my mother worries'.",
    expertDifferential: ["No disorder — sent by a worried mother", "Adjustment disorder (defensible)", "MDD (over-diagnosis)"],
    expertNext: "Listen to HER reason for coming. Sent-by-family with no complaint and intact function = reassure and offer follow-up.",
    lesson: "'Sent by family' with no symptoms is not a case. The anxious mother is the presenting problem, not the patient.",
    trap: "over_diagnosis",
  },
  {
    line: "A 24-year-old, 'the doctor said my BP readings are crazy' — racing heart and trembling every morning for two months. BP medicines changed three times.",
    expertDifferential: ["Hyperthyroidism", "Caffeine excess", "Anxiety (the easy mislabel)"],
    expertNext: "Morning tremors + erratic readings: TSH, caffeine history, medication timing — the workup comes before 'anxiety'.",
    lesson: "Anxiety is the default label for a medical mimic pattern. Morning tremors deserve a thyroid panel, not a diagnosis.",
    trap: "medical_mimic",
  },
  {
    line: "A 15-year-old boy, exam in 4 days, sleepless, butterflies, over-preparing. No avoidance, no panic outside exams, function otherwise intact.",
    expertDifferential: ["Exam anxiety within range (no disorder)", "Generalised anxiety (over-diagnosis)", "Adjustment disorder"],
    expertNext: "Situation-specific, time-limited, function intact = normal exam anxiety. Validate, don't label.",
    lesson: "Exam anxiety within range is the culture's most over-diagnosed normal. The context is the diagnosis.",
    trap: "over_diagnosis",
  },
  {
    line: "A 36-year-old woman, 'I can't remember anything' for 3 months. Also reports poor sleep, irritability, and that she stopped her job hunt. TSH pending.",
    expertDifferential: ["Depression with cognitive complaints", "Hypothyroidism", "Dementia (young, unlikely)"],
    expertNext: "Cognitive complaints with mood + sleep disturbance in a 36-year-old = depression until the workup says otherwise.",
    lesson: "Pseudo-dementia of depression: memory complaints with mood symptoms in the young are depression's. Treat mood first.",
    trap: "medical_mimic",
  },
  {
    line: "A 22-year-old man, checking the door lock exactly 7 times or 'something bad will happen' to his parents. Knows it's silly, cannot stop.",
    expertDifferential: ["OCD (checking)", "Superstitious behaviour (cultural)", "Anxiety disorder"],
    expertNext: "The ego-dystonic quality (he knows it's silly) + the magic rule = OCD. ERP, not reassurance.",
    lesson: "'I know it's silly but I can't stop' is the OCD signature — resisted, ego-dystonic, compulsive.",
    trap: "under_diagnosis",
  },
  {
    line: "A 50-year-old woman, 'seene mein jalan' (burning chest) and ghabrahat for a year. GI workups negative. She is now housebound.",
    expertDifferential: ["Somatic symptom disorder / health anxiety", "Panic disorder with agoraphobia", "Gastro issues (recheck)"],
    expertNext: "The functional decline is the discriminator — housebound = the anxiety loop owns her life. Treat the loop, acknowledge the symptom.",
    lesson: "A somatic idiom plus housebound avoidance = panic/somatic loop. The workup is done; the treatment is behavioural.",
    idiom: true,
    trap: "somatic_mask",
  },
  {
    line: "A 33-year-old man, 'dimag kaam nahi karta' (my mind doesn't work) — can't focus, can't read, forgets words. 4 months. No sleep complaint, no mood complaint.",
    expertDifferential: ["Depression (cognitive presentation)", "B12 / thyroid / anaemia", "ADHD (adult, if lifelong)"],
    expertNext: "Ask the mood/sleep questions anyway — cognitive complaints without mood complaints are still often depression. Plus the workup.",
    lesson: "'Mind doesn't work' is the cognitive idiom of depression in Indian English. Never take it at face value.",
    idiom: true,
    trap: "somatic_mask",
  },
  {
    line: "A 28-year-old man, 'neend nahi aati' (can't sleep) for 5 months. Wakes at 4am every morning, gets out of bed exhausted, lost his appetite.",
    expertDifferential: ["MDD (early-morning waking)", "Primary insomnia", "Medical mimic (thyroid)"],
    expertNext: "Early-morning waking + appetite loss + exhaustion = depression pattern. Ask mood, anhedonia, and risk.",
    lesson: "4am waking is the depression signature sleep pattern. Treat it as a mood screen, not a sleep complaint.",
    idiom: true,
    trap: "somatic_mask",
  },
  {
    line: "A 44-year-old woman, 'chakkar' (dizziness) and 'haath-pair thande' (cold hands and feet) for 2 years, plus heavy periods.",
    expertDifferential: ["Iron-deficiency anaemia", "Hypothyroidism", "Anxiety (the easy label)"],
    expertNext: "Pallor + cold + heavy periods + dizziness = anaemia workup first. The psychiatric label comes last.",
    lesson: "Cold extremities + dizziness + heavy periods is anaemia until proven otherwise. The body leads.",
    idiom: true,
    trap: "medical_mimic",
  },
  {
    line: "A 20-year-old woman, 'garmi lagti hai' (feels hot) inside, sweating, racing heart, after her engagement was fixed. No fever, no weight loss.",
    expertDifferential: ["Anxiety (situational)", "Hyperthyroidism", "Panic disorder"],
    expertNext: "'Hot inside' + sweating + racing heart around a life event: TSH to rule out thyroid, then treat the anxiety.",
    lesson: "'Feels hot inside' is a somatic anxiety idiom, but thyrotoxicosis wears the same clothes. Workup first, then the label.",
    idiom: true,
    trap: "medical_mimic",
  },
  {
    line: "A 31-year-old man, 'sinking heart' (dil baith jana) since his father's death 6 weeks ago. Not eating well, but meeting friends, working.",
    expertDifferential: ["Normal grief (idiom of loss)", "MDD (if function falls)", "Complicated grief (if time passes)"],
    expertNext: "The idiom is a loss reaction — check function over time. Preserved work + friends = grief, not depression.",
    lesson: "'Sinking heart' is the Punjabi idiom of loss. It is grief's language, not pathology — function decides.",
    idiom: true,
    trap: "cultural_idiom",
  },
  {
    line: "A 39-year-old man, 'nazar lag gayi' (evil eye) blamed for his business failing. He believes someone cursed him. No mood symptoms, functioning.",
    expertDifferential: ["Attributional belief (cultural)", "Adjustment reaction (business stress)", "MDD (if symptoms emerge)"],
    expertNext: "Respect the attribution, screen the symptoms: is there anhedonia, sleep loss, withdrawal? The belief alone is not illness.",
    lesson: "'Nazar' is a normal cultural attribution, not a delusion — it is a formulation, not a pathology.",
    idiom: true,
    trap: "cultural_idiom",
  },
  {
    line: "A 25-year-old woman, 'dil ghabrata hai' before every exam and interview. Racing heart, sweaty palms, resolves after. Sleeps fine otherwise.",
    expertDifferential: ["Performance anxiety (situational)", "Panic disorder (if spontaneous)", "Social anxiety (if broader)"],
    expertNext: "Situational, anticipatory, resolving = performance anxiety, not panic disorder. Build exposure, don't label a disorder.",
    lesson: "'Dil ghabrata hai' before performance is normal physiology + fear. The situation-specificity is the diagnosis.",
    idiom: true,
    trap: "over_diagnosis",
  },
  {
    line: "A 47-year-old man, three months of 'tension' after his brother cheated him in the family business. Sleep broken, but working, eating, doing puja.",
    expertDifferential: ["Adjustment disorder", "Situational stress, intact function (no disorder)", "MDD (screen)"],
    expertNext: "Check the protective factors: puja, eating, working. If function holds, this is stress with intact coping — not MDD.",
    lesson: "Tension after a betrayal with intact function and coping = adjustment-level, not depression. Restraint again.",
    idiom: true,
    trap: "over_diagnosis",
  },
  {
    line: "A 34-year-old woman on an antipsychotic for 6 months reports 'my hands won't stay still, I pace all day, my legs feel like they're buzzing'.",
    expertDifferential: ["Tardive akathisia / drug-induced", "Anxiety", "Restless legs syndrome (if nocturnal)"],
    expertNext: "The pacing + buzzing + on a neuroleptic = akathisia. Report to prescriber for dose review — do NOT 'treat the anxiety'.",
    lesson: "Chronic pacing on an antipsychotic is akathisia, not anxiety. Raising the antipsychotic is the worst possible move.",
    trap: "iatrogenic",
  },
  {
    line: "A 23-year-old man, 'I was in a government scheme, they tested my urine, and since then my body feels different'. No psychosis, no mood symptoms.",
    expertDifferential: ["Health anxiety / somatic preoccupation", "Delusional disorder (if fixed, impairing)", "No disorder (if transient)"],
    expertNext: "Clarify what 'different' means and whether it impairs function. A preoccupation is not yet a delusion.",
    lesson: "Reference experiences are common; fixed delusions are not. Assess fixity and impairment before any label.",
    trap: "over_diagnosis",
  },
  {
    line: "A 58-year-old woman, 'acidity' and 'gas ho gaya' for a year, plus low mood. She has lost 4kg. Family says it's 'just acidity'.",
    expertDifferential: ["Depression (somatic presentation) with weight loss", "Gastro issue (workup)", "Malignancy (weight loss — screen)"],
    expertNext: "Weight loss + mood + 'acidity' label = screening for both depression AND medical causes. Never accept the family's gastro label.",
    lesson: "'Just acidity' with weight loss and low mood is a two-way screen: depression and medical. The label hides both.",
    idiom: true,
    trap: "diagnostic_overshadowing",
  },
  {
    line: "A 21-year-old woman, 2 months of 'weakness hai' after dengue recovery. Sleeping 12 hours, not bathing, stopped college.",
    expertDifferential: ["Post-infectious fatigue", "Depression (functional collapse)", "Anaemia / post-viral syndrome"],
    expertNext: "The collapse (not bathing, stopped college) is the depression signal — post-viral fatigue doesn't do that.",
    lesson: "Post-viral fatigue is real, but functional collapse is depression's signature on top. Screen both.",
    idiom: true,
    trap: "diagnostic_overshadowing",
  },
  {
    line: "A 27-year-old man, 'I'm stressed' — but on enquiry: sleeping 3 hours, spending recklessly, talking fast, new startup plans, family worried.",
    expertDifferential: ["Hypomania/mania", "Stress (his framing)", "Substance use"],
    expertNext: "The three-hour sleep + grandiosity + recklessness = hypomania until proven otherwise. The 'stress' label is the trap.",
    lesson: "'I'm stressed' is the most dangerous understatement — the elevated state wears the costume of normal life.",
    trap: "under_diagnosis",
  },
  {
    line: "A 32-year-old woman, 4 months after her brother's suicide. She is functioning — teaching, eating — but says she 'thinks about it every day'. Family wants 'treatment'.",
    expertDifferential: ["Normal grieving with intrusive memories", "Complicated grief (if time passes without shift)", "MDD (check anhedonia, function)"],
    expertNext: "Function + time: daily thoughts of the loss with intact function at 4 months = grieving, not disorder. Validate, follow up.",
    lesson: "The family's urgency is not a diagnosis. Intrusive grief with intact function is the brain's work, not pathology.",
    trap: "over_diagnosis",
  },
  {
    line: "A 49-year-old man, 'she says I don't listen' — wife's complaint driving the visit. He drinks 3 pegs most nights 'for sleep'. Morning hands shake.",
    expertDifferential: ["Alcohol dependence (morning shakes)", "Marital distress (the presented problem)", "Depression (screen)"],
    expertNext: "The morning shakes are the clinical finding hidden in the marital complaint. Withdrawal risk + AUD first.",
    lesson: "A marital complaint can deliver the alcohol diagnosis — the shakes matter more than the argument.",
    trap: "substance_induced",
  },
  {
    line: "A 60-year-old woman, 4 weeks after cataract surgery, 'confused at night, not herself'. Family says 'old age'. No psychiatric history.",
    expertDifferential: ["Post-operative delirium", "Dementia (if it persists)", "Infection / electrolyte emergency"],
    expertNext: "NEW confusion in an older adult = medical emergency workup (infection, electrolytes). 'Old age' is never the first answer.",
    lesson: "Acute-on-chronic confusion is delirium until the workup clears it. Old age does not explain new confusion.",
    trap: "medical_mimic",
  },
  {
    line: "A 26-year-old woman, 'depression ho gaya' after a breakup — her words. Eating, sleeping, working, laughing on the phone with friends.",
    expertDifferential: ["Colloquial sadness — the idiom, not the disorder", "Adjustment reaction", "MDD (if function fails)"],
    expertNext: "Confirm function: laughing + working + eating = sadness, not depression. The idiom and the disorder are different things.",
    lesson: "'Depression ho gaya' is how people say 'I'm sad', not a self-diagnosis. Function decides the difference.",
    idiom: true,
    trap: "over_diagnosis",
  },
  {
    line: "A 37-year-old man, on three antihypertensives and metformin, 2 weeks of 'feeling low and exhausted' after a medication change. No sleep change, no anhedonia.",
    expertDifferential: ["Medication-related low mood (beta-blockers etc.)", "Medical mimic (anaemia, thyroid)", "Depression (over-diagnosis without workup)"],
    expertNext: "The medication change timeline first — a drug that started the mood change needs the prescriber, not a depression label.",
    lesson: "Low mood fully explained by a medication change is a medical problem until proven otherwise. The workup is the restraint.",
    trap: "medical_mimic",
  },
  {
    line: "A 24-year-old woman, 'I can't focus' for 6 months. No sleep complaints, but she has stopped seeing friends and cries alone at night.",
    expertDifferential: ["Depression (focus is the tip)", "Adult ADHD (if lifelong pattern)", "Anaemia / thyroid"],
    expertNext: "The withdrawal + crying = mood first. 'Can't focus' is how depression presents at her age — ask mood and risk.",
    lesson: "'Can't focus' without the historic pattern of ADHD is depression until proven otherwise. The withdrawal is the tell.",
    trap: "under_diagnosis",
  },
  {
    line: "A 55-year-old man, prostate surgery 6 weeks ago, now 'too tired to do anything', naps all day, stopped going to the temple. Family fears he's 'dying'.",
    expertDifferential: ["Post-operative depression", "Anaemia (surgical blood loss)", "Hypothyroidism"],
    expertNext: "Anhedonia + collapse after surgery + family fear = screen depression AND check the bloods. Both, not either.",
    lesson: "Surgery is a classic depression trigger. 'Too tired' with loss of religion + social withdrawal = treat the mood.",
    trap: "diagnostic_overshadowing",
  },
  {
    line: "A 31-year-old man, 'my wife says I drink too much, I say business stress'. Two DUIs this year. Denies any problem.",
    expertDifferential: ["Alcohol use disorder (severe)", "Dependence with denial", "Bipolar (if mood swings present)"],
    expertNext: "The DUIs are the objective data the denial cannot explain. Motivational interviewing, not argument.",
    lesson: "Two DUIs + denial = the alcohol problem is real and dangerous. Data beats denial.",
    trap: "adherence_fiction",
  },
  {
    line: "A 19-year-old woman, 'my roommate said I'm bipolar' because her mood swings fast when stressed. No manic episodes, no sleep change, no impulsivity.",
    expertDifferential: ["No disorder — friend's label", "Emotion dysregulation under stress", "Bipolar (requires actual episodes)"],
    expertNext: "Bipolar requires episodes of mania/hypomania — rapid mood shifts without sleep/elevation changes are not bipolar. Reassure and reframe.",
    lesson: "The lay 'bipolar' label for emotional reactivity is the modern 'hysterical'. Confirm episodes before the label.",
    trap: "over_diagnosis",
  },
  {
    line: "A 43-year-old man, 'heart attack' twice in the ER — both times normal troponin, normal ECG. He is now terrified to exercise. Cardiologist says anxiety.",
    expertDifferential: ["Panic disorder", "Cardiac anxiety after false alarms", "GAD (if generalised)"],
    expertNext: "The cardiologist's assessment + avoidance of exercise = panic with illness anxiety. CBT + graded exposure, not more tests.",
    lesson: "After a false alarm, the fear of the heart replaces the heart problem. The behavioural work is the treatment.",
    trap: "somatic_mask",
  },
  {
    line: "A 29-year-old non-binary person, 3 months of worsening low mood, started 'therapy' with a coach who called it 'energy blockage'. No assessment, no risk screen.",
    expertDifferential: ["Depression (unassessed, untreated)", "The coaching label is not a diagnosis", "Risk — screen now"],
    expertNext: "Do the actual assessment the coach didn't: mood, sleep, function, and risk. The 'energy blockage' label delays treatment.",
    lesson: "A coaching label without assessment is a treatment delay. The risk screen was never done — do it now.",
    trap: "misattributed_diagnosis",
  },
  {
    line: "A 70-year-old man, 'hearing my dead wife call my name' nightly for 6 months. Otherwise fine: eating, walking, joking with neighbours.",
    expertDifferential: ["Bereavement hallucination (common, benign)", "Psychotic disorder (if impairing/convincing)", "Dementia (if cognition slipping)"],
    expertNext: "Bereavement hallucinations in an otherwise well older person are common and not psychosis. Function + cognition decide.",
    lesson: "Hearing a lost spouse is a grief phenomenon, not schizophrenia, when function is intact. Over-pathologising it is the error.",
    trap: "over_diagnosis",
  },
  {
    line: "A 35-year-old woman, four doctors, four diagnoses (anxiety, IBS, 'weakness', 'allergy'). She is exhausted and losing faith. Sleep broken, crying daily.",
    expertDifferential: ["Depression with multiple somatisation visits", "The system failure (four labels, no assessment)", "Anxiety / somatic disorder"],
    expertNext: "STOP diagnosing — do the full history and risk screen. The depression is under the label pile.",
    lesson: "Four labels and no sleep/mood history is the pattern of missed depression. One honest assessment beats four labels.",
    trap: "misattributed_diagnosis",
  },
  {
    line: "A 22-year-old man, 'something is happening to me' — depersonalisation episodes in crowded places for 3 months. No avoidance, but worried he's 'going mad'.",
    expertDifferential: ["Anxiety with depersonalisation", "Panic-spectrum phenomenon", "Epileptic aura (if brief/recurrent)"],
    expertNext: "'Going mad' fear + situational episodes = anxiety phenomenon. The fear of madness is diagnostic, not confirmatory.",
    lesson: "Depersonalisation in crowds with the 'going mad' fear is anxiety's classic presentation. Reassurance + exposure, not psychosis work.",
    idiom: true,
    trap: "under_diagnosis",
  },
  {
    line: "A 51-year-old woman, 2 years of 'gas' and abdominal pain, six gastroscopies normal. She has stopped leaving the house and lost 8kg.",
    expertDifferential: ["Somatic symptom disorder", "Depression with somatic presentation", "Panic/agoraphobia"],
    expertNext: "The housebound + weight loss = functional collapse. Acknowledge the symptoms fully, then treat the anxiety-depression loop.",
    lesson: "The workup is done; the housebound collapse is the actual disease. Behavioural treatment, not another scope.",
    trap: "somatic_mask",
  },
  {
    line: "A 40-year-old man, 'my wife wants a divorce since my mother moved in'. He says he's fine. She says he drinks every night and rages.",
    expertDifferential: ["AUD (her account is the data)", "Marital distress", "Depression (screen)"],
    expertNext: "Interview the informant's observations: nightly drinking + rage = AUD regardless of his 'fine'. Withdrawal + motivation work.",
    lesson: "The drinker's 'fine' and the family's 'rages nightly' — the informant carries the clinical data.",
    trap: "informant_conflict",
  },
  {
    line: "A 24-year-old man, 'koi baat nahi' (nothing's wrong) to everything — flat, monosyllabic, sitting rigidly, brought by college because he stopped attending classes.",
    expertDifferential: ["Depression with withdrawal", "The 'nothing's wrong' shield", "Psychosis (if thought disorder present)"],
    expertNext: "Don't accept the shield — meet the flatness: 'you stopped classes. What happened at college that made you stop?'",
    lesson: "'Koi baat nahi' from a student who stopped attending is a depression screen, not an answer.",
    idiom: true,
    trap: "somatic_mask",
  },
  {
    line: "A 33-year-old woman, 8 months postpartum, 'I don't even feel like my baby is mine'. No sadness, but a pervasive sense of unreality, difficulty bonding.",
    expertDifferential: ["Postpartum depression with dissociation", "Perinatal OCD (if intrusive harm images)", "Adjustment to motherhood"],
    expertNext: "The unreality + bonding difficulty is a mood disorder presentation — ask intrusive thoughts about the baby directly.",
    lesson: "Postpartum presentations without 'sadness' are still depression spectrum. The unreality is the symptom to name.",
    trap: "under_diagnosis",
  },
  {
    line: "A 28-year-old woman, 'I'm stressed' — but she has lost 10kg in 3 months, is hyperactive at work, sleeps 4 hours, and her husband says she fights over nothing.",
    expertDifferential: ["Hyperthyroidism", "Bipolar (hypo)mania", "Anxiety/stress (her framing)"],
    expertNext: "Weight loss + sleep 4h + irritability = workup + mania screen. The 'stressed' frame hides a treatable cause.",
    lesson: "Hyperactivity + weight loss + little sleep is never 'just stress' — thyroid and mood elevation first.",
    trap: "medical_mimic",
  },
  {
    line: "A 34-year-old woman asking for a 'depression certificate' for her exam board — she has had 2 sessions with you and describes mild exam nerves (function intact, sleep fine). The certificate will decide 6 months of extra time.",
    expertDifferential: ["Certificate request for secondary gain", "Exam nerves in range (no disorder)", "Depression (if a real assessment says so — it hasn't yet)"],
    expertNext: "Explore what the certificate is FOR before writing anything — the external benefit, not the symptoms, may be the driver.",
    lesson: "A certificate request with intact function and an external benefit is secondary gain until properly assessed. Paperwork is not a diagnosis.",
    trap: "secondary_gain",
  },
  {
    line: "A 6-year-old boy, 'tantrums' at school since his father left 4 months ago. Teacher says he hits other children. At home he sleeps and eats fine, plays with his sister.",
    expertDifferential: ["Adjustment reaction in a child (behavioural)", "Oppositional defiant disorder (over-diagnosis)", "Depression in childhood (if withdrawn, not hitting)"],
    expertNext: "Ask about the home situation and the child's own words — behaviour IS his language at 6. Function at home decides.",
    lesson: "A child's 'tantrums' after a loss are adjustment behaviour, not a disorder — the school's report is one lens, home is another.",
    trap: "over_diagnosis",
  },
  {
    line: "A 15-year-old girl, 'always tired', sleeping 16 hours on weekends, stopped netball, grades dropped. Parents say 'just lazy teenager'.",
    expertDifferential: ["Adolescent depression", "Iron deficiency (heavy periods)", "Sleep phase delay (normal teen)"],
    expertNext: "The drop in grades + sports + 16-hour sleep is the mood signal — ask her alone about mood and risk.",
    lesson: "'Lazy teenager' with a triple drop (sleep, sport, grades) is depression until the screen says otherwise.",
    trap: "under_diagnosis",
  },
  {
    line: "A 74-year-old woman, 'she's fine, just old' — but she has lost 5kg, stopped cooking, and stares at the wall since her son moved abroad 6 months ago.",
    expertDifferential: ["Late-life depression", "Dementia (if cognitive)", "Normal ageing (over-diagnosis)"],
    expertNext: "Weight loss + social withdrawal after a loss in an older adult = depression screen + physical workup (the 5kg needs explaining).",
    lesson: "'Just old' is diagnostic overshadowing — the 5kg and the staring are the depression signature in late life.",
    trap: "diagnostic_overshadowing",
  },
  {
    line: "A 32-year-old pregnant woman (24 weeks), 'can't cope with anything', crying daily, stopped eating. Previous depression, off medication since conception.",
    expertDifferential: ["Depression relapse in pregnancy", "Normal pregnancy distress (over-diagnosis)", "Hyperemesis (if vomiting)"],
    expertNext: "Past history + stopped medication + crying daily + stopped eating = relapse risk, not 'hormones'. Screen and treat.",
    lesson: "Pregnancy does not protect against depression — past history and functional collapse decide.",
    trap: "diagnostic_overshadowing",
  },
  {
    line: "A 9-year-old boy, 'won't go to school' since a teacher shouted at him 2 weeks ago. Refuses mornings, then settles at home. No nightmares, no avoidance elsewhere.",
    expertDifferential: ["School refusal after an incident (situational)", "Separation anxiety (if broader)", "Bullying screen"],
    expertNext: "The incident-anchored onset with home-settling = situational school refusal. Ask about the teacher specifically.",
    lesson: "School refusal after a specific incident is the child's solution, not a disorder — address the incident, keep him in school.",
    trap: "over_diagnosis",
  },
  {
    line: "A 68-year-old man, 'forgetting names' for a year, but manages his medicines, walks to the market, and remembers his grandchildren's birthdays.",
    expertDifferential: ["Normal ageing (name-finding)", "Mild cognitive impairment (if functional slip)", "Dementia (if functional decline)"],
    expertNext: "Function decides: intact medication management + independent shopping = normal ageing. Names alone are not dementia.",
    lesson: "Name-finding slips with intact function are normal ageing — over-diagnosing dementia is the error at this age.",
    trap: "over_diagnosis",
  },
  {
    line: "A 12-year-old girl, 'stomach ache every school morning' for 6 weeks. Settles by 10am. Missed 4 days. No weight loss, sleeps fine.",
    expertDifferential: ["School avoidance with somatic complaint", "Functional abdominal pain", "Organic cause (if red flags)"],
    expertNext: "The morning-only timing with home-settling is the somatic mask of school avoidance — ask what's happening at school.",
    lesson: "A morning-only stomach ache that settles at home is the child's somatic idiom of avoidance. The school is the question.",
    trap: "somatic_mask",
  },
  {
    line: "A 28-year-old man, first baby born 3 weeks ago, 'not sleeping', irritable, says 'the baby doesn't feel like mine'. Wife worried he's 'going mad'.",
    expertDifferential: ["Paternal postnatal depression", "Sleep deprivation adjustment", "Psychosis (if fixed beliefs/harm)"],
    expertNext: "Paternal PND is real and under-screened — ask mood, the 'not mine' feeling (depersonalisation is common), and harm thoughts.",
    lesson: "Fathers get postpartum depression too — 'not mine' is distress, not madness; screen harm directly.",
    trap: "under_diagnosis",
  },
  {
    line: "A 5-year-old girl, 'won't eat' since starting school. Eats at home happily. No weight loss, growing well.",
    expertDifferential: ["School-context food refusal (situational)", "Feeding disorder (if weight impact)", "Normal pickiness"],
    expertNext: "Context-specific with growth intact = situational — the school environment is the question, not the appetite.",
    lesson: "Eating fine at home + refusing at school = the school, not the child, is the diagnosis.",
    trap: "over_diagnosis",
  },
  {
    line: "A 70-year-old man, 4 weeks after his wife's death, 'can't sleep, no appetite, crying in the bathroom'. His daughter wants 'something to make him better'.",
    expertDifferential: ["Acute grief (normal)", "Depression (if time passes without shift)", "Complicated grief"],
    expertNext: "Four weeks of acute grief with crying = normal — validate, offer follow-up, and screen risk (the crying is the work of grief).",
    lesson: "Acute grief looks like depression for weeks — time and function decide. Medication is not the first answer.",
    trap: "over_diagnosis",
  },
  {
    line: "A 16-year-old boy, 'exam pressure', sleeping 4 hours, over-preparing, hands shake before tests. Functions fine between exams. No panic elsewhere.",
    expertDifferential: ["Exam anxiety within range", "Generalised anxiety (if pervasive)", "Panic disorder (if spontaneous)"],
    expertNext: "Situation-specific, time-limited, function intact = exam anxiety. The context is the diagnosis.",
    lesson: "Exam anxiety with intact function between exams is the culture's most over-diagnosed normal.",
    trap: "over_diagnosis",
  },
  {
    line: "A 34-year-old woman, 2 months postpartum, intrusive images of harming the baby. She is horrified and never acts on them. No psychosis features.",
    expertDifferential: ["Perinatal OCD (ego-dystonic intrusive images)", "Postpartum psychosis (if fixed beliefs)", "Depression with anxiety"],
    expertNext: "The horror + resistance = ego-dystonic OCD, not psychosis — validate the courage to tell, and offer ERP + medication review.",
    lesson: "Intrusive harm images in a horrified mother are perinatal OCD, not psychosis — the distress IS the ego-dystonic marker.",
    trap: "iatrogenic",
  },
  {
    line: "A 7-year-old girl, 'sees a shadow person' at bedtime for 3 weeks. Calm about it, sleeps fine, no daytime symptoms, no fear of being alone.",
    expertDifferential: ["Hypnagogic visual experience (common)", "Anxiety (if distress)", "Psychosis (essentially never at 7 without other signs)"],
    expertNext: "Bedtime-only, calm, no impairment = normal hypnagogic phenomena — reassure the parents, don't investigate a shadow.",
    lesson: "A calm child's bedtime shadow is the developing brain's normal border state — pathologising it is the error.",
    trap: "over_diagnosis",
  },
  {
    line: "A 41-year-old woman, 3 months post-hysterectomy, 'low and tired', stopped meeting friends. Her GP said 'hormones will settle'. She feels dismissed.",
    expertDifferential: ["Post-operative depression", "Hormonal change with mood effects", "The dismissal itself (iatrogenic harm)"],
    expertNext: "The social withdrawal is the signal — the 'hormones will settle' framing delayed a real screen. Screen now.",
    lesson: "Post-surgical low mood with withdrawal is depression until screened — 'hormones' is the GP's shadow, not a diagnosis.",
    trap: "diagnostic_overshadowing",
  },
  {
    line: "A 13-year-old boy, 'angry all the time' since parents separated 8 months ago. Fighting at school, but doing okay academically and has friends.",
    expertDifferential: ["Adjustment reaction with anger (behavioural)", "ODD (over-diagnosis)", "Depression (if withdrawn)"],
    expertNext: "The anger is the loss talking — check academic + social function (intact) and give him a safe space to name the loss.",
    lesson: "Anger after parental separation with intact function is grief in a boy's costume, not a conduct disorder.",
    trap: "over_diagnosis",
  },
  {
    line: "A 72-year-old woman, 'everything is an effort' for 8 months since her daughter's cancer diagnosis. She cares for her grandchild daily, cooks, and visits the hospital weekly.",
    expertDifferential: ["Caregiver burden with intact function (no disorder)", "Depression (if function collapses)", "Anxiety (if panic/persistent worry)"],
    expertNext: "She IS functioning under enormous load — validate, screen mood anyway, and ask what SHE needs (she won't volunteer it).",
    lesson: "A functioning caregiver under burden is not a disorder — but the mood screen is still owed, and so is asking what SHE needs.",
    trap: "over_diagnosis",
  },
  {
    line: "A 17-year-old girl, 'I can't focus' since her best friend moved abroad. Grades steady, sleeps fine, still plays basketball. Parents want an ADHD assessment.",
    expertDifferential: ["Grief reaction (situational)", "ADHD (if lifelong pattern — it isn't here)", "Normal sadness"],
    expertNext: "The trigger-anchored, time-limited, function-intact picture = grief, not ADHD. Reassure the parents, validate her.",
    lesson: "'I can't focus' after a loss with intact grades is grief, not ADHD — the label would be the harm.",
    trap: "over_diagnosis",
  },
  {
    line: "A 66-year-old man, Parkinson's for 8 years, 'the shaking is worse and I don't want to do anything'. He has stopped his beloved chess club.",
    expertDifferential: ["Parkinson's depression (common, treatable)", "Motor progression (the shaking)", "Dementia (if cognition)"],
    expertNext: "Anhedonia in Parkinson's is depression, not 'understandable' — screen and treat; the chess club loss is the clinical clue.",
    lesson: "Losing a beloved activity to apathy in Parkinson's is depression's signature — treat it, don't explain it away.",
    trap: "diagnostic_overshadowing",
  },
  {
    line: "A 19-year-old woman, 2 weeks after a road accident (minor injury, but she saw the other driver die), now 'can't stop replaying it', avoids the road, startles at horns.",
    expertDifferential: ["Acute stress reaction (first month is normal)", "PTSD (only after a month)", "Adjustment disorder"],
    expertNext: "Within the first month, re-experiencing + avoidance is the normal stress response — validate, screen for safety, follow up.",
    lesson: "Replay + avoidance in the first month after trauma is the brain's processing, not PTSD yet — the month line is the diagnosis.",
    trap: "over_diagnosis",
  },
  {
    line: "A 36-year-old man, 'my son is scared of me' — he shouts at home after work stress. Wife says 'he's fine otherwise'. He asks if he's 'a bad father'.",
    expertDifferential: ["Occupational stress spillover (no disorder)", "Depression with irritability (screen)", "AUD (if drinking involved)"],
    expertNext: "Screen both mood and alcohol — the shouting + guilt + work stress could be either. The self-question 'bad father' is the opening.",
    lesson: "'Am I a bad father' is a mood screen in disguise — the guilt and the shouting deserve the questions, not a label.",
    trap: "under_diagnosis",
  },
  {
    line: "A 34-year-old manager, 'my team is afraid of me' — she snaps at staff, works 12-hour days, can't sleep, and drinks wine to 'switch off'. Function at work intact.",
    expertDifferential: ["Occupational stress with irritability (screen mood)", "Alcohol misuse as coping", "Burnout"],
    expertNext: "Screen both mood and alcohol — the snap + wine pattern could be either; the drinking deserves its own question.",
    lesson: "The snap + wine coping pattern is two screens in one — mood AND alcohol get asked, never just the one that shows first.",
    trap: "under_diagnosis",
  },
  {
    line: "A 41-year-old software engineer, 'my wife says I'm never present' — he works abroad for 10 months a year, video-calls the family, and now feels 'like a stranger at home'. No mood symptoms.",
    expertDifferential: ["Migration/family-separation strain (no disorder)", "Depression if persistent with function loss", "Adjustment difficulty"],
    expertNext: "The separation is the clinical content — validate the loss of daily family life, screen mood anyway, and explore what 'present' would look like.",
    lesson: "'Never present' is a migration-strain complaint, not a diagnosis — the loss of daily family life is the clinical content once mood is screened.",
    trap: "over_diagnosis",
  },
  {
    line: "A 29-year-old woman, 'I do everything for my parents' — sole caregiver for a father with dementia and a mother with arthritis, no siblings nearby, working full-time. She is exhausted but functioning.",
    expertDifferential: ["Caregiver burden with intact function (no disorder)", "Depression (if function collapses)", "Burnout"],
    expertNext: "She is functioning under enormous load — validate, screen mood, and ask what SHE needs (she won't volunteer it).",
    trap: "over_diagnosis",
    lesson: "Caregiver burden with intact function is not a disorder — but the mood screen and the 'what do YOU need' question are still owed.",
  },
  {
    line: "A 37-year-old man, 'we fight about money every week' — the couple can't discuss finances without it exploding. He sleeps fine, works, and loves his kids. Wife asks him to 'see someone'.",
    expertDifferential: ["Couple communication difficulty (relational)", "Depression with irritability (screen)", "Anxiety under financial pressure"],
    expertNext: "Relational patterns are the content — but screen both partners' mood first; irritability can hide depression.",
    trap: "under_diagnosis",
    lesson: "Relational conflict is real content, but irritability can hide depression — screen both partners' mood before diagnosing the marriage.",
  },
  {
    line: "A 46-year-old woman, 'my husband's retirement has changed everything' — he is home all day, criticising her routine, and she has started hiding her activities from him. She feels 'trapped in my own house'.",
    expertDifferential: ["Couple life-stage conflict (relational)", "Depression with irritability (screen)", "Anxiety"],
    expertNext: "The retirement shift is the trigger — name the over-proximity dynamic, screen her mood, and consider couple work.",
    trap: "over_diagnosis",
    lesson: "The retirement over-proximity is the trigger — name the dynamic, screen her mood, and consider couple work.",
  },
  {
    line: "A 52-year-old man, 'I take care of my mother with dementia all night' — he sleeps in her room, hasn't seen friends in a year, and recently told his wife 'I don't know how much longer I can do this'. No suicidal ideation.",
    expertDifferential: ["Caregiver burnout with risk line", "Depression", "Complicated grief adjacent to the dementia loss"],
    expertNext: "The 'how much longer' is a risk screen — he is describing sustainable-continuation despair, not suicidal intent, but the question is owed and respite is the intervention.",
    trap: "late_risk_reveal",
    lesson: "'How much longer' from a caregiver is a risk screen, not a threat — sustainable-despair needs the question and the respite.",
  },
  {
    line: "A 33-year-old woman, 'my mother cries when I try to move out' — she has deferred her wedding twice because of her mother's distress. She is exhausted and angry but 'can never say no'.",
    expertDifferential: ["Enmeshment/family-pattern distress (relational)", "Depression with anxiety", "Social-anxiety-adjacent avoidance"],
    expertNext: "The pattern is the clinical content — the guilt, the anger, and the deferral deserve exploration; the mood screen sits underneath.",
    trap: "over_diagnosis",
    lesson: "Enmeshment is a family pattern worth grieving — the guilt and the deferred life are the content once mood is screened.",
  },
  {
    line: "A 48-year-old man, 'my wife's affair' — 3 months ago he discovered it, and now repeatedly asks her for details, checks her phone, and wakes at 3am ruminating. He works and eats.",
    expertDifferential: ["Post-infidelity distress (relational trauma)", "Depression with insomnia (screen)", "Pathological jealousy (if fixed beliefs)"],
    expertNext: "The 3am rumination + checking is the post-infidelity pattern — screen mood and risk, and consider trauma-focused work for the betrayal.",
    trap: "under_diagnosis",
    lesson: "Post-infidelity rumination at 3am is betrayal-trauma's signature — screen mood and risk, then treat the wound, not the checking.",
  },
  {
    line: "A 31-year-old woman, 'my husband is never wrong' — he dismisses her feelings, she has stopped raising anything, and feels 'invisible'. She has lost interest in cooking, which she loved.",
    expertDifferential: ["Relational invalidation with anhedonia (screen depression)", "Depression with avoidance", "Marital distress"],
    expertNext: "The lost interest in cooking is the mood signal under the relational story — screen depression first, then the couple pattern.",
    trap: "under_diagnosis",
    lesson: "The lost interest is the mood signal under the relational story — depression first, couple pattern second.",
  },
  {
    line: "A 26-year-old man, 'my boss humiliated me in the meeting' — 2 weeks ago, he now dreads work, has taken 3 sick days, and can't stop replaying it. He sleeps 7 hours and exercises.",
    expertDifferential: ["Workplace humiliation reaction (situational)", "Adjustment disorder", "Depression if persistent"],
    expertNext: "The replay + dread is the situation's signature within the first month — validate, screen function, and follow up on the persistence.",
    trap: "over_diagnosis",
    lesson: "Workplace humiliation replay within the first month is situational — validate, screen function, and follow the persistence.",
  },
  {
    line: "A 55-year-old woman, 'I'm the spare parent' — she raised her grandchildren after her daughter's breakdown, and now the daughter is well and taking them back. She is crying daily but says 'I should be happy'.",
    expertDifferential: ["Role-loss grief (the caregiving ends)", "Depression (screen)", "Complicated grief"],
    expertNext: "The loss of the caregiving role is real grief — validate the ambivalence, screen mood, and explore what her life is now.",
    trap: "over_diagnosis",
    lesson: "The end of a caregiving role is real grief — validate the ambivalence, screen mood, and ask who she is now.",
  },
  {
    line: "A 39-year-old man, 'I can't say no to my parents' — they decide his children's school, his house location, and his holidays. He feels 'like a puppet' and has started snapping at his kids.",
    expertDifferential: ["Family-of-origin boundary distress (relational)", "Depression with irritability (screen)", "Anxiety"],
    expertNext: "The puppet feeling + snapping at kids is the boundary strain — work the differentiation, screen the mood underneath.",
    trap: "under_diagnosis",
    lesson: "The puppet feeling plus snapping at kids is boundary strain — the differentiation work plus the mood screen underneath.",
  },
  {
    line: "A 44-year-old woman, 'my sister and I are not speaking' — 8 months of silence after a property dispute. She thinks about it every day but says 'I'm fine'.",
    expertDifferential: ["Family-conflict rumination (relational)", "Depression with unresolved grief", "Anxiety"],
    expertNext: "The daily rumination about an 8-month estrangement is a real burden — the mood screen and the conflict work, both.",
    trap: "over_diagnosis",
    lesson: "An 8-month estrangement ruminating daily is a real burden — the mood screen and the conflict work, both.",
  },
  {
    line: "A 57-year-old man, 'I lost my job at 57' — 3 months ago, three applications rejected. He has stopped applying, sleeps 12 hours, and his wife says he 'doesn't wash'.",
    expertDifferential: ["Depression after job loss", "Adjustment disorder", "Burnout aftermath"],
    expertNext: "The collapse (not washing, 12-hour sleep, stopped applying) is the depression signal — screen mood and risk directly.",
    trap: "under_diagnosis",
    lesson: "'Lazy jobless' with a collapse in self-care is depression — the not-washing and the stopped-applying are the diagnosis.",
  },
  {
    line: "A 30-year-old couple, 'we can't agree on having children' — she wants them now, he wants to wait. Both otherwise well, sleeping fine, arguing weekly but otherwise warm.",
    expertDifferential: ["Couple life-decision conflict (relational)", "Depression/anxiety in either partner (screen)", "No disorder"],
    expertNext: "The disagreement is real and painful but not pathological — screen both, then help them talk about the underlying fears (hers about age, his about his father's parenting).",
    trap: "over_diagnosis",
    lesson: "A painful life-decision conflict is not pathology — screen both, then help them find the fears under the positions.",
  },
  {
    line: "A 22-year-old man, 'pet mein jalan hai' (burning in stomach) every morning before work for 6 months. Endoscopy normal. He has started taking sick days.",
    expertDifferential: ["Somatic symptom disorder", "Panic disorder with anticipatory anxiety", "Functional dyspepsia (recheck)"],
    expertNext: "The morning-specific timing + normal scope + avoidance = the anxiety loop owns the body. Treat the anticipatory panic, not the stomach.",
    idiom: true,
    trap: "somatic_mask",
    lesson: "'Pet mein jalan' before work is the somatic idiom of anticipatory anxiety. The normal endoscopy is the green light to treat the loop.",
  },
  {
    line: "A 45-year-old woman, 'I'm a burden' since her stroke 8 months ago. Husband cares for her devotedly. She has stopped physio, eats half portions, and cries when he leaves the room.",
    expertDifferential: ["Post-stroke depression", "Adjustment disorder with depressed mood", "Functional neurological symptom (if new weakness)"],
    expertNext: "The physio stop + portion halving + separation distress = depression on top of the stroke. Treat mood to rescue rehab.",
    trap: "diagnostic_overshadowing",
    lesson: "Post-stroke 'giving up' is depression, not 'understandable' — the stroke is the trigger, the mood is the treatable barrier to recovery.",
  },
  {
    line: "A 19-year-old, 'I'm not real' episodes lasting seconds, 10 times a day since exams started. No avoidance, functions well, but terrified it's 'brain damage'.",
    expertDifferential: ["Exam-stress depersonalisation", "Panic-spectrum phenomenon", "Temporal lobe epilepsy (if stereotyped/brief)"],
    expertNext: "The fear of brain damage is the anxiety — brief, situational, function-intact depersonalisation is stress, not neurology.",
    idiom: true,
    trap: "under_diagnosis",
    lesson: "'Not real' episodes during exam stress with intact function are anxiety's derealisation, not brain damage — the fear is the signal.",
  },
  {
    line: "A 60-year-old retired army officer, 'routine hai' (it's routine) for everything — wakes 5am, walks exactly 4km, eats the same dal, angry if disrupted. Wife says 'he's always been like this'.",
    expertDifferential: ["OCPD traits (lifelong, ego-syntonic)", "Autism spectrum (if social rigidity)", "Normal personality (wife's account)"],
    expertNext: "Lifelong rigidity + wife's 'always' + no distress from HIM = personality style, not disorder. The distress is hers, not his.",
    trap: "over_diagnosis",
    lesson: "Rigid routines that the person values and the spouse expects are not pathology — the distress belongs to the observer.",
  },
  {
    line: "A 28-year-old woman, 'I don't feel like a woman' after hysterectomy for fibroids. No mood symptoms, sexual function intact, but a persistent hollow feeling.",
    expertDifferential: ["Surgical loss grief (identity)", "Body image adjustment", "Depression (screen anyway)"],
    expertNext: "The hollow feeling is grief for the organ and what it represented — not depression unless anhedonia, sleep, or function shift.",
    trap: "over_diagnosis",
    lesson: "Organ loss grief is a real identity wound — it is not depression unless the mood criteria arrive. Name the loss, screen the mood.",
  },
  {
    line: "A 33-year-old man, 'my heart stops for a second' when he sees his ex's Instagram story. Racing heart, sweating, then anger. He checks her profile 20 times a day.",
    expertDifferential: ["Post-breakup intrusion with physiological arousal", "Panic disorder (if spontaneous)", "Obsessional monitoring (if ritualised)"],
    expertNext: "The trigger-specific arousal + checking = the digital attachment wound. Break the checking cycle, screen mood, process the loss.",
    trap: "under_diagnosis",
    lesson: "Social-media-triggered cardiac sensations + compulsive checking = the modern heartbreak loop. The platform is the maintaining factor.",
  },
  {
    line: "A 5-year-old boy, 'monster in my tummy' every night at bedtime. Settles with a nightlight. No daytime fears, growing well, plays normally.",
    expertDifferential: ["Normal developmental fear (magical thinking)", "Separation anxiety (if broader)", "Gastro issue (if pain described)"],
    expertNext: "Bedtime-only, magical language, nightlight resolves = normal 5-year-old imagination. The nightlight is the treatment.",
    trap: "over_diagnosis",
    lesson: "A 'monster in the tummy' fixed by a nightlight is developmental, not pathological — the child's solution is the diagnosis.",
  },
  {
    line: "A 40-year-old woman, 'I can't breathe' in lifts since the power cut trapped her for 40 minutes. Takes stairs 12 floors. No other avoidance.",
    expertDifferential: ["Specific phobia (lift/elevator)", "Panic disorder (if spontaneous)", "PTSD (if trauma criteria met)"],
    expertNext: "Situation-specific, clear traumatic onset, single avoidance = specific phobia. Exposure works; don't over-treat as panic.",
    trap: "over_diagnosis",
    lesson: "One trapped lift → stairs for life = specific phobia, not panic disorder. The specificity is the diagnosis and the treatment path.",
  },
  {
    line: "A 25-year-old man, 'dil mein dard hai' (pain in heart) when he thinks of his sister's wedding — she married against family wishes, he hasn't spoken to her in 2 years.",
    expertDifferential: ["Grief/loss idiom (unresolved family rupture)", "Depression with somatic focus", "Adjustment disorder"],
    expertNext: "The idiom points to the rupture — 'heart pain' is grief's language. The reconciliation or grief work is the clinical task.",
    idiom: true,
    trap: "cultural_idiom",
    lesson: "'Dil mein dard' is the body speaking the grief the family forbade. The symptom is the unsaid relationship.",
  },
  {
    line: "A 58-year-old man, 'I'm forgetting the words' — pauses mid-sentence, substitutes wrong nouns, aware and frustrated. MMSE 27/30. Wife confirms 18-month decline.",
    expertDifferential: ["Primary progressive aphasia", "Early Alzheimer's (logopenic variant)", "Depression with cognitive complaints (screen)"],
    expertNext: "The fluent pauses + wrong nouns + awareness + MMSE pattern = language-led dementia, not depression. Refer for neurology and speech therapy.",
    trap: "medical_mimic",
    lesson: "Word-finding pauses with wrong substitutions and preserved insight is the language-led dementia signature — not pseudo-dementia.",
  },
  {
    line: "A 17-year-old girl, 'I cut to feel something' — superficial forearm cuts, 6 months, hides them. No suicidal intent. Parents found out, 'she wants attention'.",
    expertDifferential: ["Non-suicidal self-injury (NSSI)", "Borderline personality traits (if pervasive)", "Depression (screen)"],
    expertNext: "'To feel something' is the NSSI signature — validate the pain, screen risk, and refer for DBT-informed therapy. 'Attention' is the wrong frame.",
    trap: "under_diagnosis",
    lesson: "'I cut to feel something' is the NSSI patient telling you the function — it is emotion regulation, not attention. The parents' frame is the barrier.",
  },
  {
    line: "A 36-year-old man, 'I'm fine' but his wife shows you his phone: 47 unread messages from his mother, all answered within 2 minutes. He has panic attacks if he doesn't reply.",
    expertDifferential: ["Enmeshment with panic reinforcement", "Separation anxiety (adult)", "OCD (if ritualised reply pattern)"],
    expertNext: "The panic-if-delayed is the clinical finding — the enmeshment maintains the panic. Exposure to delayed replies is the behavioural task.",
    trap: "iatrogenic",
    lesson: "Instant reply to 47 messages with panic if delayed = the phone is the safety behaviour maintaining the panic. The enmeshment is the prescription.",
  },
  {
    line: "A 70-year-old woman, 'I see children playing in my garden' — she smiles, waves, knows they're not real. No other psychosis, cognitively intact, lives alone.",
    expertDifferential: ["Charles Bonnet syndrome (visual loss + hallucinations)", "Bereavement hallucinations", "Lewy body (if parkinsonism)"],
    expertNext: "Check vision — visual loss + complex formed hallucinations + insight + intact cognition = Charles Bonnet. Reassure, don't antipsychotic.",
    trap: "medical_mimic",
    lesson: "Visual hallucinations with insight in a visually-impaired elder are Charles Bonnet, not psychosis. The eyes are the cause, not the mind.",
  },
  {
    line: "A 24-year-old woman, 'kaan mein awaz aati hai' (voice in ear) — hears her name called when falling asleep, once a week. No other voices, no distress, functions well.",
    expertDifferential: ["Hypnagogic auditory experience (normal)", "Psychosis (if fixed/delusional)", "Anxiety (if distressed by it)"],
    expertNext: "Sleep-onset, name-calling, weekly, no distress = normal hypnagogic phenomenon. Reassure; no antipsychotic, no workup.",
    idiom: true,
    trap: "over_diagnosis",
    lesson: "'Voice in ear' at sleep onset calling your name is the brain's normal border noise — pathologising it is the error.",
  },
  {
    line: "A 42-year-old man, 'my therapist said I have CPTSD' — 2 years of weekly therapy, no formal assessment, no risk screen, no medication review. He functions well at work.",
    expertDifferential: ["Therapist-assigned label without assessment", "Complex trauma (needs real evaluation)", "Depression/anxiety (screen)"],
    expertNext: "A label without assessment is a treatment delay — do the actual history, risk screen, and functional assessment the label skipped.",
    trap: "misattributed_diagnosis",
    lesson: "A therapy label without assessment is not a diagnosis — it is a formulation that delayed the real work. Assess first, label after.",
  },
  {
    line: "A 31-year-old woman, 'I'm pregnant and the baby will be defective' — 12 weeks, normal scans, no family history. She checks the Doppler daily, reads pathology forums nightly.",
    expertDifferential: ["Illness anxiety disorder (pregnancy-focused)", "OCD (health contamination)", "Normal pregnancy anxiety (if proportionate)"],
    expertNext: "The daily Doppler + pathology forums = the anxiety loop, not the pregnancy. CBT for health anxiety, not more scans.",
    trap: "under_diagnosis",
    lesson: "Normal scans + daily Doppler + pathology forums = illness anxiety wearing pregnancy's clothes. The behaviour is the diagnosis.",
  },
  {
    line: "A 55-year-old woman, 'my husband's snoring is killing me' — separate rooms for 3 years, she resents him, has stopped intimacy, says 'I'm fine, just tired'.",
    expertDifferential: ["Relational erosion (sleep divorce)", "Depression with irritability (screen)", "Sleep apnoea in husband (his problem, her sleep)"],
    expertNext: "Three years of separate rooms + resentment + lost intimacy = the marriage is the patient. Screen her mood, then couple work.",
    trap: "over_diagnosis",
    lesson: "Sleep divorce for 3 years is a marital wound, not a diagnosis — the resentment and lost intimacy are the content once mood is screened.",
  },
  {
    line: "A 19-year-old man, 'I'm not smart enough for this course' — second-year engineering, grades dropped from 9 to 5 CGPA, sleeps 12 hours, stopped coding (his passion).",
    expertDifferential: ["Depression (cognitive + anhedonia)", "Burnout", "ADHD (if lifelong, unmasked by load)"],
    expertNext: "The coding stop + 12-hour sleep + 'not smart' = depression's cognitive triad. Screen risk, treat mood, then reassess capacity.",
    trap: "under_diagnosis",
    lesson: "'Not smart enough' with lost passion and hypersomnia is depression's lie — the cognitive symptoms are the mood's costume.",
  },
  {
    line: "A 38-year-old woman, 'mera pet saaf nahi hota' (stomach doesn't clear) — 3 laxatives daily, enema weekly, 5 colonoscopies normal. She weighs 42kg, fears 'toxins'.",
    expertDifferential: ["Laxative abuse / anorexia variant", "Somatic symptom disorder (gut-focused)", "OCD (contamination/toxin)"],
    expertNext: "The 42kg + 5 normal scopes + toxin fear = the laxatives are the disorder, not the constipation. Medical stabilisation + eating disorder referral.",
    idiom: true,
    trap: "medical_mimic",
    lesson: "'Pet saaf nahi hota' at 42kg with 5 normal scopes is an eating disorder speaking through the gut — the laxatives are the symptom, not the treatment.",
  },
  {
    line: "A 27-year-old man, 'I froze' — during his sister's wedding, he couldn't move or speak for 10 minutes. No seizure features, fully aware. Never happened before or since.",
    expertDifferential: ["Dissociative freeze (acute stress)", "Conversion disorder (if recurrent)", "Catatonia (if motor signs)"],
    expertNext: "Single episode, situation-anchored, full awareness = acute dissociative freeze. Reassure, explore the wedding stressor, no neurology needed.",
    trap: "over_diagnosis",
    lesson: "A single wedding freeze with full awareness is the body's emergency brake — not a seizure, not catatonia, not a disorder unless it recurs.",
  },
  {
    line: "A 49-year-old man, 'I drink to sleep' — 4 large whiskies nightly for 10 years. Morning tremor, elevated GGT, denies withdrawal. 'I'll stop when work settles'.",
    expertDifferential: ["Alcohol dependence (severe)", "Alcohol-related liver disease", "Insomnia (the maintained excuse)"],
    expertNext: "10 years + 4 whiskies + tremor + GGT = dependence. The 'work settles' is the denial script. Detox risk assessment first, then motivation.",
    trap: "adherence_fiction",
    lesson: "'I drink to sleep' for 10 years with tremor and GGT is dependence, not insomnia — the insomnia is the excuse the dependence wrote.",
  },
  {
    line: "A 16-year-old boy, 'I'm not a boy' — since puberty, binds chest, uses male name online, distressed by periods. Parents say 'it's a phase'. No psychosis, functions at school.",
    expertDifferential: ["Gender dysphoria (adolescent)", "Body dysmorphia (if focused on specific parts)", "Exploration (if fluid)"],
    expertNext: "Persistent, distressing, puberty-onset = gender dysphoria. Affirm the name, refer to gender service, screen mood (minority stress).",
    trap: "under_diagnosis",
    lesson: "Persistent chest-binding + male name + period distress since puberty is gender dysphoria, not a phase — the parents' denial is the risk factor.",
  },
  {
    line: "A 62-year-old woman, 'I hear the TV talking about me' — volume low, she hears her name and 'she's useless'. Hearing aids help but don't stop it. Cognitively intact.",
    expertDifferential: ["Musical ear syndrome / auditory pareidolia", "Psychosis (if fixed/delusional)", "Charles Bonnet auditory variant"],
    expertNext: "Low-volume TV + name + 'useless' + hearing aids reduce but don't stop = auditory pareidolia. Reassure, optimise hearing, no antipsychotic.",
    trap: "medical_mimic",
    lesson: "TV talking about you at low volume with hearing aids is auditory pareidolia, not psychosis — the deaf brain fills the silence with meaning.",
  },
];