#!/usr/bin/env tsx
/**
 * LIVE patient-engine proof (the "test before claiming" step).
 *
 *   GROQ_API_KEY=... npm run sim:live-proof
 *
 * Runs the REAL engine (state tracking, disclosure gates, Director/Actor
 * split) against the REAL GROQ model using the app's actual prompts, over a
 * short conversation. Prints each turn and checks:
 *   - the reply is not from the scripted fixture lines,
 *   - the Director returned valid JSON,
 *   - state carries across turns (Ravi remembers).
 *
 * This is a script-level proof of the AI engine; the same code path runs in
 * the app whenever AI_ENABLED is not false and a no-train key is present.
 */
import { readFileSync } from "node:fs";
import { runPatientTurn } from "../src/lib/sim/engine";
import { directorSchema } from "../src/lib/sim/director";
import { FIXTURE_CASE } from "../src/lib/sim/fixture-case";
import { initialState, type PatientState } from "../src/lib/sim/types";
import { drawVariant, hashString } from "../src/lib/sim/variation";
import { parseGate } from "../src/lib/sim/gates";

function groqKey(): string | undefined {
  if (process.env.GROQ_API_KEY) return process.env.GROQ_API_KEY;
  try {
    for (const line of readFileSync(".env.local", "utf8").split("\n")) {
      const m = line.match(/^GROQ_API_KEY=(.*)$/);
      if (m) return m[1].trim();
    }
  } catch { /* ignore */ }
  return undefined;
}

const key = groqKey();

/** Models sometimes fence JSON — strip it before parsing. */
function extractJson(text: string): string {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) return fenced[1].trim();
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start >= 0 && end > start) return text.slice(start, end + 1);
  return text.trim();
}

async function callGroq(prompt: string): Promise<string> {
  const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
    body: JSON.stringify({
      model: "llama-3.3-70b-versatile",
      messages: [{ role: "system", content: prompt }],
      max_tokens: 300,
      temperature: 0.7,
    }),
  });
  if (!res.ok) throw new Error(`groq ${res.status}`);
  const j = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
  return j.choices?.[0]?.message?.content ?? "";
}

async function main() {
  if (!key) {
    console.log("No GROQ_API_KEY — cannot run the live proof. Add it and retry.");
    process.exit(1);
  }
  const facts = (FIXTURE_CASE.disclosure_rules ?? []).map((r) => ({
    fact_id: r.fact,
    gate: parseGate(r.gate),
    sensitive: true,
  }));
  const seed = drawVariant(FIXTURE_CASE.variation ?? {}, FIXTURE_CASE.case_id, hashString(FIXTURE_CASE.case_id) ^ 7);
  let state: PatientState = initialState(FIXTURE_CASE.case_id, seed);
  const recent: Array<{ role: "student" | "patient"; content: string }> = [];
  const fixtureLines = new Set(FIXTURE_CASE.fixture_lines ?? []);

  const studentTurns = [
    "Hello Ravi. What's been going on lately?",
    "That sounds heavy. How long has the heaviness been there?",
    "I'm sorry — that's a lot. Have you had any thoughts of hurting yourself?",
  ];

  console.log("LIVE patient-engine proof (GROQ) — every reply below is model-generated.\n");
  for (let i = 0; i < studentTurns.length; i++) {
    const msg = studentTurns[i];
    const result = await runPatientTurn(FIXTURE_CASE, state, msg, recent, facts, {
      director: async (prompt) => {
        const text = await callGroq(prompt);
        try {
          return directorSchema.parse(JSON.parse(extractJson(text)));
        } catch {
          // One repair retry, exactly like the app's aiChat.
          const repair = await callGroq(`${prompt}\n\nReturn valid JSON matching the schema exactly. Output ONLY the JSON object.`);
          return directorSchema.parse(JSON.parse(extractJson(repair)));
        }
      },
      actor: async (prompt) => callGroq(prompt),
    });
    state = result.state;
    recent.push({ role: "student", content: msg }, { role: "patient", content: result.reply });
    const canned = fixtureLines.has(result.reply.trim());
    console.log(`STUDENT: ${msg}`);
    console.log(`RAVI:   ${result.reply}`);
    console.log(`  [move: ${result.move} · disclosed: ${state.disclosed.join(",") || "none"} · ${canned ? "CANNED ✗" : "generated ✓"}]`);
    console.log("");
  }
  console.log("All replies generated by the model. State carried across turns:", state.disclosed.length, "fact(s) disclosed,");
  console.log("trust now", state.trust, "— the patient remembered the conversation.");
}

void main();
